# Blender Probe Generated Stub for Blender 5.0.1
# noinspection PyPep8Naming
# noinspection PyUnresolvedReferences
# noqa: N801
# pylint: disable=invalid-name


import sys
import typing
from typing import Any, Union, Callable, Iterator

class BrushAssetShelf:
    def __init__(self, /, *args, **kwargs) -> Any: ...
    def asset_poll(asset) -> Any: ...
    def brush_type_poll(context, asset) -> Any: ...
    def draw_context_menu(context, asset, layout) -> Any: ...
    def draw_popup_selector(layout, context, brush, show_name=True) -> Any: ...
    def get_active_asset() -> Any: ...
    def get_shelf_name_from_context(context) -> Any: ...
    def has_tool_with_brush_type(context, brush_type) -> Any: ...
    def poll(context) -> Any: ...

class BrushPanel:
    def __init__(self, /, *args, **kwargs) -> Any: ...
    def get_brush_mode(context) -> Any: ...
    def paint_settings(context) -> Any: ...
    def poll(context) -> Any: ...
    def prop_custom_pressure(layout, context, parent_row, brush, *, pressure_name, curve_visibility_name, custom_curve_name) -> Any: ...
    def prop_unified(layout, context, brush, prop_name, unified_paint_settings_override=None, unified_name=None, pressure_name=None, text=None, slider=False, header=False) -> Any: ...
    def prop_unified_color(parent, context, brush, prop_name, *, text=None) -> Any: ...
    def prop_unified_color_picker(parent, context, brush, prop_name, value_slider=True) -> Any: ...

class BrushSelectPanel:
    def __init__(self, /, *args, **kwargs) -> Any: ...
    def draw(self, context) -> Any: ...
    def draw_header_preset(self, context) -> Any: ...
    def get_brush_mode(context) -> Any: ...
    def paint_settings(context) -> Any: ...
    def poll(context) -> Any: ...
    def prop_custom_pressure(layout, context, parent_row, brush, *, pressure_name, curve_visibility_name, custom_curve_name) -> Any: ...
    def prop_unified(layout, context, brush, prop_name, unified_paint_settings_override=None, unified_name=None, pressure_name=None, text=None, slider=False, header=False) -> Any: ...
    def prop_unified_color(parent, context, brush, prop_name, *, text=None) -> Any: ...
    def prop_unified_color_picker(parent, context, brush, prop_name, value_slider=True) -> Any: ...

class ClonePanel:
    def __init__(self, /, *args, **kwargs) -> Any: ...
    def draw(self, context) -> Any: ...
    def draw_header(self, context) -> Any: ...
    def get_brush_mode(context) -> Any: ...
    def paint_settings(context) -> Any: ...
    def poll(context) -> Any: ...
    def prop_custom_pressure(layout, context, parent_row, brush, *, pressure_name, curve_visibility_name, custom_curve_name) -> Any: ...
    def prop_unified(layout, context, brush, prop_name, unified_paint_settings_override=None, unified_name=None, pressure_name=None, text=None, slider=False, header=False) -> Any: ...
    def prop_unified_color(parent, context, brush, prop_name, *, text=None) -> Any: ...
    def prop_unified_color_picker(parent, context, brush, prop_name, value_slider=True) -> Any: ...

class ColorPalettePanel:
    def __init__(self, /, *args, **kwargs) -> Any: ...
    def draw(self, context) -> Any: ...
    def get_brush_mode(context) -> Any: ...
    def paint_settings(context) -> Any: ...
    def poll(context) -> Any: ...
    def prop_custom_pressure(layout, context, parent_row, brush, *, pressure_name, curve_visibility_name, custom_curve_name) -> Any: ...
    def prop_unified(layout, context, brush, prop_name, unified_paint_settings_override=None, unified_name=None, pressure_name=None, text=None, slider=False, header=False) -> Any: ...
    def prop_unified_color(parent, context, brush, prop_name, *, text=None) -> Any: ...
    def prop_unified_color_picker(parent, context, brush, prop_name, value_slider=True) -> Any: ...

class DisplayPanel:
    def __init__(self, /, *args, **kwargs) -> Any: ...
    def draw(self, context) -> Any: ...
    def draw_header(self, context) -> Any: ...
    def get_brush_mode(context) -> Any: ...
    def paint_settings(context) -> Any: ...
    def poll(context) -> Any: ...
    def prop_custom_pressure(layout, context, parent_row, brush, *, pressure_name, curve_visibility_name, custom_curve_name) -> Any: ...
    def prop_unified(layout, context, brush, prop_name, unified_paint_settings_override=None, unified_name=None, pressure_name=None, text=None, slider=False, header=False) -> Any: ...
    def prop_unified_color(parent, context, brush, prop_name, *, text=None) -> Any: ...
    def prop_unified_color_picker(parent, context, brush, prop_name, value_slider=True) -> Any: ...

class FalloffPanel:
    def __init__(self, /, *args, **kwargs) -> Any: ...
    def draw(self, context) -> Any: ...
    def get_brush_mode(context) -> Any: ...
    def paint_settings(context) -> Any: ...
    def poll(context) -> Any: ...
    def prop_custom_pressure(layout, context, parent_row, brush, *, pressure_name, curve_visibility_name, custom_curve_name) -> Any: ...
    def prop_unified(layout, context, brush, prop_name, unified_paint_settings_override=None, unified_name=None, pressure_name=None, text=None, slider=False, header=False) -> Any: ...
    def prop_unified_color(parent, context, brush, prop_name, *, text=None) -> Any: ...
    def prop_unified_color_picker(parent, context, brush, prop_name, value_slider=True) -> Any: ...

class Menu:
    def __init__(self, /, *args, **kwargs) -> Any: ...
    def append(draw_func) -> Any: ...
    def as_pointer(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass_py(*args, **kwargs) -> Any: ...
    def draw_collapsible(context, layout) -> Any: ...
    def draw_preset(self, _context) -> Any: ...
    def driver_add(*args, **kwargs) -> Any: ...
    def driver_remove(*args, **kwargs) -> Any: ...
    def get(*args, **kwargs) -> Any: ...
    id_data: Any
    def id_properties_clear(*args, **kwargs) -> Any: ...
    def id_properties_ensure(*args, **kwargs) -> Any: ...
    def id_properties_ui(*args, **kwargs) -> Any: ...
    def is_extended() -> Any: ...
    def is_property_hidden(*args, **kwargs) -> Any: ...
    def is_property_overridable_library(*args, **kwargs) -> Any: ...
    def is_property_readonly(*args, **kwargs) -> Any: ...
    def is_property_set(*args, **kwargs) -> Any: ...
    def items(*args, **kwargs) -> Any: ...
    def keyframe_delete(*args, **kwargs) -> Any: ...
    def keyframe_insert(*args, **kwargs) -> Any: ...
    def keys(*args, **kwargs) -> Any: ...
    def path_from_id(*args, **kwargs) -> Any: ...
    def path_from_module(*args, **kwargs) -> Any: ...
    def path_menu(self, searchpaths, operator, *, props_default=None, prop_filepath='filepath', filter_ext=None, filter_path=None, display_name=None, add_operator=None, add_operator_props=None, translate=True) -> Any: ...
    def path_resolve(*args, **kwargs) -> Any: ...
    def pop(*args, **kwargs) -> Any: ...
    def prepend(draw_func) -> Any: ...
    def property_overridable_library_set(*args, **kwargs) -> Any: ...
    def property_unset(*args, **kwargs) -> Any: ...
    def remove(draw_func) -> Any: ...
    def rna_ancestors(*args, **kwargs) -> Any: ...
    def type_recast(*args, **kwargs) -> Any: ...
    def values(*args, **kwargs) -> Any: ...

class Panel:
    def __init__(self, /, *args, **kwargs) -> Any: ...
    def append(draw_func) -> Any: ...
    def as_pointer(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass_py(*args, **kwargs) -> Any: ...
    def driver_add(*args, **kwargs) -> Any: ...
    def driver_remove(*args, **kwargs) -> Any: ...
    def get(*args, **kwargs) -> Any: ...
    id_data: Any
    def id_properties_clear(*args, **kwargs) -> Any: ...
    def id_properties_ensure(*args, **kwargs) -> Any: ...
    def id_properties_ui(*args, **kwargs) -> Any: ...
    def is_extended() -> Any: ...
    def is_property_hidden(*args, **kwargs) -> Any: ...
    def is_property_overridable_library(*args, **kwargs) -> Any: ...
    def is_property_readonly(*args, **kwargs) -> Any: ...
    def is_property_set(*args, **kwargs) -> Any: ...
    def items(*args, **kwargs) -> Any: ...
    def keyframe_delete(*args, **kwargs) -> Any: ...
    def keyframe_insert(*args, **kwargs) -> Any: ...
    def keys(*args, **kwargs) -> Any: ...
    def path_from_id(*args, **kwargs) -> Any: ...
    def path_from_module(*args, **kwargs) -> Any: ...
    def path_resolve(*args, **kwargs) -> Any: ...
    def pop(*args, **kwargs) -> Any: ...
    def prepend(draw_func) -> Any: ...
    def property_overridable_library_set(*args, **kwargs) -> Any: ...
    def property_unset(*args, **kwargs) -> Any: ...
    def remove(draw_func) -> Any: ...
    def rna_ancestors(*args, **kwargs) -> Any: ...
    def type_recast(*args, **kwargs) -> Any: ...
    def values(*args, **kwargs) -> Any: ...

class SmoothStrokePanel:
    def __init__(self, /, *args, **kwargs) -> Any: ...
    def draw(self, context) -> Any: ...
    def draw_header(self, context) -> Any: ...
    def get_brush_mode(context) -> Any: ...
    def paint_settings(context) -> Any: ...
    def poll(context) -> Any: ...
    def prop_custom_pressure(layout, context, parent_row, brush, *, pressure_name, curve_visibility_name, custom_curve_name) -> Any: ...
    def prop_unified(layout, context, brush, prop_name, unified_paint_settings_override=None, unified_name=None, pressure_name=None, text=None, slider=False, header=False) -> Any: ...
    def prop_unified_color(parent, context, brush, prop_name, *, text=None) -> Any: ...
    def prop_unified_color_picker(parent, context, brush, prop_name, value_slider=True) -> Any: ...

class StrokePanel:
    def __init__(self, /, *args, **kwargs) -> Any: ...
    def draw(self, context) -> Any: ...
    def get_brush_mode(context) -> Any: ...
    def paint_settings(context) -> Any: ...
    def poll(context) -> Any: ...
    def prop_custom_pressure(layout, context, parent_row, brush, *, pressure_name, curve_visibility_name, custom_curve_name) -> Any: ...
    def prop_unified(layout, context, brush, prop_name, unified_paint_settings_override=None, unified_name=None, pressure_name=None, text=None, slider=False, header=False) -> Any: ...
    def prop_unified_color(parent, context, brush, prop_name, *, text=None) -> Any: ...
    def prop_unified_color_picker(parent, context, brush, prop_name, value_slider=True) -> Any: ...

class TextureMaskPanel:
    def __init__(self, /, *args, **kwargs) -> Any: ...
    def draw(self, context) -> Any: ...
    def get_brush_mode(context) -> Any: ...
    def paint_settings(context) -> Any: ...
    def poll(context) -> Any: ...
    def prop_custom_pressure(layout, context, parent_row, brush, *, pressure_name, curve_visibility_name, custom_curve_name) -> Any: ...
    def prop_unified(layout, context, brush, prop_name, unified_paint_settings_override=None, unified_name=None, pressure_name=None, text=None, slider=False, header=False) -> Any: ...
    def prop_unified_color(parent, context, brush, prop_name, *, text=None) -> Any: ...
    def prop_unified_color_picker(parent, context, brush, prop_name, value_slider=True) -> Any: ...

class UnifiedPaintPanel:
    def __init__(self, /, *args, **kwargs) -> Any: ...
    def get_brush_mode(context) -> Any: ...
    def paint_settings(context) -> Any: ...
    def prop_custom_pressure(layout, context, parent_row, brush, *, pressure_name, curve_visibility_name, custom_curve_name) -> Any: ...
    def prop_unified(layout, context, brush, prop_name, unified_paint_settings_override=None, unified_name=None, pressure_name=None, text=None, slider=False, header=False) -> Any: ...
    def prop_unified_color(parent, context, brush, prop_name, *, text=None) -> Any: ...
    def prop_unified_color_picker(parent, context, brush, prop_name, value_slider=True) -> Any: ...

class VIEW3D_MT_tools_projectpaint_clone:
    def __init__(self, /, *args, **kwargs) -> Any: ...
    def append(draw_func) -> Any: ...
    def as_pointer(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass_py(*args, **kwargs) -> Any: ...
    def draw(self, context) -> Any: ...
    def draw_collapsible(context, layout) -> Any: ...
    def draw_preset(self, _context) -> Any: ...
    def driver_add(*args, **kwargs) -> Any: ...
    def driver_remove(*args, **kwargs) -> Any: ...
    def get(*args, **kwargs) -> Any: ...
    id_data: Any
    def id_properties_clear(*args, **kwargs) -> Any: ...
    def id_properties_ensure(*args, **kwargs) -> Any: ...
    def id_properties_ui(*args, **kwargs) -> Any: ...
    def is_extended() -> Any: ...
    def is_property_hidden(*args, **kwargs) -> Any: ...
    def is_property_overridable_library(*args, **kwargs) -> Any: ...
    def is_property_readonly(*args, **kwargs) -> Any: ...
    def is_property_set(*args, **kwargs) -> Any: ...
    def items(*args, **kwargs) -> Any: ...
    def keyframe_delete(*args, **kwargs) -> Any: ...
    def keyframe_insert(*args, **kwargs) -> Any: ...
    def keys(*args, **kwargs) -> Any: ...
    def path_from_id(*args, **kwargs) -> Any: ...
    def path_from_module(*args, **kwargs) -> Any: ...
    def path_menu(self, searchpaths, operator, *, props_default=None, prop_filepath='filepath', filter_ext=None, filter_path=None, display_name=None, add_operator=None, add_operator_props=None, translate=True) -> Any: ...
    def path_resolve(*args, **kwargs) -> Any: ...
    def pop(*args, **kwargs) -> Any: ...
    def prepend(draw_func) -> Any: ...
    def property_overridable_library_set(*args, **kwargs) -> Any: ...
    def property_unset(*args, **kwargs) -> Any: ...
    def remove(draw_func) -> Any: ...
    def rna_ancestors(*args, **kwargs) -> Any: ...
    def type_recast(*args, **kwargs) -> Any: ...
    def values(*args, **kwargs) -> Any: ...

class VIEW3D_PT_brush_asset_shelf_filter:
    def __init__(self, /, *args, **kwargs) -> Any: ...
    def append(draw_func) -> Any: ...
    def as_pointer(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass_py(*args, **kwargs) -> Any: ...
    def draw(self, context) -> Any: ...
    def driver_add(*args, **kwargs) -> Any: ...
    def driver_remove(*args, **kwargs) -> Any: ...
    def get(*args, **kwargs) -> Any: ...
    id_data: Any
    def id_properties_clear(*args, **kwargs) -> Any: ...
    def id_properties_ensure(*args, **kwargs) -> Any: ...
    def id_properties_ui(*args, **kwargs) -> Any: ...
    def is_extended() -> Any: ...
    def is_property_hidden(*args, **kwargs) -> Any: ...
    def is_property_overridable_library(*args, **kwargs) -> Any: ...
    def is_property_readonly(*args, **kwargs) -> Any: ...
    def is_property_set(*args, **kwargs) -> Any: ...
    def items(*args, **kwargs) -> Any: ...
    def keyframe_delete(*args, **kwargs) -> Any: ...
    def keyframe_insert(*args, **kwargs) -> Any: ...
    def keys(*args, **kwargs) -> Any: ...
    def path_from_id(*args, **kwargs) -> Any: ...
    def path_from_module(*args, **kwargs) -> Any: ...
    def path_resolve(*args, **kwargs) -> Any: ...
    def poll(context) -> Any: ...
    def pop(*args, **kwargs) -> Any: ...
    def prepend(draw_func) -> Any: ...
    def property_overridable_library_set(*args, **kwargs) -> Any: ...
    def property_unset(*args, **kwargs) -> Any: ...
    def remove(draw_func) -> Any: ...
    def rna_ancestors(*args, **kwargs) -> Any: ...
    def type_recast(*args, **kwargs) -> Any: ...
    def values(*args, **kwargs) -> Any: ...

def brush_basic__draw_color_selector(context, layout, brush, gp_settings) -> Any:
    ...

def brush_basic_grease_pencil_paint_settings(layout, context, brush, props, *, compact=False) -> Any:
    ...

def brush_basic_grease_pencil_vertex_settings(layout, context, brush, *, compact=False) -> Any:
    ...

def brush_basic_grease_pencil_weight_settings(layout, context, brush, *, compact=False) -> Any:
    ...

def brush_basic_texpaint_settings(layout, context, brush, *, compact=False) -> Any:
    ...

def brush_mask_texture_settings(layout, brush) -> Any:
    ...

def brush_settings(layout, context, brush, popover=False) -> Any:
    ...

def brush_settings_advanced(layout, context, settings, brush, popover=False) -> Any:
    ...

def brush_shared_settings(layout, context, brush, popover=False) -> Any:
    ...

def brush_texture_settings(layout, brush, sculpt) -> Any:
    ...

classes: Any
def color_jitter_panel(layout, context, brush) -> Any:
    ...

def draw_color_settings(context, layout, brush, color_type=False) -> Any:
    ...

i18n_contexts: Any
def iface_(*args, **kwargs) -> Any:
    ...

def n_(*args, **kwargs) -> Any:
    ...
