# Blender Probe Generated Stub for Blender 5.0.1
# noinspection PyPep8Naming
# noinspection PyUnresolvedReferences
# noqa: N801
# pylint: disable=invalid-name


import sys
import typing
from typing import Any, Union, Callable, Iterator

class ColorAttributesListBase:
    def __init__(self, /, *args, **kwargs) -> Any: ...
    def filter_items(self, _context, data, property) -> Any: ...

class DATA_PT_context_mesh:
    def __init__(self, /, *args, **kwargs) -> Any: ...
    def append(draw_func) -> Any: ...
    def as_pointer(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass_py(*args, **kwargs) -> Any: ...
    def draw(self, context) -> Any: ...
    def driver_add(*args, **kwargs) -> Any: ...
    def driver_remove(*args, **kwargs) -> Any: ...
    def get(*args, **kwargs) -> Any: ...
    id_data: Any
    def id_properties_clear(*args, **kwargs) -> Any: ...
    def id_properties_ensure(*args, **kwargs) -> Any: ...
    def id_properties_ui(*args, **kwargs) -> Any: ...
    def is_extended() -> Any: ...
    def is_property_hidden(*args, **kwargs) -> Any: ...
    def is_property_overridable_library(*args, **kwargs) -> Any: ...
    def is_property_readonly(*args, **kwargs) -> Any: ...
    def is_property_set(*args, **kwargs) -> Any: ...
    def items(*args, **kwargs) -> Any: ...
    def keyframe_delete(*args, **kwargs) -> Any: ...
    def keyframe_insert(*args, **kwargs) -> Any: ...
    def keys(*args, **kwargs) -> Any: ...
    def path_from_id(*args, **kwargs) -> Any: ...
    def path_from_module(*args, **kwargs) -> Any: ...
    def path_resolve(*args, **kwargs) -> Any: ...
    def poll(context) -> Any: ...
    def pop(*args, **kwargs) -> Any: ...
    def prepend(draw_func) -> Any: ...
    def property_overridable_library_set(*args, **kwargs) -> Any: ...
    def property_unset(*args, **kwargs) -> Any: ...
    def remove(draw_func) -> Any: ...
    def rna_ancestors(*args, **kwargs) -> Any: ...
    def type_recast(*args, **kwargs) -> Any: ...
    def values(*args, **kwargs) -> Any: ...

class DATA_PT_custom_props_mesh:
    def __init__(self, /, *args, **kwargs) -> Any: ...
    def append(draw_func) -> Any: ...
    def as_pointer(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass_py(*args, **kwargs) -> Any: ...
    def draw(self, context) -> Any: ...
    def driver_add(*args, **kwargs) -> Any: ...
    def driver_remove(*args, **kwargs) -> Any: ...
    def get(*args, **kwargs) -> Any: ...
    id_data: Any
    def id_properties_clear(*args, **kwargs) -> Any: ...
    def id_properties_ensure(*args, **kwargs) -> Any: ...
    def id_properties_ui(*args, **kwargs) -> Any: ...
    def is_extended() -> Any: ...
    def is_property_hidden(*args, **kwargs) -> Any: ...
    def is_property_overridable_library(*args, **kwargs) -> Any: ...
    def is_property_readonly(*args, **kwargs) -> Any: ...
    def is_property_set(*args, **kwargs) -> Any: ...
    def items(*args, **kwargs) -> Any: ...
    def keyframe_delete(*args, **kwargs) -> Any: ...
    def keyframe_insert(*args, **kwargs) -> Any: ...
    def keys(*args, **kwargs) -> Any: ...
    def path_from_id(*args, **kwargs) -> Any: ...
    def path_from_module(*args, **kwargs) -> Any: ...
    def path_resolve(*args, **kwargs) -> Any: ...
    def poll(context) -> Any: ...
    def pop(*args, **kwargs) -> Any: ...
    def prepend(draw_func) -> Any: ...
    def property_overridable_library_set(*args, **kwargs) -> Any: ...
    def property_unset(*args, **kwargs) -> Any: ...
    def remove(draw_func) -> Any: ...
    def rna_ancestors(*args, **kwargs) -> Any: ...
    def type_recast(*args, **kwargs) -> Any: ...
    def values(*args, **kwargs) -> Any: ...

class DATA_PT_customdata:
    def __init__(self, /, *args, **kwargs) -> Any: ...
    def append(draw_func) -> Any: ...
    def as_pointer(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass_py(*args, **kwargs) -> Any: ...
    def draw(self, context) -> Any: ...
    def driver_add(*args, **kwargs) -> Any: ...
    def driver_remove(*args, **kwargs) -> Any: ...
    def get(*args, **kwargs) -> Any: ...
    id_data: Any
    def id_properties_clear(*args, **kwargs) -> Any: ...
    def id_properties_ensure(*args, **kwargs) -> Any: ...
    def id_properties_ui(*args, **kwargs) -> Any: ...
    def is_extended() -> Any: ...
    def is_property_hidden(*args, **kwargs) -> Any: ...
    def is_property_overridable_library(*args, **kwargs) -> Any: ...
    def is_property_readonly(*args, **kwargs) -> Any: ...
    def is_property_set(*args, **kwargs) -> Any: ...
    def items(*args, **kwargs) -> Any: ...
    def keyframe_delete(*args, **kwargs) -> Any: ...
    def keyframe_insert(*args, **kwargs) -> Any: ...
    def keys(*args, **kwargs) -> Any: ...
    def path_from_id(*args, **kwargs) -> Any: ...
    def path_from_module(*args, **kwargs) -> Any: ...
    def path_resolve(*args, **kwargs) -> Any: ...
    def poll(context) -> Any: ...
    def pop(*args, **kwargs) -> Any: ...
    def prepend(draw_func) -> Any: ...
    def property_overridable_library_set(*args, **kwargs) -> Any: ...
    def property_unset(*args, **kwargs) -> Any: ...
    def remove(draw_func) -> Any: ...
    def rna_ancestors(*args, **kwargs) -> Any: ...
    def type_recast(*args, **kwargs) -> Any: ...
    def values(*args, **kwargs) -> Any: ...

class DATA_PT_mesh_animation:
    def __init__(self, /, *args, **kwargs) -> Any: ...
    def append(draw_func) -> Any: ...
    def as_pointer(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass_py(*args, **kwargs) -> Any: ...
    def draw(self, context) -> Any: ...
    def draw_action_and_slot_selector(context, layout, animated_id) -> Any: ...
    def driver_add(*args, **kwargs) -> Any: ...
    def driver_remove(*args, **kwargs) -> Any: ...
    def get(*args, **kwargs) -> Any: ...
    id_data: Any
    def id_properties_clear(*args, **kwargs) -> Any: ...
    def id_properties_ensure(*args, **kwargs) -> Any: ...
    def id_properties_ui(*args, **kwargs) -> Any: ...
    def is_extended() -> Any: ...
    def is_property_hidden(*args, **kwargs) -> Any: ...
    def is_property_overridable_library(*args, **kwargs) -> Any: ...
    def is_property_readonly(*args, **kwargs) -> Any: ...
    def is_property_set(*args, **kwargs) -> Any: ...
    def items(*args, **kwargs) -> Any: ...
    def keyframe_delete(*args, **kwargs) -> Any: ...
    def keyframe_insert(*args, **kwargs) -> Any: ...
    def keys(*args, **kwargs) -> Any: ...
    def path_from_id(*args, **kwargs) -> Any: ...
    def path_from_module(*args, **kwargs) -> Any: ...
    def path_resolve(*args, **kwargs) -> Any: ...
    def poll(context) -> Any: ...
    def pop(*args, **kwargs) -> Any: ...
    def prepend(draw_func) -> Any: ...
    def property_overridable_library_set(*args, **kwargs) -> Any: ...
    def property_unset(*args, **kwargs) -> Any: ...
    def remove(draw_func) -> Any: ...
    def rna_ancestors(*args, **kwargs) -> Any: ...
    def type_recast(*args, **kwargs) -> Any: ...
    def values(*args, **kwargs) -> Any: ...

class DATA_PT_mesh_attributes:
    def __init__(self, /, *args, **kwargs) -> Any: ...
    def append(draw_func) -> Any: ...
    def as_pointer(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass_py(*args, **kwargs) -> Any: ...
    def draw(self, context) -> Any: ...
    def driver_add(*args, **kwargs) -> Any: ...
    def driver_remove(*args, **kwargs) -> Any: ...
    def get(*args, **kwargs) -> Any: ...
    id_data: Any
    def id_properties_clear(*args, **kwargs) -> Any: ...
    def id_properties_ensure(*args, **kwargs) -> Any: ...
    def id_properties_ui(*args, **kwargs) -> Any: ...
    def is_extended() -> Any: ...
    def is_property_hidden(*args, **kwargs) -> Any: ...
    def is_property_overridable_library(*args, **kwargs) -> Any: ...
    def is_property_readonly(*args, **kwargs) -> Any: ...
    def is_property_set(*args, **kwargs) -> Any: ...
    def items(*args, **kwargs) -> Any: ...
    def keyframe_delete(*args, **kwargs) -> Any: ...
    def keyframe_insert(*args, **kwargs) -> Any: ...
    def keys(*args, **kwargs) -> Any: ...
    def path_from_id(*args, **kwargs) -> Any: ...
    def path_from_module(*args, **kwargs) -> Any: ...
    def path_resolve(*args, **kwargs) -> Any: ...
    def poll(context) -> Any: ...
    def pop(*args, **kwargs) -> Any: ...
    def prepend(draw_func) -> Any: ...
    def property_overridable_library_set(*args, **kwargs) -> Any: ...
    def property_unset(*args, **kwargs) -> Any: ...
    def remove(draw_func) -> Any: ...
    def rna_ancestors(*args, **kwargs) -> Any: ...
    def type_recast(*args, **kwargs) -> Any: ...
    def values(*args, **kwargs) -> Any: ...

class DATA_PT_remesh:
    def __init__(self, /, *args, **kwargs) -> Any: ...
    def append(draw_func) -> Any: ...
    def as_pointer(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass_py(*args, **kwargs) -> Any: ...
    def draw(self, context) -> Any: ...
    def driver_add(*args, **kwargs) -> Any: ...
    def driver_remove(*args, **kwargs) -> Any: ...
    def get(*args, **kwargs) -> Any: ...
    id_data: Any
    def id_properties_clear(*args, **kwargs) -> Any: ...
    def id_properties_ensure(*args, **kwargs) -> Any: ...
    def id_properties_ui(*args, **kwargs) -> Any: ...
    def is_extended() -> Any: ...
    def is_property_hidden(*args, **kwargs) -> Any: ...
    def is_property_overridable_library(*args, **kwargs) -> Any: ...
    def is_property_readonly(*args, **kwargs) -> Any: ...
    def is_property_set(*args, **kwargs) -> Any: ...
    def items(*args, **kwargs) -> Any: ...
    def keyframe_delete(*args, **kwargs) -> Any: ...
    def keyframe_insert(*args, **kwargs) -> Any: ...
    def keys(*args, **kwargs) -> Any: ...
    def path_from_id(*args, **kwargs) -> Any: ...
    def path_from_module(*args, **kwargs) -> Any: ...
    def path_resolve(*args, **kwargs) -> Any: ...
    def poll(context) -> Any: ...
    def pop(*args, **kwargs) -> Any: ...
    def prepend(draw_func) -> Any: ...
    def property_overridable_library_set(*args, **kwargs) -> Any: ...
    def property_unset(*args, **kwargs) -> Any: ...
    def remove(draw_func) -> Any: ...
    def rna_ancestors(*args, **kwargs) -> Any: ...
    def type_recast(*args, **kwargs) -> Any: ...
    def values(*args, **kwargs) -> Any: ...

class DATA_PT_shape_keys:
    def __init__(self, /, *args, **kwargs) -> Any: ...
    def append(draw_func) -> Any: ...
    def as_pointer(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass_py(*args, **kwargs) -> Any: ...
    def draw(self, context) -> Any: ...
    def driver_add(*args, **kwargs) -> Any: ...
    def driver_remove(*args, **kwargs) -> Any: ...
    def get(*args, **kwargs) -> Any: ...
    id_data: Any
    def id_properties_clear(*args, **kwargs) -> Any: ...
    def id_properties_ensure(*args, **kwargs) -> Any: ...
    def id_properties_ui(*args, **kwargs) -> Any: ...
    def is_extended() -> Any: ...
    def is_property_hidden(*args, **kwargs) -> Any: ...
    def is_property_overridable_library(*args, **kwargs) -> Any: ...
    def is_property_readonly(*args, **kwargs) -> Any: ...
    def is_property_set(*args, **kwargs) -> Any: ...
    def items(*args, **kwargs) -> Any: ...
    def keyframe_delete(*args, **kwargs) -> Any: ...
    def keyframe_insert(*args, **kwargs) -> Any: ...
    def keys(*args, **kwargs) -> Any: ...
    def path_from_id(*args, **kwargs) -> Any: ...
    def path_from_module(*args, **kwargs) -> Any: ...
    def path_resolve(*args, **kwargs) -> Any: ...
    def poll(context) -> Any: ...
    def pop(*args, **kwargs) -> Any: ...
    def prepend(draw_func) -> Any: ...
    def property_overridable_library_set(*args, **kwargs) -> Any: ...
    def property_unset(*args, **kwargs) -> Any: ...
    def remove(draw_func) -> Any: ...
    def rna_ancestors(*args, **kwargs) -> Any: ...
    def type_recast(*args, **kwargs) -> Any: ...
    def values(*args, **kwargs) -> Any: ...

class DATA_PT_texture_space:
    def __init__(self, /, *args, **kwargs) -> Any: ...
    def append(draw_func) -> Any: ...
    def as_pointer(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass_py(*args, **kwargs) -> Any: ...
    def draw(self, context) -> Any: ...
    def driver_add(*args, **kwargs) -> Any: ...
    def driver_remove(*args, **kwargs) -> Any: ...
    def get(*args, **kwargs) -> Any: ...
    id_data: Any
    def id_properties_clear(*args, **kwargs) -> Any: ...
    def id_properties_ensure(*args, **kwargs) -> Any: ...
    def id_properties_ui(*args, **kwargs) -> Any: ...
    def is_extended() -> Any: ...
    def is_property_hidden(*args, **kwargs) -> Any: ...
    def is_property_overridable_library(*args, **kwargs) -> Any: ...
    def is_property_readonly(*args, **kwargs) -> Any: ...
    def is_property_set(*args, **kwargs) -> Any: ...
    def items(*args, **kwargs) -> Any: ...
    def keyframe_delete(*args, **kwargs) -> Any: ...
    def keyframe_insert(*args, **kwargs) -> Any: ...
    def keys(*args, **kwargs) -> Any: ...
    def path_from_id(*args, **kwargs) -> Any: ...
    def path_from_module(*args, **kwargs) -> Any: ...
    def path_resolve(*args, **kwargs) -> Any: ...
    def poll(context) -> Any: ...
    def pop(*args, **kwargs) -> Any: ...
    def prepend(draw_func) -> Any: ...
    def property_overridable_library_set(*args, **kwargs) -> Any: ...
    def property_unset(*args, **kwargs) -> Any: ...
    def remove(draw_func) -> Any: ...
    def rna_ancestors(*args, **kwargs) -> Any: ...
    def type_recast(*args, **kwargs) -> Any: ...
    def values(*args, **kwargs) -> Any: ...

class DATA_PT_uv_texture:
    def __init__(self, /, *args, **kwargs) -> Any: ...
    def append(draw_func) -> Any: ...
    def as_pointer(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass_py(*args, **kwargs) -> Any: ...
    def draw(self, context) -> Any: ...
    def driver_add(*args, **kwargs) -> Any: ...
    def driver_remove(*args, **kwargs) -> Any: ...
    def get(*args, **kwargs) -> Any: ...
    id_data: Any
    def id_properties_clear(*args, **kwargs) -> Any: ...
    def id_properties_ensure(*args, **kwargs) -> Any: ...
    def id_properties_ui(*args, **kwargs) -> Any: ...
    def is_extended() -> Any: ...
    def is_property_hidden(*args, **kwargs) -> Any: ...
    def is_property_overridable_library(*args, **kwargs) -> Any: ...
    def is_property_readonly(*args, **kwargs) -> Any: ...
    def is_property_set(*args, **kwargs) -> Any: ...
    def items(*args, **kwargs) -> Any: ...
    def keyframe_delete(*args, **kwargs) -> Any: ...
    def keyframe_insert(*args, **kwargs) -> Any: ...
    def keys(*args, **kwargs) -> Any: ...
    def path_from_id(*args, **kwargs) -> Any: ...
    def path_from_module(*args, **kwargs) -> Any: ...
    def path_resolve(*args, **kwargs) -> Any: ...
    def poll(context) -> Any: ...
    def pop(*args, **kwargs) -> Any: ...
    def prepend(draw_func) -> Any: ...
    def property_overridable_library_set(*args, **kwargs) -> Any: ...
    def property_unset(*args, **kwargs) -> Any: ...
    def remove(draw_func) -> Any: ...
    def rna_ancestors(*args, **kwargs) -> Any: ...
    def type_recast(*args, **kwargs) -> Any: ...
    def values(*args, **kwargs) -> Any: ...

class DATA_PT_vertex_colors:
    def __init__(self, /, *args, **kwargs) -> Any: ...
    def append(draw_func) -> Any: ...
    def as_pointer(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass_py(*args, **kwargs) -> Any: ...
    def draw(self, context) -> Any: ...
    def driver_add(*args, **kwargs) -> Any: ...
    def driver_remove(*args, **kwargs) -> Any: ...
    def get(*args, **kwargs) -> Any: ...
    id_data: Any
    def id_properties_clear(*args, **kwargs) -> Any: ...
    def id_properties_ensure(*args, **kwargs) -> Any: ...
    def id_properties_ui(*args, **kwargs) -> Any: ...
    def is_extended() -> Any: ...
    def is_property_hidden(*args, **kwargs) -> Any: ...
    def is_property_overridable_library(*args, **kwargs) -> Any: ...
    def is_property_readonly(*args, **kwargs) -> Any: ...
    def is_property_set(*args, **kwargs) -> Any: ...
    def items(*args, **kwargs) -> Any: ...
    def keyframe_delete(*args, **kwargs) -> Any: ...
    def keyframe_insert(*args, **kwargs) -> Any: ...
    def keys(*args, **kwargs) -> Any: ...
    def path_from_id(*args, **kwargs) -> Any: ...
    def path_from_module(*args, **kwargs) -> Any: ...
    def path_resolve(*args, **kwargs) -> Any: ...
    def poll(context) -> Any: ...
    def pop(*args, **kwargs) -> Any: ...
    def prepend(draw_func) -> Any: ...
    def property_overridable_library_set(*args, **kwargs) -> Any: ...
    def property_unset(*args, **kwargs) -> Any: ...
    def remove(draw_func) -> Any: ...
    def rna_ancestors(*args, **kwargs) -> Any: ...
    def type_recast(*args, **kwargs) -> Any: ...
    def values(*args, **kwargs) -> Any: ...

class DATA_PT_vertex_groups:
    def __init__(self, /, *args, **kwargs) -> Any: ...
    def append(draw_func) -> Any: ...
    def as_pointer(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass_py(*args, **kwargs) -> Any: ...
    def draw(self, context) -> Any: ...
    def driver_add(*args, **kwargs) -> Any: ...
    def driver_remove(*args, **kwargs) -> Any: ...
    def get(*args, **kwargs) -> Any: ...
    id_data: Any
    def id_properties_clear(*args, **kwargs) -> Any: ...
    def id_properties_ensure(*args, **kwargs) -> Any: ...
    def id_properties_ui(*args, **kwargs) -> Any: ...
    def is_extended() -> Any: ...
    def is_property_hidden(*args, **kwargs) -> Any: ...
    def is_property_overridable_library(*args, **kwargs) -> Any: ...
    def is_property_readonly(*args, **kwargs) -> Any: ...
    def is_property_set(*args, **kwargs) -> Any: ...
    def items(*args, **kwargs) -> Any: ...
    def keyframe_delete(*args, **kwargs) -> Any: ...
    def keyframe_insert(*args, **kwargs) -> Any: ...
    def keys(*args, **kwargs) -> Any: ...
    def path_from_id(*args, **kwargs) -> Any: ...
    def path_from_module(*args, **kwargs) -> Any: ...
    def path_resolve(*args, **kwargs) -> Any: ...
    def poll(context) -> Any: ...
    def pop(*args, **kwargs) -> Any: ...
    def prepend(draw_func) -> Any: ...
    def property_overridable_library_set(*args, **kwargs) -> Any: ...
    def property_unset(*args, **kwargs) -> Any: ...
    def remove(draw_func) -> Any: ...
    def rna_ancestors(*args, **kwargs) -> Any: ...
    def type_recast(*args, **kwargs) -> Any: ...
    def values(*args, **kwargs) -> Any: ...

class MESH_MT_attribute_context_menu:
    def __init__(self, /, *args, **kwargs) -> Any: ...
    def append(draw_func) -> Any: ...
    def as_pointer(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass_py(*args, **kwargs) -> Any: ...
    def draw(self, _context) -> Any: ...
    def draw_collapsible(context, layout) -> Any: ...
    def draw_preset(self, _context) -> Any: ...
    def driver_add(*args, **kwargs) -> Any: ...
    def driver_remove(*args, **kwargs) -> Any: ...
    def get(*args, **kwargs) -> Any: ...
    id_data: Any
    def id_properties_clear(*args, **kwargs) -> Any: ...
    def id_properties_ensure(*args, **kwargs) -> Any: ...
    def id_properties_ui(*args, **kwargs) -> Any: ...
    def is_extended() -> Any: ...
    def is_property_hidden(*args, **kwargs) -> Any: ...
    def is_property_overridable_library(*args, **kwargs) -> Any: ...
    def is_property_readonly(*args, **kwargs) -> Any: ...
    def is_property_set(*args, **kwargs) -> Any: ...
    def items(*args, **kwargs) -> Any: ...
    def keyframe_delete(*args, **kwargs) -> Any: ...
    def keyframe_insert(*args, **kwargs) -> Any: ...
    def keys(*args, **kwargs) -> Any: ...
    def path_from_id(*args, **kwargs) -> Any: ...
    def path_from_module(*args, **kwargs) -> Any: ...
    def path_menu(self, searchpaths, operator, *, props_default=None, prop_filepath='filepath', filter_ext=None, filter_path=None, display_name=None, add_operator=None, add_operator_props=None, translate=True) -> Any: ...
    def path_resolve(*args, **kwargs) -> Any: ...
    def pop(*args, **kwargs) -> Any: ...
    def prepend(draw_func) -> Any: ...
    def property_overridable_library_set(*args, **kwargs) -> Any: ...
    def property_unset(*args, **kwargs) -> Any: ...
    def remove(draw_func) -> Any: ...
    def rna_ancestors(*args, **kwargs) -> Any: ...
    def type_recast(*args, **kwargs) -> Any: ...
    def values(*args, **kwargs) -> Any: ...

class MESH_MT_color_attribute_context_menu:
    def __init__(self, /, *args, **kwargs) -> Any: ...
    def append(draw_func) -> Any: ...
    def as_pointer(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass_py(*args, **kwargs) -> Any: ...
    def draw(self, _context) -> Any: ...
    def draw_collapsible(context, layout) -> Any: ...
    def draw_preset(self, _context) -> Any: ...
    def driver_add(*args, **kwargs) -> Any: ...
    def driver_remove(*args, **kwargs) -> Any: ...
    def get(*args, **kwargs) -> Any: ...
    id_data: Any
    def id_properties_clear(*args, **kwargs) -> Any: ...
    def id_properties_ensure(*args, **kwargs) -> Any: ...
    def id_properties_ui(*args, **kwargs) -> Any: ...
    def is_extended() -> Any: ...
    def is_property_hidden(*args, **kwargs) -> Any: ...
    def is_property_overridable_library(*args, **kwargs) -> Any: ...
    def is_property_readonly(*args, **kwargs) -> Any: ...
    def is_property_set(*args, **kwargs) -> Any: ...
    def items(*args, **kwargs) -> Any: ...
    def keyframe_delete(*args, **kwargs) -> Any: ...
    def keyframe_insert(*args, **kwargs) -> Any: ...
    def keys(*args, **kwargs) -> Any: ...
    def path_from_id(*args, **kwargs) -> Any: ...
    def path_from_module(*args, **kwargs) -> Any: ...
    def path_menu(self, searchpaths, operator, *, props_default=None, prop_filepath='filepath', filter_ext=None, filter_path=None, display_name=None, add_operator=None, add_operator_props=None, translate=True) -> Any: ...
    def path_resolve(*args, **kwargs) -> Any: ...
    def pop(*args, **kwargs) -> Any: ...
    def prepend(draw_func) -> Any: ...
    def property_overridable_library_set(*args, **kwargs) -> Any: ...
    def property_unset(*args, **kwargs) -> Any: ...
    def remove(draw_func) -> Any: ...
    def rna_ancestors(*args, **kwargs) -> Any: ...
    def type_recast(*args, **kwargs) -> Any: ...
    def values(*args, **kwargs) -> Any: ...

class MESH_MT_shape_key_context_menu:
    def __init__(self, /, *args, **kwargs) -> Any: ...
    def append(draw_func) -> Any: ...
    def as_pointer(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass_py(*args, **kwargs) -> Any: ...
    def draw(self, _context) -> Any: ...
    def draw_collapsible(context, layout) -> Any: ...
    def draw_preset(self, _context) -> Any: ...
    def driver_add(*args, **kwargs) -> Any: ...
    def driver_remove(*args, **kwargs) -> Any: ...
    def get(*args, **kwargs) -> Any: ...
    id_data: Any
    def id_properties_clear(*args, **kwargs) -> Any: ...
    def id_properties_ensure(*args, **kwargs) -> Any: ...
    def id_properties_ui(*args, **kwargs) -> Any: ...
    def is_extended() -> Any: ...
    def is_property_hidden(*args, **kwargs) -> Any: ...
    def is_property_overridable_library(*args, **kwargs) -> Any: ...
    def is_property_readonly(*args, **kwargs) -> Any: ...
    def is_property_set(*args, **kwargs) -> Any: ...
    def items(*args, **kwargs) -> Any: ...
    def keyframe_delete(*args, **kwargs) -> Any: ...
    def keyframe_insert(*args, **kwargs) -> Any: ...
    def keys(*args, **kwargs) -> Any: ...
    def path_from_id(*args, **kwargs) -> Any: ...
    def path_from_module(*args, **kwargs) -> Any: ...
    def path_menu(self, searchpaths, operator, *, props_default=None, prop_filepath='filepath', filter_ext=None, filter_path=None, display_name=None, add_operator=None, add_operator_props=None, translate=True) -> Any: ...
    def path_resolve(*args, **kwargs) -> Any: ...
    def pop(*args, **kwargs) -> Any: ...
    def prepend(draw_func) -> Any: ...
    def property_overridable_library_set(*args, **kwargs) -> Any: ...
    def property_unset(*args, **kwargs) -> Any: ...
    def remove(draw_func) -> Any: ...
    def rna_ancestors(*args, **kwargs) -> Any: ...
    def type_recast(*args, **kwargs) -> Any: ...
    def values(*args, **kwargs) -> Any: ...

class MESH_MT_shape_key_tree_context_menu:
    def __init__(self, /, *args, **kwargs) -> Any: ...
    def append(draw_func) -> Any: ...
    def as_pointer(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass_py(*args, **kwargs) -> Any: ...
    def draw(self, _context) -> Any: ...
    def draw_collapsible(context, layout) -> Any: ...
    def draw_preset(self, _context) -> Any: ...
    def driver_add(*args, **kwargs) -> Any: ...
    def driver_remove(*args, **kwargs) -> Any: ...
    def get(*args, **kwargs) -> Any: ...
    id_data: Any
    def id_properties_clear(*args, **kwargs) -> Any: ...
    def id_properties_ensure(*args, **kwargs) -> Any: ...
    def id_properties_ui(*args, **kwargs) -> Any: ...
    def is_extended() -> Any: ...
    def is_property_hidden(*args, **kwargs) -> Any: ...
    def is_property_overridable_library(*args, **kwargs) -> Any: ...
    def is_property_readonly(*args, **kwargs) -> Any: ...
    def is_property_set(*args, **kwargs) -> Any: ...
    def items(*args, **kwargs) -> Any: ...
    def keyframe_delete(*args, **kwargs) -> Any: ...
    def keyframe_insert(*args, **kwargs) -> Any: ...
    def keys(*args, **kwargs) -> Any: ...
    def path_from_id(*args, **kwargs) -> Any: ...
    def path_from_module(*args, **kwargs) -> Any: ...
    def path_menu(self, searchpaths, operator, *, props_default=None, prop_filepath='filepath', filter_ext=None, filter_path=None, display_name=None, add_operator=None, add_operator_props=None, translate=True) -> Any: ...
    def path_resolve(*args, **kwargs) -> Any: ...
    def pop(*args, **kwargs) -> Any: ...
    def prepend(draw_func) -> Any: ...
    def property_overridable_library_set(*args, **kwargs) -> Any: ...
    def property_unset(*args, **kwargs) -> Any: ...
    def remove(draw_func) -> Any: ...
    def rna_ancestors(*args, **kwargs) -> Any: ...
    def type_recast(*args, **kwargs) -> Any: ...
    def values(*args, **kwargs) -> Any: ...

class MESH_MT_vertex_group_context_menu:
    def __init__(self, /, *args, **kwargs) -> Any: ...
    def append(draw_func) -> Any: ...
    def as_pointer(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass_py(*args, **kwargs) -> Any: ...
    def draw(self, _context) -> Any: ...
    def draw_collapsible(context, layout) -> Any: ...
    def draw_preset(self, _context) -> Any: ...
    def driver_add(*args, **kwargs) -> Any: ...
    def driver_remove(*args, **kwargs) -> Any: ...
    def get(*args, **kwargs) -> Any: ...
    id_data: Any
    def id_properties_clear(*args, **kwargs) -> Any: ...
    def id_properties_ensure(*args, **kwargs) -> Any: ...
    def id_properties_ui(*args, **kwargs) -> Any: ...
    def is_extended() -> Any: ...
    def is_property_hidden(*args, **kwargs) -> Any: ...
    def is_property_overridable_library(*args, **kwargs) -> Any: ...
    def is_property_readonly(*args, **kwargs) -> Any: ...
    def is_property_set(*args, **kwargs) -> Any: ...
    def items(*args, **kwargs) -> Any: ...
    def keyframe_delete(*args, **kwargs) -> Any: ...
    def keyframe_insert(*args, **kwargs) -> Any: ...
    def keys(*args, **kwargs) -> Any: ...
    def path_from_id(*args, **kwargs) -> Any: ...
    def path_from_module(*args, **kwargs) -> Any: ...
    def path_menu(self, searchpaths, operator, *, props_default=None, prop_filepath='filepath', filter_ext=None, filter_path=None, display_name=None, add_operator=None, add_operator_props=None, translate=True) -> Any: ...
    def path_resolve(*args, **kwargs) -> Any: ...
    def pop(*args, **kwargs) -> Any: ...
    def prepend(draw_func) -> Any: ...
    def property_overridable_library_set(*args, **kwargs) -> Any: ...
    def property_unset(*args, **kwargs) -> Any: ...
    def remove(draw_func) -> Any: ...
    def rna_ancestors(*args, **kwargs) -> Any: ...
    def type_recast(*args, **kwargs) -> Any: ...
    def values(*args, **kwargs) -> Any: ...

class MESH_UL_attributes:
    def __init__(self, /, *args, **kwargs) -> Any: ...
    def append(draw_func) -> Any: ...
    def as_pointer(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass_py(*args, **kwargs) -> Any: ...
    def draw_item(self, _context, layout, _data, attribute, _icon, _active_data, _active_propname, _index) -> Any: ...
    def driver_add(*args, **kwargs) -> Any: ...
    def driver_remove(*args, **kwargs) -> Any: ...
    def filter_items(self, _context, data, property) -> Any: ...
    def get(*args, **kwargs) -> Any: ...
    id_data: Any
    def id_properties_clear(*args, **kwargs) -> Any: ...
    def id_properties_ensure(*args, **kwargs) -> Any: ...
    def id_properties_ui(*args, **kwargs) -> Any: ...
    def is_extended() -> Any: ...
    def is_property_hidden(*args, **kwargs) -> Any: ...
    def is_property_overridable_library(*args, **kwargs) -> Any: ...
    def is_property_readonly(*args, **kwargs) -> Any: ...
    def is_property_set(*args, **kwargs) -> Any: ...
    def items(*args, **kwargs) -> Any: ...
    def keyframe_delete(*args, **kwargs) -> Any: ...
    def keyframe_insert(*args, **kwargs) -> Any: ...
    def keys(*args, **kwargs) -> Any: ...
    def path_from_id(*args, **kwargs) -> Any: ...
    def path_from_module(*args, **kwargs) -> Any: ...
    def path_resolve(*args, **kwargs) -> Any: ...
    def pop(*args, **kwargs) -> Any: ...
    def prepend(draw_func) -> Any: ...
    def property_overridable_library_set(*args, **kwargs) -> Any: ...
    def property_unset(*args, **kwargs) -> Any: ...
    def remove(draw_func) -> Any: ...
    def rna_ancestors(*args, **kwargs) -> Any: ...
    def type_recast(*args, **kwargs) -> Any: ...
    def values(*args, **kwargs) -> Any: ...

class MESH_UL_color_attributes:
    def __init__(self, /, *args, **kwargs) -> Any: ...
    def append(draw_func) -> Any: ...
    def as_pointer(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass_py(*args, **kwargs) -> Any: ...
    def draw_item(self, _context, layout, data, attribute, _icon, _active_data, _active_propname, _index) -> Any: ...
    def driver_add(*args, **kwargs) -> Any: ...
    def driver_remove(*args, **kwargs) -> Any: ...
    def filter_items(self, _context, data, property) -> Any: ...
    def get(*args, **kwargs) -> Any: ...
    id_data: Any
    def id_properties_clear(*args, **kwargs) -> Any: ...
    def id_properties_ensure(*args, **kwargs) -> Any: ...
    def id_properties_ui(*args, **kwargs) -> Any: ...
    def is_extended() -> Any: ...
    def is_property_hidden(*args, **kwargs) -> Any: ...
    def is_property_overridable_library(*args, **kwargs) -> Any: ...
    def is_property_readonly(*args, **kwargs) -> Any: ...
    def is_property_set(*args, **kwargs) -> Any: ...
    def items(*args, **kwargs) -> Any: ...
    def keyframe_delete(*args, **kwargs) -> Any: ...
    def keyframe_insert(*args, **kwargs) -> Any: ...
    def keys(*args, **kwargs) -> Any: ...
    def path_from_id(*args, **kwargs) -> Any: ...
    def path_from_module(*args, **kwargs) -> Any: ...
    def path_resolve(*args, **kwargs) -> Any: ...
    def pop(*args, **kwargs) -> Any: ...
    def prepend(draw_func) -> Any: ...
    def property_overridable_library_set(*args, **kwargs) -> Any: ...
    def property_unset(*args, **kwargs) -> Any: ...
    def remove(draw_func) -> Any: ...
    def rna_ancestors(*args, **kwargs) -> Any: ...
    def type_recast(*args, **kwargs) -> Any: ...
    def values(*args, **kwargs) -> Any: ...

class MESH_UL_color_attributes_selector:
    def __init__(self, /, *args, **kwargs) -> Any: ...
    def append(draw_func) -> Any: ...
    def as_pointer(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass_py(*args, **kwargs) -> Any: ...
    def draw_item(self, _context, layout, _data, attribute, _icon, _active_data, _active_propname, _index) -> Any: ...
    def driver_add(*args, **kwargs) -> Any: ...
    def driver_remove(*args, **kwargs) -> Any: ...
    def filter_items(self, _context, data, property) -> Any: ...
    def get(*args, **kwargs) -> Any: ...
    id_data: Any
    def id_properties_clear(*args, **kwargs) -> Any: ...
    def id_properties_ensure(*args, **kwargs) -> Any: ...
    def id_properties_ui(*args, **kwargs) -> Any: ...
    def is_extended() -> Any: ...
    def is_property_hidden(*args, **kwargs) -> Any: ...
    def is_property_overridable_library(*args, **kwargs) -> Any: ...
    def is_property_readonly(*args, **kwargs) -> Any: ...
    def is_property_set(*args, **kwargs) -> Any: ...
    def items(*args, **kwargs) -> Any: ...
    def keyframe_delete(*args, **kwargs) -> Any: ...
    def keyframe_insert(*args, **kwargs) -> Any: ...
    def keys(*args, **kwargs) -> Any: ...
    def path_from_id(*args, **kwargs) -> Any: ...
    def path_from_module(*args, **kwargs) -> Any: ...
    def path_resolve(*args, **kwargs) -> Any: ...
    def pop(*args, **kwargs) -> Any: ...
    def prepend(draw_func) -> Any: ...
    def property_overridable_library_set(*args, **kwargs) -> Any: ...
    def property_unset(*args, **kwargs) -> Any: ...
    def remove(draw_func) -> Any: ...
    def rna_ancestors(*args, **kwargs) -> Any: ...
    def type_recast(*args, **kwargs) -> Any: ...
    def values(*args, **kwargs) -> Any: ...

class MESH_UL_uvmaps:
    def __init__(self, /, *args, **kwargs) -> Any: ...
    def append(draw_func) -> Any: ...
    def as_pointer(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass_py(*args, **kwargs) -> Any: ...
    def draw_item(self, _context, layout, _data, item, icon, _active_data, _active_propname, _index) -> Any: ...
    def driver_add(*args, **kwargs) -> Any: ...
    def driver_remove(*args, **kwargs) -> Any: ...
    def get(*args, **kwargs) -> Any: ...
    id_data: Any
    def id_properties_clear(*args, **kwargs) -> Any: ...
    def id_properties_ensure(*args, **kwargs) -> Any: ...
    def id_properties_ui(*args, **kwargs) -> Any: ...
    def is_extended() -> Any: ...
    def is_property_hidden(*args, **kwargs) -> Any: ...
    def is_property_overridable_library(*args, **kwargs) -> Any: ...
    def is_property_readonly(*args, **kwargs) -> Any: ...
    def is_property_set(*args, **kwargs) -> Any: ...
    def items(*args, **kwargs) -> Any: ...
    def keyframe_delete(*args, **kwargs) -> Any: ...
    def keyframe_insert(*args, **kwargs) -> Any: ...
    def keys(*args, **kwargs) -> Any: ...
    def path_from_id(*args, **kwargs) -> Any: ...
    def path_from_module(*args, **kwargs) -> Any: ...
    def path_resolve(*args, **kwargs) -> Any: ...
    def pop(*args, **kwargs) -> Any: ...
    def prepend(draw_func) -> Any: ...
    def property_overridable_library_set(*args, **kwargs) -> Any: ...
    def property_unset(*args, **kwargs) -> Any: ...
    def remove(draw_func) -> Any: ...
    def rna_ancestors(*args, **kwargs) -> Any: ...
    def type_recast(*args, **kwargs) -> Any: ...
    def values(*args, **kwargs) -> Any: ...

class MESH_UL_vgroups:
    def __init__(self, /, *args, **kwargs) -> Any: ...
    def append(draw_func) -> Any: ...
    def as_pointer(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass_py(*args, **kwargs) -> Any: ...
    def draw_item(self, _context, layout, _data, item, icon, _active_data_, _active_propname, _index) -> Any: ...
    def driver_add(*args, **kwargs) -> Any: ...
    def driver_remove(*args, **kwargs) -> Any: ...
    def get(*args, **kwargs) -> Any: ...
    id_data: Any
    def id_properties_clear(*args, **kwargs) -> Any: ...
    def id_properties_ensure(*args, **kwargs) -> Any: ...
    def id_properties_ui(*args, **kwargs) -> Any: ...
    def is_extended() -> Any: ...
    def is_property_hidden(*args, **kwargs) -> Any: ...
    def is_property_overridable_library(*args, **kwargs) -> Any: ...
    def is_property_readonly(*args, **kwargs) -> Any: ...
    def is_property_set(*args, **kwargs) -> Any: ...
    def items(*args, **kwargs) -> Any: ...
    def keyframe_delete(*args, **kwargs) -> Any: ...
    def keyframe_insert(*args, **kwargs) -> Any: ...
    def keys(*args, **kwargs) -> Any: ...
    def path_from_id(*args, **kwargs) -> Any: ...
    def path_from_module(*args, **kwargs) -> Any: ...
    def path_resolve(*args, **kwargs) -> Any: ...
    def pop(*args, **kwargs) -> Any: ...
    def prepend(draw_func) -> Any: ...
    def property_overridable_library_set(*args, **kwargs) -> Any: ...
    def property_unset(*args, **kwargs) -> Any: ...
    def remove(draw_func) -> Any: ...
    def rna_ancestors(*args, **kwargs) -> Any: ...
    def type_recast(*args, **kwargs) -> Any: ...
    def values(*args, **kwargs) -> Any: ...

class Menu:
    def __init__(self, /, *args, **kwargs) -> Any: ...
    def append(draw_func) -> Any: ...
    def as_pointer(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass_py(*args, **kwargs) -> Any: ...
    def draw_collapsible(context, layout) -> Any: ...
    def draw_preset(self, _context) -> Any: ...
    def driver_add(*args, **kwargs) -> Any: ...
    def driver_remove(*args, **kwargs) -> Any: ...
    def get(*args, **kwargs) -> Any: ...
    id_data: Any
    def id_properties_clear(*args, **kwargs) -> Any: ...
    def id_properties_ensure(*args, **kwargs) -> Any: ...
    def id_properties_ui(*args, **kwargs) -> Any: ...
    def is_extended() -> Any: ...
    def is_property_hidden(*args, **kwargs) -> Any: ...
    def is_property_overridable_library(*args, **kwargs) -> Any: ...
    def is_property_readonly(*args, **kwargs) -> Any: ...
    def is_property_set(*args, **kwargs) -> Any: ...
    def items(*args, **kwargs) -> Any: ...
    def keyframe_delete(*args, **kwargs) -> Any: ...
    def keyframe_insert(*args, **kwargs) -> Any: ...
    def keys(*args, **kwargs) -> Any: ...
    def path_from_id(*args, **kwargs) -> Any: ...
    def path_from_module(*args, **kwargs) -> Any: ...
    def path_menu(self, searchpaths, operator, *, props_default=None, prop_filepath='filepath', filter_ext=None, filter_path=None, display_name=None, add_operator=None, add_operator_props=None, translate=True) -> Any: ...
    def path_resolve(*args, **kwargs) -> Any: ...
    def pop(*args, **kwargs) -> Any: ...
    def prepend(draw_func) -> Any: ...
    def property_overridable_library_set(*args, **kwargs) -> Any: ...
    def property_unset(*args, **kwargs) -> Any: ...
    def remove(draw_func) -> Any: ...
    def rna_ancestors(*args, **kwargs) -> Any: ...
    def type_recast(*args, **kwargs) -> Any: ...
    def values(*args, **kwargs) -> Any: ...

class MeshButtonsPanel:
    def __init__(self, /, *args, **kwargs) -> Any: ...
    def poll(context) -> Any: ...

class Panel:
    def __init__(self, /, *args, **kwargs) -> Any: ...
    def append(draw_func) -> Any: ...
    def as_pointer(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass_py(*args, **kwargs) -> Any: ...
    def driver_add(*args, **kwargs) -> Any: ...
    def driver_remove(*args, **kwargs) -> Any: ...
    def get(*args, **kwargs) -> Any: ...
    id_data: Any
    def id_properties_clear(*args, **kwargs) -> Any: ...
    def id_properties_ensure(*args, **kwargs) -> Any: ...
    def id_properties_ui(*args, **kwargs) -> Any: ...
    def is_extended() -> Any: ...
    def is_property_hidden(*args, **kwargs) -> Any: ...
    def is_property_overridable_library(*args, **kwargs) -> Any: ...
    def is_property_readonly(*args, **kwargs) -> Any: ...
    def is_property_set(*args, **kwargs) -> Any: ...
    def items(*args, **kwargs) -> Any: ...
    def keyframe_delete(*args, **kwargs) -> Any: ...
    def keyframe_insert(*args, **kwargs) -> Any: ...
    def keys(*args, **kwargs) -> Any: ...
    def path_from_id(*args, **kwargs) -> Any: ...
    def path_from_module(*args, **kwargs) -> Any: ...
    def path_resolve(*args, **kwargs) -> Any: ...
    def pop(*args, **kwargs) -> Any: ...
    def prepend(draw_func) -> Any: ...
    def property_overridable_library_set(*args, **kwargs) -> Any: ...
    def property_unset(*args, **kwargs) -> Any: ...
    def remove(draw_func) -> Any: ...
    def rna_ancestors(*args, **kwargs) -> Any: ...
    def type_recast(*args, **kwargs) -> Any: ...
    def values(*args, **kwargs) -> Any: ...

class PropertiesAnimationMixin:
    """Mix-in class for Animation panels.

    This class can be used to show a generic 'Animation' panel for IDs shown in
    the properties editor. Specific ID types need specific subclasses.

    For an example, see DATA_PT_camera_animation in properties_data_camera.py
    """
    def __init__(self, /, *args, **kwargs) -> Any: ...
    def draw(self, context) -> Any: ...
    def draw_action_and_slot_selector(context, layout, animated_id) -> Any: ...
    def poll(context) -> Any: ...

class PropertyPanel:
    """
    The subclass should have its own poll function
    and the variable '_context_path' MUST be set.
    """
    def __init__(self, /, *args, **kwargs) -> Any: ...
    def draw(self, context) -> Any: ...
    def poll(context) -> Any: ...

class UIList:
    def __init__(self, /, *args, **kwargs) -> Any: ...
    def append(draw_func) -> Any: ...
    def as_pointer(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass_py(*args, **kwargs) -> Any: ...
    def driver_add(*args, **kwargs) -> Any: ...
    def driver_remove(*args, **kwargs) -> Any: ...
    def get(*args, **kwargs) -> Any: ...
    id_data: Any
    def id_properties_clear(*args, **kwargs) -> Any: ...
    def id_properties_ensure(*args, **kwargs) -> Any: ...
    def id_properties_ui(*args, **kwargs) -> Any: ...
    def is_extended() -> Any: ...
    def is_property_hidden(*args, **kwargs) -> Any: ...
    def is_property_overridable_library(*args, **kwargs) -> Any: ...
    def is_property_readonly(*args, **kwargs) -> Any: ...
    def is_property_set(*args, **kwargs) -> Any: ...
    def items(*args, **kwargs) -> Any: ...
    def keyframe_delete(*args, **kwargs) -> Any: ...
    def keyframe_insert(*args, **kwargs) -> Any: ...
    def keys(*args, **kwargs) -> Any: ...
    def path_from_id(*args, **kwargs) -> Any: ...
    def path_from_module(*args, **kwargs) -> Any: ...
    def path_resolve(*args, **kwargs) -> Any: ...
    def pop(*args, **kwargs) -> Any: ...
    def prepend(draw_func) -> Any: ...
    def property_overridable_library_set(*args, **kwargs) -> Any: ...
    def property_unset(*args, **kwargs) -> Any: ...
    def remove(draw_func) -> Any: ...
    def rna_ancestors(*args, **kwargs) -> Any: ...
    def type_recast(*args, **kwargs) -> Any: ...
    def values(*args, **kwargs) -> Any: ...

classes: Any
def draw_attribute_warnings(context, layout, attributes) -> Any:
    ...

def draw_shape_key_properties(context, layout) -> Any:
    ...

def iface_(*args, **kwargs) -> Any:
    ...

def rpt_(*args, **kwargs) -> Any:
    ...
