# Blender Probe Generated Stub for Blender 5.0.1
# noinspection PyPep8Naming
# noinspection PyUnresolvedReferences
# noqa: N801
# pylint: disable=invalid-name


import sys
import typing
from typing import Any, Union, Callable, Iterator

class DATA_PT_context_pointcloud:
    def __init__(self, /, *args, **kwargs) -> Any: ...
    def append(draw_func) -> Any: ...
    def as_pointer(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass_py(*args, **kwargs) -> Any: ...
    def draw(self, context) -> Any: ...
    def driver_add(*args, **kwargs) -> Any: ...
    def driver_remove(*args, **kwargs) -> Any: ...
    def get(*args, **kwargs) -> Any: ...
    id_data: Any
    def id_properties_clear(*args, **kwargs) -> Any: ...
    def id_properties_ensure(*args, **kwargs) -> Any: ...
    def id_properties_ui(*args, **kwargs) -> Any: ...
    def is_extended() -> Any: ...
    def is_property_hidden(*args, **kwargs) -> Any: ...
    def is_property_overridable_library(*args, **kwargs) -> Any: ...
    def is_property_readonly(*args, **kwargs) -> Any: ...
    def is_property_set(*args, **kwargs) -> Any: ...
    def items(*args, **kwargs) -> Any: ...
    def keyframe_delete(*args, **kwargs) -> Any: ...
    def keyframe_insert(*args, **kwargs) -> Any: ...
    def keys(*args, **kwargs) -> Any: ...
    def path_from_id(*args, **kwargs) -> Any: ...
    def path_from_module(*args, **kwargs) -> Any: ...
    def path_resolve(*args, **kwargs) -> Any: ...
    def poll(context) -> Any: ...
    def pop(*args, **kwargs) -> Any: ...
    def prepend(draw_func) -> Any: ...
    def property_overridable_library_set(*args, **kwargs) -> Any: ...
    def property_unset(*args, **kwargs) -> Any: ...
    def remove(draw_func) -> Any: ...
    def rna_ancestors(*args, **kwargs) -> Any: ...
    def type_recast(*args, **kwargs) -> Any: ...
    def values(*args, **kwargs) -> Any: ...

class DATA_PT_custom_props_pointcloud:
    def __init__(self, /, *args, **kwargs) -> Any: ...
    def append(draw_func) -> Any: ...
    def as_pointer(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass_py(*args, **kwargs) -> Any: ...
    def draw(self, context) -> Any: ...
    def driver_add(*args, **kwargs) -> Any: ...
    def driver_remove(*args, **kwargs) -> Any: ...
    def get(*args, **kwargs) -> Any: ...
    id_data: Any
    def id_properties_clear(*args, **kwargs) -> Any: ...
    def id_properties_ensure(*args, **kwargs) -> Any: ...
    def id_properties_ui(*args, **kwargs) -> Any: ...
    def is_extended() -> Any: ...
    def is_property_hidden(*args, **kwargs) -> Any: ...
    def is_property_overridable_library(*args, **kwargs) -> Any: ...
    def is_property_readonly(*args, **kwargs) -> Any: ...
    def is_property_set(*args, **kwargs) -> Any: ...
    def items(*args, **kwargs) -> Any: ...
    def keyframe_delete(*args, **kwargs) -> Any: ...
    def keyframe_insert(*args, **kwargs) -> Any: ...
    def keys(*args, **kwargs) -> Any: ...
    def path_from_id(*args, **kwargs) -> Any: ...
    def path_from_module(*args, **kwargs) -> Any: ...
    def path_resolve(*args, **kwargs) -> Any: ...
    def poll(context) -> Any: ...
    def pop(*args, **kwargs) -> Any: ...
    def prepend(draw_func) -> Any: ...
    def property_overridable_library_set(*args, **kwargs) -> Any: ...
    def property_unset(*args, **kwargs) -> Any: ...
    def remove(draw_func) -> Any: ...
    def rna_ancestors(*args, **kwargs) -> Any: ...
    def type_recast(*args, **kwargs) -> Any: ...
    def values(*args, **kwargs) -> Any: ...

class DATA_PT_pointcloud_attributes:
    def __init__(self, /, *args, **kwargs) -> Any: ...
    def append(draw_func) -> Any: ...
    def as_pointer(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass_py(*args, **kwargs) -> Any: ...
    def draw(self, context) -> Any: ...
    def driver_add(*args, **kwargs) -> Any: ...
    def driver_remove(*args, **kwargs) -> Any: ...
    def get(*args, **kwargs) -> Any: ...
    id_data: Any
    def id_properties_clear(*args, **kwargs) -> Any: ...
    def id_properties_ensure(*args, **kwargs) -> Any: ...
    def id_properties_ui(*args, **kwargs) -> Any: ...
    def is_extended() -> Any: ...
    def is_property_hidden(*args, **kwargs) -> Any: ...
    def is_property_overridable_library(*args, **kwargs) -> Any: ...
    def is_property_readonly(*args, **kwargs) -> Any: ...
    def is_property_set(*args, **kwargs) -> Any: ...
    def items(*args, **kwargs) -> Any: ...
    def keyframe_delete(*args, **kwargs) -> Any: ...
    def keyframe_insert(*args, **kwargs) -> Any: ...
    def keys(*args, **kwargs) -> Any: ...
    def path_from_id(*args, **kwargs) -> Any: ...
    def path_from_module(*args, **kwargs) -> Any: ...
    def path_resolve(*args, **kwargs) -> Any: ...
    def poll(context) -> Any: ...
    def pop(*args, **kwargs) -> Any: ...
    def prepend(draw_func) -> Any: ...
    def property_overridable_library_set(*args, **kwargs) -> Any: ...
    def property_unset(*args, **kwargs) -> Any: ...
    def remove(draw_func) -> Any: ...
    def rna_ancestors(*args, **kwargs) -> Any: ...
    def type_recast(*args, **kwargs) -> Any: ...
    def values(*args, **kwargs) -> Any: ...

class DataButtonsPanel:
    def __init__(self, /, *args, **kwargs) -> Any: ...
    def poll(context) -> Any: ...

class Menu:
    def __init__(self, /, *args, **kwargs) -> Any: ...
    def append(draw_func) -> Any: ...
    def as_pointer(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass_py(*args, **kwargs) -> Any: ...
    def draw_collapsible(context, layout) -> Any: ...
    def draw_preset(self, _context) -> Any: ...
    def driver_add(*args, **kwargs) -> Any: ...
    def driver_remove(*args, **kwargs) -> Any: ...
    def get(*args, **kwargs) -> Any: ...
    id_data: Any
    def id_properties_clear(*args, **kwargs) -> Any: ...
    def id_properties_ensure(*args, **kwargs) -> Any: ...
    def id_properties_ui(*args, **kwargs) -> Any: ...
    def is_extended() -> Any: ...
    def is_property_hidden(*args, **kwargs) -> Any: ...
    def is_property_overridable_library(*args, **kwargs) -> Any: ...
    def is_property_readonly(*args, **kwargs) -> Any: ...
    def is_property_set(*args, **kwargs) -> Any: ...
    def items(*args, **kwargs) -> Any: ...
    def keyframe_delete(*args, **kwargs) -> Any: ...
    def keyframe_insert(*args, **kwargs) -> Any: ...
    def keys(*args, **kwargs) -> Any: ...
    def path_from_id(*args, **kwargs) -> Any: ...
    def path_from_module(*args, **kwargs) -> Any: ...
    def path_menu(self, searchpaths, operator, *, props_default=None, prop_filepath='filepath', filter_ext=None, filter_path=None, display_name=None, add_operator=None, add_operator_props=None, translate=True) -> Any: ...
    def path_resolve(*args, **kwargs) -> Any: ...
    def pop(*args, **kwargs) -> Any: ...
    def prepend(draw_func) -> Any: ...
    def property_overridable_library_set(*args, **kwargs) -> Any: ...
    def property_unset(*args, **kwargs) -> Any: ...
    def remove(draw_func) -> Any: ...
    def rna_ancestors(*args, **kwargs) -> Any: ...
    def type_recast(*args, **kwargs) -> Any: ...
    def values(*args, **kwargs) -> Any: ...

class POINTCLOUD_MT_add_attribute:
    def __init__(self, /, *args, **kwargs) -> Any: ...
    def add_standard_attribute(layout, pointcloud, name, data_type, domain) -> Any: ...
    def append(draw_func) -> Any: ...
    def as_pointer(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass_py(*args, **kwargs) -> Any: ...
    def draw(self, context) -> Any: ...
    def draw_collapsible(context, layout) -> Any: ...
    def draw_preset(self, _context) -> Any: ...
    def driver_add(*args, **kwargs) -> Any: ...
    def driver_remove(*args, **kwargs) -> Any: ...
    def get(*args, **kwargs) -> Any: ...
    id_data: Any
    def id_properties_clear(*args, **kwargs) -> Any: ...
    def id_properties_ensure(*args, **kwargs) -> Any: ...
    def id_properties_ui(*args, **kwargs) -> Any: ...
    def is_extended() -> Any: ...
    def is_property_hidden(*args, **kwargs) -> Any: ...
    def is_property_overridable_library(*args, **kwargs) -> Any: ...
    def is_property_readonly(*args, **kwargs) -> Any: ...
    def is_property_set(*args, **kwargs) -> Any: ...
    def items(*args, **kwargs) -> Any: ...
    def keyframe_delete(*args, **kwargs) -> Any: ...
    def keyframe_insert(*args, **kwargs) -> Any: ...
    def keys(*args, **kwargs) -> Any: ...
    def path_from_id(*args, **kwargs) -> Any: ...
    def path_from_module(*args, **kwargs) -> Any: ...
    def path_menu(self, searchpaths, operator, *, props_default=None, prop_filepath='filepath', filter_ext=None, filter_path=None, display_name=None, add_operator=None, add_operator_props=None, translate=True) -> Any: ...
    def path_resolve(*args, **kwargs) -> Any: ...
    def pop(*args, **kwargs) -> Any: ...
    def prepend(draw_func) -> Any: ...
    def property_overridable_library_set(*args, **kwargs) -> Any: ...
    def property_unset(*args, **kwargs) -> Any: ...
    def remove(draw_func) -> Any: ...
    def rna_ancestors(*args, **kwargs) -> Any: ...
    def type_recast(*args, **kwargs) -> Any: ...
    def values(*args, **kwargs) -> Any: ...

class POINTCLOUD_MT_attribute_context_menu:
    def __init__(self, /, *args, **kwargs) -> Any: ...
    def append(draw_func) -> Any: ...
    def as_pointer(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass_py(*args, **kwargs) -> Any: ...
    def draw(self, _context) -> Any: ...
    def draw_collapsible(context, layout) -> Any: ...
    def draw_preset(self, _context) -> Any: ...
    def driver_add(*args, **kwargs) -> Any: ...
    def driver_remove(*args, **kwargs) -> Any: ...
    def get(*args, **kwargs) -> Any: ...
    id_data: Any
    def id_properties_clear(*args, **kwargs) -> Any: ...
    def id_properties_ensure(*args, **kwargs) -> Any: ...
    def id_properties_ui(*args, **kwargs) -> Any: ...
    def is_extended() -> Any: ...
    def is_property_hidden(*args, **kwargs) -> Any: ...
    def is_property_overridable_library(*args, **kwargs) -> Any: ...
    def is_property_readonly(*args, **kwargs) -> Any: ...
    def is_property_set(*args, **kwargs) -> Any: ...
    def items(*args, **kwargs) -> Any: ...
    def keyframe_delete(*args, **kwargs) -> Any: ...
    def keyframe_insert(*args, **kwargs) -> Any: ...
    def keys(*args, **kwargs) -> Any: ...
    def path_from_id(*args, **kwargs) -> Any: ...
    def path_from_module(*args, **kwargs) -> Any: ...
    def path_menu(self, searchpaths, operator, *, props_default=None, prop_filepath='filepath', filter_ext=None, filter_path=None, display_name=None, add_operator=None, add_operator_props=None, translate=True) -> Any: ...
    def path_resolve(*args, **kwargs) -> Any: ...
    def pop(*args, **kwargs) -> Any: ...
    def prepend(draw_func) -> Any: ...
    def property_overridable_library_set(*args, **kwargs) -> Any: ...
    def property_unset(*args, **kwargs) -> Any: ...
    def remove(draw_func) -> Any: ...
    def rna_ancestors(*args, **kwargs) -> Any: ...
    def type_recast(*args, **kwargs) -> Any: ...
    def values(*args, **kwargs) -> Any: ...

class POINTCLOUD_UL_attributes:
    def __init__(self, /, *args, **kwargs) -> Any: ...
    def append(draw_func) -> Any: ...
    def as_pointer(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass_py(*args, **kwargs) -> Any: ...
    def draw_item(self, _context, layout, _data, attribute, _icon, _active_data, _active_propname, _index) -> Any: ...
    def driver_add(*args, **kwargs) -> Any: ...
    def driver_remove(*args, **kwargs) -> Any: ...
    def filter_items(self, _context, data, property) -> Any: ...
    def get(*args, **kwargs) -> Any: ...
    id_data: Any
    def id_properties_clear(*args, **kwargs) -> Any: ...
    def id_properties_ensure(*args, **kwargs) -> Any: ...
    def id_properties_ui(*args, **kwargs) -> Any: ...
    def is_extended() -> Any: ...
    def is_property_hidden(*args, **kwargs) -> Any: ...
    def is_property_overridable_library(*args, **kwargs) -> Any: ...
    def is_property_readonly(*args, **kwargs) -> Any: ...
    def is_property_set(*args, **kwargs) -> Any: ...
    def items(*args, **kwargs) -> Any: ...
    def keyframe_delete(*args, **kwargs) -> Any: ...
    def keyframe_insert(*args, **kwargs) -> Any: ...
    def keys(*args, **kwargs) -> Any: ...
    def path_from_id(*args, **kwargs) -> Any: ...
    def path_from_module(*args, **kwargs) -> Any: ...
    def path_resolve(*args, **kwargs) -> Any: ...
    def pop(*args, **kwargs) -> Any: ...
    def prepend(draw_func) -> Any: ...
    def property_overridable_library_set(*args, **kwargs) -> Any: ...
    def property_unset(*args, **kwargs) -> Any: ...
    def remove(draw_func) -> Any: ...
    def rna_ancestors(*args, **kwargs) -> Any: ...
    def type_recast(*args, **kwargs) -> Any: ...
    def values(*args, **kwargs) -> Any: ...

class Panel:
    def __init__(self, /, *args, **kwargs) -> Any: ...
    def append(draw_func) -> Any: ...
    def as_pointer(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass_py(*args, **kwargs) -> Any: ...
    def driver_add(*args, **kwargs) -> Any: ...
    def driver_remove(*args, **kwargs) -> Any: ...
    def get(*args, **kwargs) -> Any: ...
    id_data: Any
    def id_properties_clear(*args, **kwargs) -> Any: ...
    def id_properties_ensure(*args, **kwargs) -> Any: ...
    def id_properties_ui(*args, **kwargs) -> Any: ...
    def is_extended() -> Any: ...
    def is_property_hidden(*args, **kwargs) -> Any: ...
    def is_property_overridable_library(*args, **kwargs) -> Any: ...
    def is_property_readonly(*args, **kwargs) -> Any: ...
    def is_property_set(*args, **kwargs) -> Any: ...
    def items(*args, **kwargs) -> Any: ...
    def keyframe_delete(*args, **kwargs) -> Any: ...
    def keyframe_insert(*args, **kwargs) -> Any: ...
    def keys(*args, **kwargs) -> Any: ...
    def path_from_id(*args, **kwargs) -> Any: ...
    def path_from_module(*args, **kwargs) -> Any: ...
    def path_resolve(*args, **kwargs) -> Any: ...
    def pop(*args, **kwargs) -> Any: ...
    def prepend(draw_func) -> Any: ...
    def property_overridable_library_set(*args, **kwargs) -> Any: ...
    def property_unset(*args, **kwargs) -> Any: ...
    def remove(draw_func) -> Any: ...
    def rna_ancestors(*args, **kwargs) -> Any: ...
    def type_recast(*args, **kwargs) -> Any: ...
    def values(*args, **kwargs) -> Any: ...

class PropertyPanel:
    """
    The subclass should have its own poll function
    and the variable '_context_path' MUST be set.
    """
    def __init__(self, /, *args, **kwargs) -> Any: ...
    def draw(self, context) -> Any: ...
    def poll(context) -> Any: ...

class UIList:
    def __init__(self, /, *args, **kwargs) -> Any: ...
    def append(draw_func) -> Any: ...
    def as_pointer(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass_py(*args, **kwargs) -> Any: ...
    def driver_add(*args, **kwargs) -> Any: ...
    def driver_remove(*args, **kwargs) -> Any: ...
    def get(*args, **kwargs) -> Any: ...
    id_data: Any
    def id_properties_clear(*args, **kwargs) -> Any: ...
    def id_properties_ensure(*args, **kwargs) -> Any: ...
    def id_properties_ui(*args, **kwargs) -> Any: ...
    def is_extended() -> Any: ...
    def is_property_hidden(*args, **kwargs) -> Any: ...
    def is_property_overridable_library(*args, **kwargs) -> Any: ...
    def is_property_readonly(*args, **kwargs) -> Any: ...
    def is_property_set(*args, **kwargs) -> Any: ...
    def items(*args, **kwargs) -> Any: ...
    def keyframe_delete(*args, **kwargs) -> Any: ...
    def keyframe_insert(*args, **kwargs) -> Any: ...
    def keys(*args, **kwargs) -> Any: ...
    def path_from_id(*args, **kwargs) -> Any: ...
    def path_from_module(*args, **kwargs) -> Any: ...
    def path_resolve(*args, **kwargs) -> Any: ...
    def pop(*args, **kwargs) -> Any: ...
    def prepend(draw_func) -> Any: ...
    def property_overridable_library_set(*args, **kwargs) -> Any: ...
    def property_unset(*args, **kwargs) -> Any: ...
    def remove(draw_func) -> Any: ...
    def rna_ancestors(*args, **kwargs) -> Any: ...
    def type_recast(*args, **kwargs) -> Any: ...
    def values(*args, **kwargs) -> Any: ...

classes: Any