"""
Online Documentation:
https://docs.blender.org/api/current/aud.html
"""

# Blender Probe Generated Stub for Blender 5.0.1
# noinspection PyPep8Naming
# noinspection PyUnresolvedReferences
# noqa: N801
# pylint: disable=invalid-name


import sys
import typing
from typing import Any, Union, Callable, Iterator

AP_LOCATION = 3
AP_ORIENTATION = 4
AP_PANNING = 1
AP_PITCH = 2
AP_PITCH_SCALE = 6
AP_TIME_STRETCH = 5
AP_VOLUME = 0
class AnimateableProperty:
    """An AnimateableProperty object stores an array of float values for animating sound properties (e.g. pan, volume, pitch-scale)"""
    """
    Online Documentation:
    https://docs.blender.org/api/current/aud.html
    """
    def __init__(self, /, *args, **kwargs) -> Any: ...
    animated: Any
    count: Any
    def read(*args, **kwargs) -> Any: ...
    def readSingle(*args, **kwargs) -> Any: ...
    def write(*args, **kwargs) -> Any: ...
    def writeConstantRange(*args, **kwargs) -> Any: ...

CHANNELS_INVALID = 0
CHANNELS_MONO = 1
CHANNELS_STEREO = 2
CHANNELS_STEREO_LFE = 3
CHANNELS_SURROUND4 = 4
CHANNELS_SURROUND5 = 5
CHANNELS_SURROUND51 = 6
CHANNELS_SURROUND61 = 7
CHANNELS_SURROUND71 = 8
CODEC_AAC = 1
CODEC_AC3 = 2
CODEC_FLAC = 3
CODEC_INVALID = 0
CODEC_MP2 = 4
CODEC_MP3 = 5
CODEC_OPUS = 8
CODEC_PCM = 6
CODEC_VORBIS = 7
CONTAINER_AAC = 8
CONTAINER_AC3 = 1
CONTAINER_FLAC = 2
CONTAINER_INVALID = 0
CONTAINER_MATROSKA = 3
CONTAINER_MP2 = 4
CONTAINER_MP3 = 5
CONTAINER_OGG = 6
CONTAINER_WAV = 7
DISTANCE_MODEL_EXPONENT = 5
DISTANCE_MODEL_EXPONENT_CLAMPED = 6
DISTANCE_MODEL_INVALID = 0
DISTANCE_MODEL_INVERSE = 1
DISTANCE_MODEL_INVERSE_CLAMPED = 2
DISTANCE_MODEL_LINEAR = 3
DISTANCE_MODEL_LINEAR_CLAMPED = 4
class Device:
    """Device objects represent an audio output backend like OpenAL or SDL, but might also represent a file output or RAM buffer output."""
    """
    Online Documentation:
    https://docs.blender.org/api/current/aud.html
    """
    def __init__(self, /, *args, **kwargs) -> Any: ...
    channels: Any
    distance_model: Any
    doppler_factor: Any
    format: Any
    listener_location: Any
    listener_orientation: Any
    listener_velocity: Any
    def lock(*args, **kwargs) -> Any: ...
    def play(*args, **kwargs) -> Any: ...
    rate: Any
    speed_of_sound: Any
    def stopAll(*args, **kwargs) -> Any: ...
    def unlock(*args, **kwargs) -> Any: ...
    volume: Any

class DynamicMusic:
    """The DynamicMusic object allows to play music depending on a current scene, scene changes are managed by the class, with the possibility of custom transitions.
The default transition is a crossfade effect, and the default scene is silent and has id 0"""
    """
    Online Documentation:
    https://docs.blender.org/api/current/aud.html
    """
    def __init__(self, /, *args, **kwargs) -> Any: ...
    def addScene(*args, **kwargs) -> Any: ...
    def addTransition(*args, **kwargs) -> Any: ...
    fadeTime: Any
    def pause(*args, **kwargs) -> Any: ...
    position: Any
    def resume(*args, **kwargs) -> Any: ...
    scene: Any
    status: Any
    def stop(*args, **kwargs) -> Any: ...
    volume: Any

FORMAT_FLOAT32 = 36
FORMAT_FLOAT64 = 40
FORMAT_INVALID = 0
FORMAT_S16 = 18
FORMAT_S24 = 19
FORMAT_S32 = 20
FORMAT_U8 = 1
class HRTF:
    """An HRTF object represents a set of head related transfer functions as impulse responses. It's used for binaural sound"""
    """
    Online Documentation:
    https://docs.blender.org/api/current/aud.html
    """
    def __init__(self, /, *args, **kwargs) -> Any: ...
    def addImpulseResponseFromSound(*args, **kwargs) -> Any: ...
    def loadLeftHrtfSet(*args, **kwargs) -> Any: ...
    def loadRightHrtfSet(*args, **kwargs) -> Any: ...

class Handle:
    """Handle objects are playback handles that can be used to control playback of a sound. If a sound is played back multiple times then there are as many handles."""
    """
    Online Documentation:
    https://docs.blender.org/api/current/aud.html
    """
    def __init__(self, /, *args, **kwargs) -> Any: ...
    attenuation: Any
    cone_angle_inner: Any
    cone_angle_outer: Any
    cone_volume_outer: Any
    distance_maximum: Any
    distance_reference: Any
    keep: Any
    location: Any
    loop_count: Any
    orientation: Any
    def pause(*args, **kwargs) -> Any: ...
    pitch: Any
    position: Any
    relative: Any
    def resume(*args, **kwargs) -> Any: ...
    status: Any
    def stop(*args, **kwargs) -> Any: ...
    velocity: Any
    volume: Any
    volume_maximum: Any
    volume_minimum: Any

class ImpulseResponse:
    """An ImpulseResponse object represents a filter with which to convolve a sound."""
    """
    Online Documentation:
    https://docs.blender.org/api/current/aud.html
    """
    def __init__(self, /, *args, **kwargs) -> Any: ...

class PlaybackManager:
    """A PlabackManager object allows to easily control groups os sounds organized in categories."""
    """
    Online Documentation:
    https://docs.blender.org/api/current/aud.html
    """
    def __init__(self, /, *args, **kwargs) -> Any: ...
    def addCategory(*args, **kwargs) -> Any: ...
    def clean(*args, **kwargs) -> Any: ...
    def getVolume(*args, **kwargs) -> Any: ...
    def pause(*args, **kwargs) -> Any: ...
    def play(*args, **kwargs) -> Any: ...
    def resume(*args, **kwargs) -> Any: ...
    def setVolume(*args, **kwargs) -> Any: ...
    def stop(*args, **kwargs) -> Any: ...

RATE_11025 = 11025
RATE_16000 = 16000
RATE_192000 = 192000
RATE_22050 = 22050
RATE_32000 = 32000
RATE_44100 = 44100
RATE_48000 = 48000
RATE_8000 = 8000
RATE_88200 = 88200
RATE_96000 = 96000
RATE_INVALID = 0
STATUS_INVALID = 0
STATUS_PAUSED = 2
STATUS_PLAYING = 1
STATUS_STOPPED = 3
STRETCHER_QUALITY_CONSISTENT = 2
STRETCHER_QUALITY_FAST = 1
STRETCHER_QUALITY_HIGH = 0
class Sequence:
    """This sound represents sequenced entries to play a sound sequence."""
    """
    Online Documentation:
    https://docs.blender.org/api/current/aud.html
    """
    def ADSR(*args, **kwargs) -> Any: ...
    def __init__(self, /, *args, **kwargs) -> Any: ...
    def accumulate(*args, **kwargs) -> Any: ...
    def add(*args, **kwargs) -> Any: ...
    def addSound(*args, **kwargs) -> Any: ...
    def animateableTimeStretchPitchScale(*args, **kwargs) -> Any: ...
    def binaural(*args, **kwargs) -> Any: ...
    def buffer(*args, **kwargs) -> Any: ...
    def cache(*args, **kwargs) -> Any: ...
    channels: Any
    def convolver(*args, **kwargs) -> Any: ...
    def data(*args, **kwargs) -> Any: ...
    def delay(*args, **kwargs) -> Any: ...
    distance_model: Any
    doppler_factor: Any
    def envelope(*args, **kwargs) -> Any: ...
    def fadein(*args, **kwargs) -> Any: ...
    def fadeout(*args, **kwargs) -> Any: ...
    def file(*args, **kwargs) -> Any: ...
    def filter(*args, **kwargs) -> Any: ...
    fps: Any
    def highpass(*args, **kwargs) -> Any: ...
    def join(*args, **kwargs) -> Any: ...
    length: Any
    def limit(*args, **kwargs) -> Any: ...
    def list(*args, **kwargs) -> Any: ...
    def loop(*args, **kwargs) -> Any: ...
    def lowpass(*args, **kwargs) -> Any: ...
    def mix(*args, **kwargs) -> Any: ...
    def modulate(*args, **kwargs) -> Any: ...
    def mutable(*args, **kwargs) -> Any: ...
    muted: Any
    def pingpong(*args, **kwargs) -> Any: ...
    def pitch(*args, **kwargs) -> Any: ...
    rate: Any
    def rechannel(*args, **kwargs) -> Any: ...
    def remove(*args, **kwargs) -> Any: ...
    def resample(*args, **kwargs) -> Any: ...
    def reverse(*args, **kwargs) -> Any: ...
    def sawtooth(*args, **kwargs) -> Any: ...
    def setAnimationData(*args, **kwargs) -> Any: ...
    def silence(*args, **kwargs) -> Any: ...
    def sine(*args, **kwargs) -> Any: ...
    specs: Any
    speed_of_sound: Any
    def square(*args, **kwargs) -> Any: ...
    def sum(*args, **kwargs) -> Any: ...
    def threshold(*args, **kwargs) -> Any: ...
    def timeStretchPitchScale(*args, **kwargs) -> Any: ...
    def triangle(*args, **kwargs) -> Any: ...
    def volume(*args, **kwargs) -> Any: ...
    def write(*args, **kwargs) -> Any: ...

class SequenceEntry:
    """SequenceEntry objects represent an entry of a sequenced sound."""
    """
    Online Documentation:
    https://docs.blender.org/api/current/aud.html
    """
    def __init__(self, /, *args, **kwargs) -> Any: ...
    attenuation: Any
    cone_angle_inner: Any
    cone_angle_outer: Any
    cone_volume_outer: Any
    distance_maximum: Any
    distance_reference: Any
    def move(*args, **kwargs) -> Any: ...
    muted: Any
    relative: Any
    def setAnimationData(*args, **kwargs) -> Any: ...
    sound: Any
    volume_maximum: Any
    volume_minimum: Any

class Sound:
    """Sound objects are immutable and represent a sound that can be played simultaneously multiple times. They are called factories because they create reader objects internally that are used for playback."""
    """
    Online Documentation:
    https://docs.blender.org/api/current/aud.html
    """
    def ADSR(*args, **kwargs) -> Any: ...
    def __init__(self, /, *args, **kwargs) -> Any: ...
    def accumulate(*args, **kwargs) -> Any: ...
    def addSound(*args, **kwargs) -> Any: ...
    def animateableTimeStretchPitchScale(*args, **kwargs) -> Any: ...
    def binaural(*args, **kwargs) -> Any: ...
    def buffer(*args, **kwargs) -> Any: ...
    def cache(*args, **kwargs) -> Any: ...
    def convolver(*args, **kwargs) -> Any: ...
    def data(*args, **kwargs) -> Any: ...
    def delay(*args, **kwargs) -> Any: ...
    def envelope(*args, **kwargs) -> Any: ...
    def fadein(*args, **kwargs) -> Any: ...
    def fadeout(*args, **kwargs) -> Any: ...
    def file(*args, **kwargs) -> Any: ...
    def filter(*args, **kwargs) -> Any: ...
    def highpass(*args, **kwargs) -> Any: ...
    def join(*args, **kwargs) -> Any: ...
    length: Any
    def limit(*args, **kwargs) -> Any: ...
    def list(*args, **kwargs) -> Any: ...
    def loop(*args, **kwargs) -> Any: ...
    def lowpass(*args, **kwargs) -> Any: ...
    def mix(*args, **kwargs) -> Any: ...
    def modulate(*args, **kwargs) -> Any: ...
    def mutable(*args, **kwargs) -> Any: ...
    def pingpong(*args, **kwargs) -> Any: ...
    def pitch(*args, **kwargs) -> Any: ...
    def rechannel(*args, **kwargs) -> Any: ...
    def resample(*args, **kwargs) -> Any: ...
    def reverse(*args, **kwargs) -> Any: ...
    def sawtooth(*args, **kwargs) -> Any: ...
    def silence(*args, **kwargs) -> Any: ...
    def sine(*args, **kwargs) -> Any: ...
    specs: Any
    def square(*args, **kwargs) -> Any: ...
    def sum(*args, **kwargs) -> Any: ...
    def threshold(*args, **kwargs) -> Any: ...
    def timeStretchPitchScale(*args, **kwargs) -> Any: ...
    def triangle(*args, **kwargs) -> Any: ...
    def volume(*args, **kwargs) -> Any: ...
    def write(*args, **kwargs) -> Any: ...

class Source:
    """The source object represents the source position of a binaural sound."""
    """
    Online Documentation:
    https://docs.blender.org/api/current/aud.html
    """
    def __init__(self, /, *args, **kwargs) -> Any: ...
    azimuth: Any
    distance: Any
    elevation: Any

class ThreadPool:
    """A ThreadPool is used to parallelize convolution efficiently."""
    """
    Online Documentation:
    https://docs.blender.org/api/current/aud.html
    """
    def __init__(self, /, *args, **kwargs) -> Any: ...

class error:
    """
    Online Documentation:
    https://docs.blender.org/api/current/aud.html
    """
    def __init__(self, /, *args, **kwargs) -> Any: ...
    def add_note(*args, **kwargs) -> Any: ...
    args: Any
    def with_traceback(*args, **kwargs) -> Any: ...
