# Blender Probe Generated Stub for Blender 5.0.1
# noinspection PyPep8Naming
# noinspection PyUnresolvedReferences
# noqa: N801
# pylint: disable=invalid-name


import sys
import typing
from typing import Any, Union, Callable, Iterator

class Menu:
    def __init__(self, /, *args, **kwargs) -> Any: ...
    def append(draw_func) -> Any: ...
    def as_pointer(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass_py(*args, **kwargs) -> Any: ...
    def draw_collapsible(context, layout) -> Any: ...
    def draw_preset(self, _context) -> Any: ...
    def driver_add(*args, **kwargs) -> Any: ...
    def driver_remove(*args, **kwargs) -> Any: ...
    def get(*args, **kwargs) -> Any: ...
    id_data: Any
    def id_properties_clear(*args, **kwargs) -> Any: ...
    def id_properties_ensure(*args, **kwargs) -> Any: ...
    def id_properties_ui(*args, **kwargs) -> Any: ...
    def is_extended() -> Any: ...
    def is_property_hidden(*args, **kwargs) -> Any: ...
    def is_property_overridable_library(*args, **kwargs) -> Any: ...
    def is_property_readonly(*args, **kwargs) -> Any: ...
    def is_property_set(*args, **kwargs) -> Any: ...
    def items(*args, **kwargs) -> Any: ...
    def keyframe_delete(*args, **kwargs) -> Any: ...
    def keyframe_insert(*args, **kwargs) -> Any: ...
    def keys(*args, **kwargs) -> Any: ...
    def path_from_id(*args, **kwargs) -> Any: ...
    def path_from_module(*args, **kwargs) -> Any: ...
    def path_menu(self, searchpaths, operator, *, props_default=None, prop_filepath='filepath', filter_ext=None, filter_path=None, display_name=None, add_operator=None, add_operator_props=None, translate=True) -> Any: ...
    def path_resolve(*args, **kwargs) -> Any: ...
    def pop(*args, **kwargs) -> Any: ...
    def prepend(draw_func) -> Any: ...
    def property_overridable_library_set(*args, **kwargs) -> Any: ...
    def property_unset(*args, **kwargs) -> Any: ...
    def remove(draw_func) -> Any: ...
    def rna_ancestors(*args, **kwargs) -> Any: ...
    def type_recast(*args, **kwargs) -> Any: ...
    def values(*args, **kwargs) -> Any: ...

class PARTICLE_MT_context_menu:
    def __init__(self, /, *args, **kwargs) -> Any: ...
    def append(draw_func) -> Any: ...
    def as_pointer(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass_py(*args, **kwargs) -> Any: ...
    def draw(self, context) -> Any: ...
    def draw_collapsible(context, layout) -> Any: ...
    def draw_preset(self, _context) -> Any: ...
    def driver_add(*args, **kwargs) -> Any: ...
    def driver_remove(*args, **kwargs) -> Any: ...
    def get(*args, **kwargs) -> Any: ...
    id_data: Any
    def id_properties_clear(*args, **kwargs) -> Any: ...
    def id_properties_ensure(*args, **kwargs) -> Any: ...
    def id_properties_ui(*args, **kwargs) -> Any: ...
    def is_extended() -> Any: ...
    def is_property_hidden(*args, **kwargs) -> Any: ...
    def is_property_overridable_library(*args, **kwargs) -> Any: ...
    def is_property_readonly(*args, **kwargs) -> Any: ...
    def is_property_set(*args, **kwargs) -> Any: ...
    def items(*args, **kwargs) -> Any: ...
    def keyframe_delete(*args, **kwargs) -> Any: ...
    def keyframe_insert(*args, **kwargs) -> Any: ...
    def keys(*args, **kwargs) -> Any: ...
    def path_from_id(*args, **kwargs) -> Any: ...
    def path_from_module(*args, **kwargs) -> Any: ...
    def path_menu(self, searchpaths, operator, *, props_default=None, prop_filepath='filepath', filter_ext=None, filter_path=None, display_name=None, add_operator=None, add_operator_props=None, translate=True) -> Any: ...
    def path_resolve(*args, **kwargs) -> Any: ...
    def pop(*args, **kwargs) -> Any: ...
    def prepend(draw_func) -> Any: ...
    def property_overridable_library_set(*args, **kwargs) -> Any: ...
    def property_unset(*args, **kwargs) -> Any: ...
    def remove(draw_func) -> Any: ...
    def rna_ancestors(*args, **kwargs) -> Any: ...
    def type_recast(*args, **kwargs) -> Any: ...
    def values(*args, **kwargs) -> Any: ...

class PARTICLE_PT_animation:
    def __init__(self, /, *args, **kwargs) -> Any: ...
    def append(draw_func) -> Any: ...
    def as_pointer(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass_py(*args, **kwargs) -> Any: ...
    def draw(self, context) -> Any: ...
    def draw_action_and_slot_selector(context, layout, animated_id) -> Any: ...
    def driver_add(*args, **kwargs) -> Any: ...
    def driver_remove(*args, **kwargs) -> Any: ...
    def get(*args, **kwargs) -> Any: ...
    id_data: Any
    def id_properties_clear(*args, **kwargs) -> Any: ...
    def id_properties_ensure(*args, **kwargs) -> Any: ...
    def id_properties_ui(*args, **kwargs) -> Any: ...
    def is_extended() -> Any: ...
    def is_property_hidden(*args, **kwargs) -> Any: ...
    def is_property_overridable_library(*args, **kwargs) -> Any: ...
    def is_property_readonly(*args, **kwargs) -> Any: ...
    def is_property_set(*args, **kwargs) -> Any: ...
    def items(*args, **kwargs) -> Any: ...
    def keyframe_delete(*args, **kwargs) -> Any: ...
    def keyframe_insert(*args, **kwargs) -> Any: ...
    def keys(*args, **kwargs) -> Any: ...
    def path_from_id(*args, **kwargs) -> Any: ...
    def path_from_module(*args, **kwargs) -> Any: ...
    def path_resolve(*args, **kwargs) -> Any: ...
    def poll(context) -> Any: ...
    def pop(*args, **kwargs) -> Any: ...
    def prepend(draw_func) -> Any: ...
    def property_overridable_library_set(*args, **kwargs) -> Any: ...
    def property_unset(*args, **kwargs) -> Any: ...
    def remove(draw_func) -> Any: ...
    def rna_ancestors(*args, **kwargs) -> Any: ...
    def type_recast(*args, **kwargs) -> Any: ...
    def values(*args, **kwargs) -> Any: ...

class PARTICLE_PT_boidbrain:
    def __init__(self, /, *args, **kwargs) -> Any: ...
    def append(draw_func) -> Any: ...
    def as_pointer(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass_py(*args, **kwargs) -> Any: ...
    def draw(self, context) -> Any: ...
    def driver_add(*args, **kwargs) -> Any: ...
    def driver_remove(*args, **kwargs) -> Any: ...
    def get(*args, **kwargs) -> Any: ...
    id_data: Any
    def id_properties_clear(*args, **kwargs) -> Any: ...
    def id_properties_ensure(*args, **kwargs) -> Any: ...
    def id_properties_ui(*args, **kwargs) -> Any: ...
    def is_extended() -> Any: ...
    def is_property_hidden(*args, **kwargs) -> Any: ...
    def is_property_overridable_library(*args, **kwargs) -> Any: ...
    def is_property_readonly(*args, **kwargs) -> Any: ...
    def is_property_set(*args, **kwargs) -> Any: ...
    def items(*args, **kwargs) -> Any: ...
    def keyframe_delete(*args, **kwargs) -> Any: ...
    def keyframe_insert(*args, **kwargs) -> Any: ...
    def keys(*args, **kwargs) -> Any: ...
    def path_from_id(*args, **kwargs) -> Any: ...
    def path_from_module(*args, **kwargs) -> Any: ...
    def path_resolve(*args, **kwargs) -> Any: ...
    def poll(context) -> Any: ...
    def pop(*args, **kwargs) -> Any: ...
    def prepend(draw_func) -> Any: ...
    def property_overridable_library_set(*args, **kwargs) -> Any: ...
    def property_unset(*args, **kwargs) -> Any: ...
    def remove(draw_func) -> Any: ...
    def rna_ancestors(*args, **kwargs) -> Any: ...
    def type_recast(*args, **kwargs) -> Any: ...
    def values(*args, **kwargs) -> Any: ...

class PARTICLE_PT_cache:
    def __init__(self, /, *args, **kwargs) -> Any: ...
    def append(draw_func) -> Any: ...
    def as_pointer(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass_py(*args, **kwargs) -> Any: ...
    def draw(self, context) -> Any: ...
    def driver_add(*args, **kwargs) -> Any: ...
    def driver_remove(*args, **kwargs) -> Any: ...
    def get(*args, **kwargs) -> Any: ...
    id_data: Any
    def id_properties_clear(*args, **kwargs) -> Any: ...
    def id_properties_ensure(*args, **kwargs) -> Any: ...
    def id_properties_ui(*args, **kwargs) -> Any: ...
    def is_extended() -> Any: ...
    def is_property_hidden(*args, **kwargs) -> Any: ...
    def is_property_overridable_library(*args, **kwargs) -> Any: ...
    def is_property_readonly(*args, **kwargs) -> Any: ...
    def is_property_set(*args, **kwargs) -> Any: ...
    def items(*args, **kwargs) -> Any: ...
    def keyframe_delete(*args, **kwargs) -> Any: ...
    def keyframe_insert(*args, **kwargs) -> Any: ...
    def keys(*args, **kwargs) -> Any: ...
    def path_from_id(*args, **kwargs) -> Any: ...
    def path_from_module(*args, **kwargs) -> Any: ...
    def path_resolve(*args, **kwargs) -> Any: ...
    def poll(context) -> Any: ...
    def pop(*args, **kwargs) -> Any: ...
    def prepend(draw_func) -> Any: ...
    def property_overridable_library_set(*args, **kwargs) -> Any: ...
    def property_unset(*args, **kwargs) -> Any: ...
    def remove(draw_func) -> Any: ...
    def rna_ancestors(*args, **kwargs) -> Any: ...
    def type_recast(*args, **kwargs) -> Any: ...
    def values(*args, **kwargs) -> Any: ...

class PARTICLE_PT_children:
    def __init__(self, /, *args, **kwargs) -> Any: ...
    def append(draw_func) -> Any: ...
    def as_pointer(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass_py(*args, **kwargs) -> Any: ...
    def draw(self, context) -> Any: ...
    def driver_add(*args, **kwargs) -> Any: ...
    def driver_remove(*args, **kwargs) -> Any: ...
    def get(*args, **kwargs) -> Any: ...
    id_data: Any
    def id_properties_clear(*args, **kwargs) -> Any: ...
    def id_properties_ensure(*args, **kwargs) -> Any: ...
    def id_properties_ui(*args, **kwargs) -> Any: ...
    def is_extended() -> Any: ...
    def is_property_hidden(*args, **kwargs) -> Any: ...
    def is_property_overridable_library(*args, **kwargs) -> Any: ...
    def is_property_readonly(*args, **kwargs) -> Any: ...
    def is_property_set(*args, **kwargs) -> Any: ...
    def items(*args, **kwargs) -> Any: ...
    def keyframe_delete(*args, **kwargs) -> Any: ...
    def keyframe_insert(*args, **kwargs) -> Any: ...
    def keys(*args, **kwargs) -> Any: ...
    def path_from_id(*args, **kwargs) -> Any: ...
    def path_from_module(*args, **kwargs) -> Any: ...
    def path_resolve(*args, **kwargs) -> Any: ...
    def poll(context) -> Any: ...
    def pop(*args, **kwargs) -> Any: ...
    def prepend(draw_func) -> Any: ...
    def property_overridable_library_set(*args, **kwargs) -> Any: ...
    def property_unset(*args, **kwargs) -> Any: ...
    def remove(draw_func) -> Any: ...
    def rna_ancestors(*args, **kwargs) -> Any: ...
    def type_recast(*args, **kwargs) -> Any: ...
    def values(*args, **kwargs) -> Any: ...

class PARTICLE_PT_children_clumping:
    def __init__(self, /, *args, **kwargs) -> Any: ...
    def append(draw_func) -> Any: ...
    def as_pointer(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass_py(*args, **kwargs) -> Any: ...
    def draw(self, context) -> Any: ...
    def driver_add(*args, **kwargs) -> Any: ...
    def driver_remove(*args, **kwargs) -> Any: ...
    def get(*args, **kwargs) -> Any: ...
    id_data: Any
    def id_properties_clear(*args, **kwargs) -> Any: ...
    def id_properties_ensure(*args, **kwargs) -> Any: ...
    def id_properties_ui(*args, **kwargs) -> Any: ...
    def is_extended() -> Any: ...
    def is_property_hidden(*args, **kwargs) -> Any: ...
    def is_property_overridable_library(*args, **kwargs) -> Any: ...
    def is_property_readonly(*args, **kwargs) -> Any: ...
    def is_property_set(*args, **kwargs) -> Any: ...
    def items(*args, **kwargs) -> Any: ...
    def keyframe_delete(*args, **kwargs) -> Any: ...
    def keyframe_insert(*args, **kwargs) -> Any: ...
    def keys(*args, **kwargs) -> Any: ...
    def path_from_id(*args, **kwargs) -> Any: ...
    def path_from_module(*args, **kwargs) -> Any: ...
    def path_resolve(*args, **kwargs) -> Any: ...
    def poll(context) -> Any: ...
    def pop(*args, **kwargs) -> Any: ...
    def prepend(draw_func) -> Any: ...
    def property_overridable_library_set(*args, **kwargs) -> Any: ...
    def property_unset(*args, **kwargs) -> Any: ...
    def remove(draw_func) -> Any: ...
    def rna_ancestors(*args, **kwargs) -> Any: ...
    def type_recast(*args, **kwargs) -> Any: ...
    def values(*args, **kwargs) -> Any: ...

class PARTICLE_PT_children_clumping_noise:
    def __init__(self, /, *args, **kwargs) -> Any: ...
    def append(draw_func) -> Any: ...
    def as_pointer(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass_py(*args, **kwargs) -> Any: ...
    def draw(self, context) -> Any: ...
    def draw_header(self, context) -> Any: ...
    def driver_add(*args, **kwargs) -> Any: ...
    def driver_remove(*args, **kwargs) -> Any: ...
    def get(*args, **kwargs) -> Any: ...
    id_data: Any
    def id_properties_clear(*args, **kwargs) -> Any: ...
    def id_properties_ensure(*args, **kwargs) -> Any: ...
    def id_properties_ui(*args, **kwargs) -> Any: ...
    def is_extended() -> Any: ...
    def is_property_hidden(*args, **kwargs) -> Any: ...
    def is_property_overridable_library(*args, **kwargs) -> Any: ...
    def is_property_readonly(*args, **kwargs) -> Any: ...
    def is_property_set(*args, **kwargs) -> Any: ...
    def items(*args, **kwargs) -> Any: ...
    def keyframe_delete(*args, **kwargs) -> Any: ...
    def keyframe_insert(*args, **kwargs) -> Any: ...
    def keys(*args, **kwargs) -> Any: ...
    def path_from_id(*args, **kwargs) -> Any: ...
    def path_from_module(*args, **kwargs) -> Any: ...
    def path_resolve(*args, **kwargs) -> Any: ...
    def poll(context) -> Any: ...
    def pop(*args, **kwargs) -> Any: ...
    def prepend(draw_func) -> Any: ...
    def property_overridable_library_set(*args, **kwargs) -> Any: ...
    def property_unset(*args, **kwargs) -> Any: ...
    def remove(draw_func) -> Any: ...
    def rna_ancestors(*args, **kwargs) -> Any: ...
    def type_recast(*args, **kwargs) -> Any: ...
    def values(*args, **kwargs) -> Any: ...

class PARTICLE_PT_children_kink:
    def __init__(self, /, *args, **kwargs) -> Any: ...
    def append(draw_func) -> Any: ...
    def as_pointer(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass_py(*args, **kwargs) -> Any: ...
    def draw(self, context) -> Any: ...
    def driver_add(*args, **kwargs) -> Any: ...
    def driver_remove(*args, **kwargs) -> Any: ...
    def get(*args, **kwargs) -> Any: ...
    id_data: Any
    def id_properties_clear(*args, **kwargs) -> Any: ...
    def id_properties_ensure(*args, **kwargs) -> Any: ...
    def id_properties_ui(*args, **kwargs) -> Any: ...
    def is_extended() -> Any: ...
    def is_property_hidden(*args, **kwargs) -> Any: ...
    def is_property_overridable_library(*args, **kwargs) -> Any: ...
    def is_property_readonly(*args, **kwargs) -> Any: ...
    def is_property_set(*args, **kwargs) -> Any: ...
    def items(*args, **kwargs) -> Any: ...
    def keyframe_delete(*args, **kwargs) -> Any: ...
    def keyframe_insert(*args, **kwargs) -> Any: ...
    def keys(*args, **kwargs) -> Any: ...
    def path_from_id(*args, **kwargs) -> Any: ...
    def path_from_module(*args, **kwargs) -> Any: ...
    def path_resolve(*args, **kwargs) -> Any: ...
    def poll(context) -> Any: ...
    def pop(*args, **kwargs) -> Any: ...
    def prepend(draw_func) -> Any: ...
    def property_overridable_library_set(*args, **kwargs) -> Any: ...
    def property_unset(*args, **kwargs) -> Any: ...
    def remove(draw_func) -> Any: ...
    def rna_ancestors(*args, **kwargs) -> Any: ...
    def type_recast(*args, **kwargs) -> Any: ...
    def values(*args, **kwargs) -> Any: ...

class PARTICLE_PT_children_parting:
    def __init__(self, /, *args, **kwargs) -> Any: ...
    def append(draw_func) -> Any: ...
    def as_pointer(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass_py(*args, **kwargs) -> Any: ...
    def draw(self, context) -> Any: ...
    def driver_add(*args, **kwargs) -> Any: ...
    def driver_remove(*args, **kwargs) -> Any: ...
    def get(*args, **kwargs) -> Any: ...
    id_data: Any
    def id_properties_clear(*args, **kwargs) -> Any: ...
    def id_properties_ensure(*args, **kwargs) -> Any: ...
    def id_properties_ui(*args, **kwargs) -> Any: ...
    def is_extended() -> Any: ...
    def is_property_hidden(*args, **kwargs) -> Any: ...
    def is_property_overridable_library(*args, **kwargs) -> Any: ...
    def is_property_readonly(*args, **kwargs) -> Any: ...
    def is_property_set(*args, **kwargs) -> Any: ...
    def items(*args, **kwargs) -> Any: ...
    def keyframe_delete(*args, **kwargs) -> Any: ...
    def keyframe_insert(*args, **kwargs) -> Any: ...
    def keys(*args, **kwargs) -> Any: ...
    def path_from_id(*args, **kwargs) -> Any: ...
    def path_from_module(*args, **kwargs) -> Any: ...
    def path_resolve(*args, **kwargs) -> Any: ...
    def poll(context) -> Any: ...
    def pop(*args, **kwargs) -> Any: ...
    def prepend(draw_func) -> Any: ...
    def property_overridable_library_set(*args, **kwargs) -> Any: ...
    def property_unset(*args, **kwargs) -> Any: ...
    def remove(draw_func) -> Any: ...
    def rna_ancestors(*args, **kwargs) -> Any: ...
    def type_recast(*args, **kwargs) -> Any: ...
    def values(*args, **kwargs) -> Any: ...

class PARTICLE_PT_children_roughness:
    def __init__(self, /, *args, **kwargs) -> Any: ...
    def append(draw_func) -> Any: ...
    def as_pointer(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass_py(*args, **kwargs) -> Any: ...
    def draw(self, context) -> Any: ...
    def driver_add(*args, **kwargs) -> Any: ...
    def driver_remove(*args, **kwargs) -> Any: ...
    def get(*args, **kwargs) -> Any: ...
    id_data: Any
    def id_properties_clear(*args, **kwargs) -> Any: ...
    def id_properties_ensure(*args, **kwargs) -> Any: ...
    def id_properties_ui(*args, **kwargs) -> Any: ...
    def is_extended() -> Any: ...
    def is_property_hidden(*args, **kwargs) -> Any: ...
    def is_property_overridable_library(*args, **kwargs) -> Any: ...
    def is_property_readonly(*args, **kwargs) -> Any: ...
    def is_property_set(*args, **kwargs) -> Any: ...
    def items(*args, **kwargs) -> Any: ...
    def keyframe_delete(*args, **kwargs) -> Any: ...
    def keyframe_insert(*args, **kwargs) -> Any: ...
    def keys(*args, **kwargs) -> Any: ...
    def path_from_id(*args, **kwargs) -> Any: ...
    def path_from_module(*args, **kwargs) -> Any: ...
    def path_resolve(*args, **kwargs) -> Any: ...
    def poll(context) -> Any: ...
    def pop(*args, **kwargs) -> Any: ...
    def prepend(draw_func) -> Any: ...
    def property_overridable_library_set(*args, **kwargs) -> Any: ...
    def property_unset(*args, **kwargs) -> Any: ...
    def remove(draw_func) -> Any: ...
    def rna_ancestors(*args, **kwargs) -> Any: ...
    def type_recast(*args, **kwargs) -> Any: ...
    def values(*args, **kwargs) -> Any: ...

class PARTICLE_PT_context_particles:
    def __init__(self, /, *args, **kwargs) -> Any: ...
    def append(draw_func) -> Any: ...
    def as_pointer(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass_py(*args, **kwargs) -> Any: ...
    def draw(self, context) -> Any: ...
    def driver_add(*args, **kwargs) -> Any: ...
    def driver_remove(*args, **kwargs) -> Any: ...
    def get(*args, **kwargs) -> Any: ...
    id_data: Any
    def id_properties_clear(*args, **kwargs) -> Any: ...
    def id_properties_ensure(*args, **kwargs) -> Any: ...
    def id_properties_ui(*args, **kwargs) -> Any: ...
    def is_extended() -> Any: ...
    def is_property_hidden(*args, **kwargs) -> Any: ...
    def is_property_overridable_library(*args, **kwargs) -> Any: ...
    def is_property_readonly(*args, **kwargs) -> Any: ...
    def is_property_set(*args, **kwargs) -> Any: ...
    def items(*args, **kwargs) -> Any: ...
    def keyframe_delete(*args, **kwargs) -> Any: ...
    def keyframe_insert(*args, **kwargs) -> Any: ...
    def keys(*args, **kwargs) -> Any: ...
    def path_from_id(*args, **kwargs) -> Any: ...
    def path_from_module(*args, **kwargs) -> Any: ...
    def path_resolve(*args, **kwargs) -> Any: ...
    def poll(context) -> Any: ...
    def pop(*args, **kwargs) -> Any: ...
    def prepend(draw_func) -> Any: ...
    def property_overridable_library_set(*args, **kwargs) -> Any: ...
    def property_unset(*args, **kwargs) -> Any: ...
    def remove(draw_func) -> Any: ...
    def rna_ancestors(*args, **kwargs) -> Any: ...
    def type_recast(*args, **kwargs) -> Any: ...
    def values(*args, **kwargs) -> Any: ...

class PARTICLE_PT_custom_props:
    def __init__(self, /, *args, **kwargs) -> Any: ...
    def append(draw_func) -> Any: ...
    def as_pointer(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass_py(*args, **kwargs) -> Any: ...
    def draw(self, context) -> Any: ...
    def driver_add(*args, **kwargs) -> Any: ...
    def driver_remove(*args, **kwargs) -> Any: ...
    def get(*args, **kwargs) -> Any: ...
    id_data: Any
    def id_properties_clear(*args, **kwargs) -> Any: ...
    def id_properties_ensure(*args, **kwargs) -> Any: ...
    def id_properties_ui(*args, **kwargs) -> Any: ...
    def is_extended() -> Any: ...
    def is_property_hidden(*args, **kwargs) -> Any: ...
    def is_property_overridable_library(*args, **kwargs) -> Any: ...
    def is_property_readonly(*args, **kwargs) -> Any: ...
    def is_property_set(*args, **kwargs) -> Any: ...
    def items(*args, **kwargs) -> Any: ...
    def keyframe_delete(*args, **kwargs) -> Any: ...
    def keyframe_insert(*args, **kwargs) -> Any: ...
    def keys(*args, **kwargs) -> Any: ...
    def path_from_id(*args, **kwargs) -> Any: ...
    def path_from_module(*args, **kwargs) -> Any: ...
    def path_resolve(*args, **kwargs) -> Any: ...
    def poll(context) -> Any: ...
    def pop(*args, **kwargs) -> Any: ...
    def prepend(draw_func) -> Any: ...
    def property_overridable_library_set(*args, **kwargs) -> Any: ...
    def property_unset(*args, **kwargs) -> Any: ...
    def remove(draw_func) -> Any: ...
    def rna_ancestors(*args, **kwargs) -> Any: ...
    def type_recast(*args, **kwargs) -> Any: ...
    def values(*args, **kwargs) -> Any: ...

class PARTICLE_PT_draw:
    def __init__(self, /, *args, **kwargs) -> Any: ...
    def append(draw_func) -> Any: ...
    def as_pointer(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass_py(*args, **kwargs) -> Any: ...
    def draw(self, context) -> Any: ...
    def driver_add(*args, **kwargs) -> Any: ...
    def driver_remove(*args, **kwargs) -> Any: ...
    def get(*args, **kwargs) -> Any: ...
    id_data: Any
    def id_properties_clear(*args, **kwargs) -> Any: ...
    def id_properties_ensure(*args, **kwargs) -> Any: ...
    def id_properties_ui(*args, **kwargs) -> Any: ...
    def is_extended() -> Any: ...
    def is_property_hidden(*args, **kwargs) -> Any: ...
    def is_property_overridable_library(*args, **kwargs) -> Any: ...
    def is_property_readonly(*args, **kwargs) -> Any: ...
    def is_property_set(*args, **kwargs) -> Any: ...
    def items(*args, **kwargs) -> Any: ...
    def keyframe_delete(*args, **kwargs) -> Any: ...
    def keyframe_insert(*args, **kwargs) -> Any: ...
    def keys(*args, **kwargs) -> Any: ...
    def path_from_id(*args, **kwargs) -> Any: ...
    def path_from_module(*args, **kwargs) -> Any: ...
    def path_resolve(*args, **kwargs) -> Any: ...
    def poll(context) -> Any: ...
    def pop(*args, **kwargs) -> Any: ...
    def prepend(draw_func) -> Any: ...
    def property_overridable_library_set(*args, **kwargs) -> Any: ...
    def property_unset(*args, **kwargs) -> Any: ...
    def remove(draw_func) -> Any: ...
    def rna_ancestors(*args, **kwargs) -> Any: ...
    def type_recast(*args, **kwargs) -> Any: ...
    def values(*args, **kwargs) -> Any: ...

class PARTICLE_PT_emission:
    def __init__(self, /, *args, **kwargs) -> Any: ...
    def append(draw_func) -> Any: ...
    def as_pointer(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass_py(*args, **kwargs) -> Any: ...
    def draw(self, context) -> Any: ...
    def driver_add(*args, **kwargs) -> Any: ...
    def driver_remove(*args, **kwargs) -> Any: ...
    def get(*args, **kwargs) -> Any: ...
    id_data: Any
    def id_properties_clear(*args, **kwargs) -> Any: ...
    def id_properties_ensure(*args, **kwargs) -> Any: ...
    def id_properties_ui(*args, **kwargs) -> Any: ...
    def is_extended() -> Any: ...
    def is_property_hidden(*args, **kwargs) -> Any: ...
    def is_property_overridable_library(*args, **kwargs) -> Any: ...
    def is_property_readonly(*args, **kwargs) -> Any: ...
    def is_property_set(*args, **kwargs) -> Any: ...
    def items(*args, **kwargs) -> Any: ...
    def keyframe_delete(*args, **kwargs) -> Any: ...
    def keyframe_insert(*args, **kwargs) -> Any: ...
    def keys(*args, **kwargs) -> Any: ...
    def path_from_id(*args, **kwargs) -> Any: ...
    def path_from_module(*args, **kwargs) -> Any: ...
    def path_resolve(*args, **kwargs) -> Any: ...
    def poll(context) -> Any: ...
    def pop(*args, **kwargs) -> Any: ...
    def prepend(draw_func) -> Any: ...
    def property_overridable_library_set(*args, **kwargs) -> Any: ...
    def property_unset(*args, **kwargs) -> Any: ...
    def remove(draw_func) -> Any: ...
    def rna_ancestors(*args, **kwargs) -> Any: ...
    def type_recast(*args, **kwargs) -> Any: ...
    def values(*args, **kwargs) -> Any: ...

class PARTICLE_PT_emission_source:
    def __init__(self, /, *args, **kwargs) -> Any: ...
    def append(draw_func) -> Any: ...
    def as_pointer(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass_py(*args, **kwargs) -> Any: ...
    def draw(self, context) -> Any: ...
    def driver_add(*args, **kwargs) -> Any: ...
    def driver_remove(*args, **kwargs) -> Any: ...
    def get(*args, **kwargs) -> Any: ...
    id_data: Any
    def id_properties_clear(*args, **kwargs) -> Any: ...
    def id_properties_ensure(*args, **kwargs) -> Any: ...
    def id_properties_ui(*args, **kwargs) -> Any: ...
    def is_extended() -> Any: ...
    def is_property_hidden(*args, **kwargs) -> Any: ...
    def is_property_overridable_library(*args, **kwargs) -> Any: ...
    def is_property_readonly(*args, **kwargs) -> Any: ...
    def is_property_set(*args, **kwargs) -> Any: ...
    def items(*args, **kwargs) -> Any: ...
    def keyframe_delete(*args, **kwargs) -> Any: ...
    def keyframe_insert(*args, **kwargs) -> Any: ...
    def keys(*args, **kwargs) -> Any: ...
    def path_from_id(*args, **kwargs) -> Any: ...
    def path_from_module(*args, **kwargs) -> Any: ...
    def path_resolve(*args, **kwargs) -> Any: ...
    def poll(context) -> Any: ...
    def pop(*args, **kwargs) -> Any: ...
    def prepend(draw_func) -> Any: ...
    def property_overridable_library_set(*args, **kwargs) -> Any: ...
    def property_unset(*args, **kwargs) -> Any: ...
    def remove(draw_func) -> Any: ...
    def rna_ancestors(*args, **kwargs) -> Any: ...
    def type_recast(*args, **kwargs) -> Any: ...
    def values(*args, **kwargs) -> Any: ...

class PARTICLE_PT_field_weights:
    def __init__(self, /, *args, **kwargs) -> Any: ...
    def append(draw_func) -> Any: ...
    def as_pointer(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass_py(*args, **kwargs) -> Any: ...
    def draw(self, context) -> Any: ...
    def driver_add(*args, **kwargs) -> Any: ...
    def driver_remove(*args, **kwargs) -> Any: ...
    def get(*args, **kwargs) -> Any: ...
    id_data: Any
    def id_properties_clear(*args, **kwargs) -> Any: ...
    def id_properties_ensure(*args, **kwargs) -> Any: ...
    def id_properties_ui(*args, **kwargs) -> Any: ...
    def is_extended() -> Any: ...
    def is_property_hidden(*args, **kwargs) -> Any: ...
    def is_property_overridable_library(*args, **kwargs) -> Any: ...
    def is_property_readonly(*args, **kwargs) -> Any: ...
    def is_property_set(*args, **kwargs) -> Any: ...
    def items(*args, **kwargs) -> Any: ...
    def keyframe_delete(*args, **kwargs) -> Any: ...
    def keyframe_insert(*args, **kwargs) -> Any: ...
    def keys(*args, **kwargs) -> Any: ...
    def path_from_id(*args, **kwargs) -> Any: ...
    def path_from_module(*args, **kwargs) -> Any: ...
    def path_resolve(*args, **kwargs) -> Any: ...
    def poll(context) -> Any: ...
    def pop(*args, **kwargs) -> Any: ...
    def prepend(draw_func) -> Any: ...
    def property_overridable_library_set(*args, **kwargs) -> Any: ...
    def property_unset(*args, **kwargs) -> Any: ...
    def remove(draw_func) -> Any: ...
    def rna_ancestors(*args, **kwargs) -> Any: ...
    def type_recast(*args, **kwargs) -> Any: ...
    def values(*args, **kwargs) -> Any: ...

class PARTICLE_PT_force_fields:
    def __init__(self, /, *args, **kwargs) -> Any: ...
    def append(draw_func) -> Any: ...
    def as_pointer(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass_py(*args, **kwargs) -> Any: ...
    def draw(self, context) -> Any: ...
    def driver_add(*args, **kwargs) -> Any: ...
    def driver_remove(*args, **kwargs) -> Any: ...
    def get(*args, **kwargs) -> Any: ...
    id_data: Any
    def id_properties_clear(*args, **kwargs) -> Any: ...
    def id_properties_ensure(*args, **kwargs) -> Any: ...
    def id_properties_ui(*args, **kwargs) -> Any: ...
    def is_extended() -> Any: ...
    def is_property_hidden(*args, **kwargs) -> Any: ...
    def is_property_overridable_library(*args, **kwargs) -> Any: ...
    def is_property_readonly(*args, **kwargs) -> Any: ...
    def is_property_set(*args, **kwargs) -> Any: ...
    def items(*args, **kwargs) -> Any: ...
    def keyframe_delete(*args, **kwargs) -> Any: ...
    def keyframe_insert(*args, **kwargs) -> Any: ...
    def keys(*args, **kwargs) -> Any: ...
    def path_from_id(*args, **kwargs) -> Any: ...
    def path_from_module(*args, **kwargs) -> Any: ...
    def path_resolve(*args, **kwargs) -> Any: ...
    def poll(context) -> Any: ...
    def pop(*args, **kwargs) -> Any: ...
    def prepend(draw_func) -> Any: ...
    def property_overridable_library_set(*args, **kwargs) -> Any: ...
    def property_unset(*args, **kwargs) -> Any: ...
    def remove(draw_func) -> Any: ...
    def rna_ancestors(*args, **kwargs) -> Any: ...
    def type_recast(*args, **kwargs) -> Any: ...
    def values(*args, **kwargs) -> Any: ...

class PARTICLE_PT_force_fields_type1:
    def __init__(self, /, *args, **kwargs) -> Any: ...
    def append(draw_func) -> Any: ...
    def as_pointer(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass_py(*args, **kwargs) -> Any: ...
    def draw(self, context) -> Any: ...
    def driver_add(*args, **kwargs) -> Any: ...
    def driver_remove(*args, **kwargs) -> Any: ...
    def get(*args, **kwargs) -> Any: ...
    id_data: Any
    def id_properties_clear(*args, **kwargs) -> Any: ...
    def id_properties_ensure(*args, **kwargs) -> Any: ...
    def id_properties_ui(*args, **kwargs) -> Any: ...
    def is_extended() -> Any: ...
    def is_property_hidden(*args, **kwargs) -> Any: ...
    def is_property_overridable_library(*args, **kwargs) -> Any: ...
    def is_property_readonly(*args, **kwargs) -> Any: ...
    def is_property_set(*args, **kwargs) -> Any: ...
    def items(*args, **kwargs) -> Any: ...
    def keyframe_delete(*args, **kwargs) -> Any: ...
    def keyframe_insert(*args, **kwargs) -> Any: ...
    def keys(*args, **kwargs) -> Any: ...
    def path_from_id(*args, **kwargs) -> Any: ...
    def path_from_module(*args, **kwargs) -> Any: ...
    def path_resolve(*args, **kwargs) -> Any: ...
    def poll(context) -> Any: ...
    def pop(*args, **kwargs) -> Any: ...
    def prepend(draw_func) -> Any: ...
    def property_overridable_library_set(*args, **kwargs) -> Any: ...
    def property_unset(*args, **kwargs) -> Any: ...
    def remove(draw_func) -> Any: ...
    def rna_ancestors(*args, **kwargs) -> Any: ...
    def type_recast(*args, **kwargs) -> Any: ...
    def values(*args, **kwargs) -> Any: ...

class PARTICLE_PT_force_fields_type1_falloff:
    def __init__(self, /, *args, **kwargs) -> Any: ...
    def append(draw_func) -> Any: ...
    def as_pointer(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass_py(*args, **kwargs) -> Any: ...
    def draw(self, context) -> Any: ...
    def driver_add(*args, **kwargs) -> Any: ...
    def driver_remove(*args, **kwargs) -> Any: ...
    def get(*args, **kwargs) -> Any: ...
    id_data: Any
    def id_properties_clear(*args, **kwargs) -> Any: ...
    def id_properties_ensure(*args, **kwargs) -> Any: ...
    def id_properties_ui(*args, **kwargs) -> Any: ...
    def is_extended() -> Any: ...
    def is_property_hidden(*args, **kwargs) -> Any: ...
    def is_property_overridable_library(*args, **kwargs) -> Any: ...
    def is_property_readonly(*args, **kwargs) -> Any: ...
    def is_property_set(*args, **kwargs) -> Any: ...
    def items(*args, **kwargs) -> Any: ...
    def keyframe_delete(*args, **kwargs) -> Any: ...
    def keyframe_insert(*args, **kwargs) -> Any: ...
    def keys(*args, **kwargs) -> Any: ...
    def path_from_id(*args, **kwargs) -> Any: ...
    def path_from_module(*args, **kwargs) -> Any: ...
    def path_resolve(*args, **kwargs) -> Any: ...
    def poll(context) -> Any: ...
    def pop(*args, **kwargs) -> Any: ...
    def prepend(draw_func) -> Any: ...
    def property_overridable_library_set(*args, **kwargs) -> Any: ...
    def property_unset(*args, **kwargs) -> Any: ...
    def remove(draw_func) -> Any: ...
    def rna_ancestors(*args, **kwargs) -> Any: ...
    def type_recast(*args, **kwargs) -> Any: ...
    def values(*args, **kwargs) -> Any: ...

class PARTICLE_PT_force_fields_type2:
    def __init__(self, /, *args, **kwargs) -> Any: ...
    def append(draw_func) -> Any: ...
    def as_pointer(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass_py(*args, **kwargs) -> Any: ...
    def draw(self, context) -> Any: ...
    def driver_add(*args, **kwargs) -> Any: ...
    def driver_remove(*args, **kwargs) -> Any: ...
    def get(*args, **kwargs) -> Any: ...
    id_data: Any
    def id_properties_clear(*args, **kwargs) -> Any: ...
    def id_properties_ensure(*args, **kwargs) -> Any: ...
    def id_properties_ui(*args, **kwargs) -> Any: ...
    def is_extended() -> Any: ...
    def is_property_hidden(*args, **kwargs) -> Any: ...
    def is_property_overridable_library(*args, **kwargs) -> Any: ...
    def is_property_readonly(*args, **kwargs) -> Any: ...
    def is_property_set(*args, **kwargs) -> Any: ...
    def items(*args, **kwargs) -> Any: ...
    def keyframe_delete(*args, **kwargs) -> Any: ...
    def keyframe_insert(*args, **kwargs) -> Any: ...
    def keys(*args, **kwargs) -> Any: ...
    def path_from_id(*args, **kwargs) -> Any: ...
    def path_from_module(*args, **kwargs) -> Any: ...
    def path_resolve(*args, **kwargs) -> Any: ...
    def poll(context) -> Any: ...
    def pop(*args, **kwargs) -> Any: ...
    def prepend(draw_func) -> Any: ...
    def property_overridable_library_set(*args, **kwargs) -> Any: ...
    def property_unset(*args, **kwargs) -> Any: ...
    def remove(draw_func) -> Any: ...
    def rna_ancestors(*args, **kwargs) -> Any: ...
    def type_recast(*args, **kwargs) -> Any: ...
    def values(*args, **kwargs) -> Any: ...

class PARTICLE_PT_force_fields_type2_falloff:
    def __init__(self, /, *args, **kwargs) -> Any: ...
    def append(draw_func) -> Any: ...
    def as_pointer(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass_py(*args, **kwargs) -> Any: ...
    def draw(self, context) -> Any: ...
    def driver_add(*args, **kwargs) -> Any: ...
    def driver_remove(*args, **kwargs) -> Any: ...
    def get(*args, **kwargs) -> Any: ...
    id_data: Any
    def id_properties_clear(*args, **kwargs) -> Any: ...
    def id_properties_ensure(*args, **kwargs) -> Any: ...
    def id_properties_ui(*args, **kwargs) -> Any: ...
    def is_extended() -> Any: ...
    def is_property_hidden(*args, **kwargs) -> Any: ...
    def is_property_overridable_library(*args, **kwargs) -> Any: ...
    def is_property_readonly(*args, **kwargs) -> Any: ...
    def is_property_set(*args, **kwargs) -> Any: ...
    def items(*args, **kwargs) -> Any: ...
    def keyframe_delete(*args, **kwargs) -> Any: ...
    def keyframe_insert(*args, **kwargs) -> Any: ...
    def keys(*args, **kwargs) -> Any: ...
    def path_from_id(*args, **kwargs) -> Any: ...
    def path_from_module(*args, **kwargs) -> Any: ...
    def path_resolve(*args, **kwargs) -> Any: ...
    def poll(context) -> Any: ...
    def pop(*args, **kwargs) -> Any: ...
    def prepend(draw_func) -> Any: ...
    def property_overridable_library_set(*args, **kwargs) -> Any: ...
    def property_unset(*args, **kwargs) -> Any: ...
    def remove(draw_func) -> Any: ...
    def rna_ancestors(*args, **kwargs) -> Any: ...
    def type_recast(*args, **kwargs) -> Any: ...
    def values(*args, **kwargs) -> Any: ...

class PARTICLE_PT_hair_dynamics:
    def __init__(self, /, *args, **kwargs) -> Any: ...
    def append(draw_func) -> Any: ...
    def as_pointer(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass_py(*args, **kwargs) -> Any: ...
    def draw(self, context) -> Any: ...
    def draw_header(self, context) -> Any: ...
    def draw_header_preset(self, context) -> Any: ...
    def driver_add(*args, **kwargs) -> Any: ...
    def driver_remove(*args, **kwargs) -> Any: ...
    def get(*args, **kwargs) -> Any: ...
    id_data: Any
    def id_properties_clear(*args, **kwargs) -> Any: ...
    def id_properties_ensure(*args, **kwargs) -> Any: ...
    def id_properties_ui(*args, **kwargs) -> Any: ...
    def is_extended() -> Any: ...
    def is_property_hidden(*args, **kwargs) -> Any: ...
    def is_property_overridable_library(*args, **kwargs) -> Any: ...
    def is_property_readonly(*args, **kwargs) -> Any: ...
    def is_property_set(*args, **kwargs) -> Any: ...
    def items(*args, **kwargs) -> Any: ...
    def keyframe_delete(*args, **kwargs) -> Any: ...
    def keyframe_insert(*args, **kwargs) -> Any: ...
    def keys(*args, **kwargs) -> Any: ...
    def path_from_id(*args, **kwargs) -> Any: ...
    def path_from_module(*args, **kwargs) -> Any: ...
    def path_resolve(*args, **kwargs) -> Any: ...
    def poll(context) -> Any: ...
    def pop(*args, **kwargs) -> Any: ...
    def prepend(draw_func) -> Any: ...
    def property_overridable_library_set(*args, **kwargs) -> Any: ...
    def property_unset(*args, **kwargs) -> Any: ...
    def remove(draw_func) -> Any: ...
    def rna_ancestors(*args, **kwargs) -> Any: ...
    def type_recast(*args, **kwargs) -> Any: ...
    def values(*args, **kwargs) -> Any: ...

class PARTICLE_PT_hair_dynamics_collision:
    def __init__(self, /, *args, **kwargs) -> Any: ...
    def append(draw_func) -> Any: ...
    def as_pointer(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass_py(*args, **kwargs) -> Any: ...
    def draw(self, context) -> Any: ...
    def driver_add(*args, **kwargs) -> Any: ...
    def driver_remove(*args, **kwargs) -> Any: ...
    def get(*args, **kwargs) -> Any: ...
    id_data: Any
    def id_properties_clear(*args, **kwargs) -> Any: ...
    def id_properties_ensure(*args, **kwargs) -> Any: ...
    def id_properties_ui(*args, **kwargs) -> Any: ...
    def is_extended() -> Any: ...
    def is_property_hidden(*args, **kwargs) -> Any: ...
    def is_property_overridable_library(*args, **kwargs) -> Any: ...
    def is_property_readonly(*args, **kwargs) -> Any: ...
    def is_property_set(*args, **kwargs) -> Any: ...
    def items(*args, **kwargs) -> Any: ...
    def keyframe_delete(*args, **kwargs) -> Any: ...
    def keyframe_insert(*args, **kwargs) -> Any: ...
    def keys(*args, **kwargs) -> Any: ...
    def path_from_id(*args, **kwargs) -> Any: ...
    def path_from_module(*args, **kwargs) -> Any: ...
    def path_resolve(*args, **kwargs) -> Any: ...
    def poll(context) -> Any: ...
    def pop(*args, **kwargs) -> Any: ...
    def prepend(draw_func) -> Any: ...
    def property_overridable_library_set(*args, **kwargs) -> Any: ...
    def property_unset(*args, **kwargs) -> Any: ...
    def remove(draw_func) -> Any: ...
    def rna_ancestors(*args, **kwargs) -> Any: ...
    def type_recast(*args, **kwargs) -> Any: ...
    def values(*args, **kwargs) -> Any: ...

class PARTICLE_PT_hair_dynamics_presets:
    def __init__(self, /, *args, **kwargs) -> Any: ...
    def append(draw_func) -> Any: ...
    def as_pointer(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass_py(*args, **kwargs) -> Any: ...
    def draw(self, context) -> Any: ...
    def draw_menu(layout, text=None) -> Any: ...
    def draw_panel_header(layout) -> Any: ...
    def driver_add(*args, **kwargs) -> Any: ...
    def driver_remove(*args, **kwargs) -> Any: ...
    def get(*args, **kwargs) -> Any: ...
    id_data: Any
    def id_properties_clear(*args, **kwargs) -> Any: ...
    def id_properties_ensure(*args, **kwargs) -> Any: ...
    def id_properties_ui(*args, **kwargs) -> Any: ...
    def is_extended() -> Any: ...
    def is_property_hidden(*args, **kwargs) -> Any: ...
    def is_property_overridable_library(*args, **kwargs) -> Any: ...
    def is_property_readonly(*args, **kwargs) -> Any: ...
    def is_property_set(*args, **kwargs) -> Any: ...
    def items(*args, **kwargs) -> Any: ...
    def keyframe_delete(*args, **kwargs) -> Any: ...
    def keyframe_insert(*args, **kwargs) -> Any: ...
    def keys(*args, **kwargs) -> Any: ...
    def path_from_id(*args, **kwargs) -> Any: ...
    def path_from_module(*args, **kwargs) -> Any: ...
    def path_menu(self, searchpaths, operator, *, props_default=None, prop_filepath='filepath', filter_ext=None, filter_path=None, display_name=None, add_operator=None, add_operator_props=None, translate=True) -> Any: ...
    def path_resolve(*args, **kwargs) -> Any: ...
    def pop(*args, **kwargs) -> Any: ...
    def prepend(draw_func) -> Any: ...
    def property_overridable_library_set(*args, **kwargs) -> Any: ...
    def property_unset(*args, **kwargs) -> Any: ...
    def remove(draw_func) -> Any: ...
    def rna_ancestors(*args, **kwargs) -> Any: ...
    def type_recast(*args, **kwargs) -> Any: ...
    def values(*args, **kwargs) -> Any: ...

class PARTICLE_PT_hair_dynamics_structure:
    def __init__(self, /, *args, **kwargs) -> Any: ...
    def append(draw_func) -> Any: ...
    def as_pointer(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass_py(*args, **kwargs) -> Any: ...
    def draw(self, context) -> Any: ...
    def driver_add(*args, **kwargs) -> Any: ...
    def driver_remove(*args, **kwargs) -> Any: ...
    def get(*args, **kwargs) -> Any: ...
    id_data: Any
    def id_properties_clear(*args, **kwargs) -> Any: ...
    def id_properties_ensure(*args, **kwargs) -> Any: ...
    def id_properties_ui(*args, **kwargs) -> Any: ...
    def is_extended() -> Any: ...
    def is_property_hidden(*args, **kwargs) -> Any: ...
    def is_property_overridable_library(*args, **kwargs) -> Any: ...
    def is_property_readonly(*args, **kwargs) -> Any: ...
    def is_property_set(*args, **kwargs) -> Any: ...
    def items(*args, **kwargs) -> Any: ...
    def keyframe_delete(*args, **kwargs) -> Any: ...
    def keyframe_insert(*args, **kwargs) -> Any: ...
    def keys(*args, **kwargs) -> Any: ...
    def path_from_id(*args, **kwargs) -> Any: ...
    def path_from_module(*args, **kwargs) -> Any: ...
    def path_resolve(*args, **kwargs) -> Any: ...
    def poll(context) -> Any: ...
    def pop(*args, **kwargs) -> Any: ...
    def prepend(draw_func) -> Any: ...
    def property_overridable_library_set(*args, **kwargs) -> Any: ...
    def property_unset(*args, **kwargs) -> Any: ...
    def remove(draw_func) -> Any: ...
    def rna_ancestors(*args, **kwargs) -> Any: ...
    def type_recast(*args, **kwargs) -> Any: ...
    def values(*args, **kwargs) -> Any: ...

class PARTICLE_PT_hair_dynamics_volume:
    def __init__(self, /, *args, **kwargs) -> Any: ...
    def append(draw_func) -> Any: ...
    def as_pointer(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass_py(*args, **kwargs) -> Any: ...
    def draw(self, context) -> Any: ...
    def driver_add(*args, **kwargs) -> Any: ...
    def driver_remove(*args, **kwargs) -> Any: ...
    def get(*args, **kwargs) -> Any: ...
    id_data: Any
    def id_properties_clear(*args, **kwargs) -> Any: ...
    def id_properties_ensure(*args, **kwargs) -> Any: ...
    def id_properties_ui(*args, **kwargs) -> Any: ...
    def is_extended() -> Any: ...
    def is_property_hidden(*args, **kwargs) -> Any: ...
    def is_property_overridable_library(*args, **kwargs) -> Any: ...
    def is_property_readonly(*args, **kwargs) -> Any: ...
    def is_property_set(*args, **kwargs) -> Any: ...
    def items(*args, **kwargs) -> Any: ...
    def keyframe_delete(*args, **kwargs) -> Any: ...
    def keyframe_insert(*args, **kwargs) -> Any: ...
    def keys(*args, **kwargs) -> Any: ...
    def path_from_id(*args, **kwargs) -> Any: ...
    def path_from_module(*args, **kwargs) -> Any: ...
    def path_resolve(*args, **kwargs) -> Any: ...
    def poll(context) -> Any: ...
    def pop(*args, **kwargs) -> Any: ...
    def prepend(draw_func) -> Any: ...
    def property_overridable_library_set(*args, **kwargs) -> Any: ...
    def property_unset(*args, **kwargs) -> Any: ...
    def remove(draw_func) -> Any: ...
    def rna_ancestors(*args, **kwargs) -> Any: ...
    def type_recast(*args, **kwargs) -> Any: ...
    def values(*args, **kwargs) -> Any: ...

class PARTICLE_PT_hair_shape:
    def __init__(self, /, *args, **kwargs) -> Any: ...
    def append(draw_func) -> Any: ...
    def as_pointer(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass_py(*args, **kwargs) -> Any: ...
    def draw(self, context) -> Any: ...
    def driver_add(*args, **kwargs) -> Any: ...
    def driver_remove(*args, **kwargs) -> Any: ...
    def get(*args, **kwargs) -> Any: ...
    id_data: Any
    def id_properties_clear(*args, **kwargs) -> Any: ...
    def id_properties_ensure(*args, **kwargs) -> Any: ...
    def id_properties_ui(*args, **kwargs) -> Any: ...
    def is_extended() -> Any: ...
    def is_property_hidden(*args, **kwargs) -> Any: ...
    def is_property_overridable_library(*args, **kwargs) -> Any: ...
    def is_property_readonly(*args, **kwargs) -> Any: ...
    def is_property_set(*args, **kwargs) -> Any: ...
    def items(*args, **kwargs) -> Any: ...
    def keyframe_delete(*args, **kwargs) -> Any: ...
    def keyframe_insert(*args, **kwargs) -> Any: ...
    def keys(*args, **kwargs) -> Any: ...
    def path_from_id(*args, **kwargs) -> Any: ...
    def path_from_module(*args, **kwargs) -> Any: ...
    def path_resolve(*args, **kwargs) -> Any: ...
    def poll(context) -> Any: ...
    def pop(*args, **kwargs) -> Any: ...
    def prepend(draw_func) -> Any: ...
    def property_overridable_library_set(*args, **kwargs) -> Any: ...
    def property_unset(*args, **kwargs) -> Any: ...
    def remove(draw_func) -> Any: ...
    def rna_ancestors(*args, **kwargs) -> Any: ...
    def type_recast(*args, **kwargs) -> Any: ...
    def values(*args, **kwargs) -> Any: ...

class PARTICLE_PT_physics:
    def __init__(self, /, *args, **kwargs) -> Any: ...
    def append(draw_func) -> Any: ...
    def as_pointer(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass_py(*args, **kwargs) -> Any: ...
    def draw(self, context) -> Any: ...
    def driver_add(*args, **kwargs) -> Any: ...
    def driver_remove(*args, **kwargs) -> Any: ...
    def get(*args, **kwargs) -> Any: ...
    id_data: Any
    def id_properties_clear(*args, **kwargs) -> Any: ...
    def id_properties_ensure(*args, **kwargs) -> Any: ...
    def id_properties_ui(*args, **kwargs) -> Any: ...
    def is_extended() -> Any: ...
    def is_property_hidden(*args, **kwargs) -> Any: ...
    def is_property_overridable_library(*args, **kwargs) -> Any: ...
    def is_property_readonly(*args, **kwargs) -> Any: ...
    def is_property_set(*args, **kwargs) -> Any: ...
    def items(*args, **kwargs) -> Any: ...
    def keyframe_delete(*args, **kwargs) -> Any: ...
    def keyframe_insert(*args, **kwargs) -> Any: ...
    def keys(*args, **kwargs) -> Any: ...
    def path_from_id(*args, **kwargs) -> Any: ...
    def path_from_module(*args, **kwargs) -> Any: ...
    def path_resolve(*args, **kwargs) -> Any: ...
    def poll(context) -> Any: ...
    def pop(*args, **kwargs) -> Any: ...
    def prepend(draw_func) -> Any: ...
    def property_overridable_library_set(*args, **kwargs) -> Any: ...
    def property_unset(*args, **kwargs) -> Any: ...
    def remove(draw_func) -> Any: ...
    def rna_ancestors(*args, **kwargs) -> Any: ...
    def type_recast(*args, **kwargs) -> Any: ...
    def values(*args, **kwargs) -> Any: ...

class PARTICLE_PT_physics_boids_battle:
    def __init__(self, /, *args, **kwargs) -> Any: ...
    def append(draw_func) -> Any: ...
    def as_pointer(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass_py(*args, **kwargs) -> Any: ...
    def draw(self, context) -> Any: ...
    def driver_add(*args, **kwargs) -> Any: ...
    def driver_remove(*args, **kwargs) -> Any: ...
    def get(*args, **kwargs) -> Any: ...
    id_data: Any
    def id_properties_clear(*args, **kwargs) -> Any: ...
    def id_properties_ensure(*args, **kwargs) -> Any: ...
    def id_properties_ui(*args, **kwargs) -> Any: ...
    def is_extended() -> Any: ...
    def is_property_hidden(*args, **kwargs) -> Any: ...
    def is_property_overridable_library(*args, **kwargs) -> Any: ...
    def is_property_readonly(*args, **kwargs) -> Any: ...
    def is_property_set(*args, **kwargs) -> Any: ...
    def items(*args, **kwargs) -> Any: ...
    def keyframe_delete(*args, **kwargs) -> Any: ...
    def keyframe_insert(*args, **kwargs) -> Any: ...
    def keys(*args, **kwargs) -> Any: ...
    def path_from_id(*args, **kwargs) -> Any: ...
    def path_from_module(*args, **kwargs) -> Any: ...
    def path_resolve(*args, **kwargs) -> Any: ...
    def poll(context) -> Any: ...
    def pop(*args, **kwargs) -> Any: ...
    def prepend(draw_func) -> Any: ...
    def property_overridable_library_set(*args, **kwargs) -> Any: ...
    def property_unset(*args, **kwargs) -> Any: ...
    def remove(draw_func) -> Any: ...
    def rna_ancestors(*args, **kwargs) -> Any: ...
    def type_recast(*args, **kwargs) -> Any: ...
    def values(*args, **kwargs) -> Any: ...

class PARTICLE_PT_physics_boids_misc:
    def __init__(self, /, *args, **kwargs) -> Any: ...
    def append(draw_func) -> Any: ...
    def as_pointer(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass_py(*args, **kwargs) -> Any: ...
    def draw(self, context) -> Any: ...
    def driver_add(*args, **kwargs) -> Any: ...
    def driver_remove(*args, **kwargs) -> Any: ...
    def get(*args, **kwargs) -> Any: ...
    id_data: Any
    def id_properties_clear(*args, **kwargs) -> Any: ...
    def id_properties_ensure(*args, **kwargs) -> Any: ...
    def id_properties_ui(*args, **kwargs) -> Any: ...
    def is_extended() -> Any: ...
    def is_property_hidden(*args, **kwargs) -> Any: ...
    def is_property_overridable_library(*args, **kwargs) -> Any: ...
    def is_property_readonly(*args, **kwargs) -> Any: ...
    def is_property_set(*args, **kwargs) -> Any: ...
    def items(*args, **kwargs) -> Any: ...
    def keyframe_delete(*args, **kwargs) -> Any: ...
    def keyframe_insert(*args, **kwargs) -> Any: ...
    def keys(*args, **kwargs) -> Any: ...
    def path_from_id(*args, **kwargs) -> Any: ...
    def path_from_module(*args, **kwargs) -> Any: ...
    def path_resolve(*args, **kwargs) -> Any: ...
    def poll(context) -> Any: ...
    def pop(*args, **kwargs) -> Any: ...
    def prepend(draw_func) -> Any: ...
    def property_overridable_library_set(*args, **kwargs) -> Any: ...
    def property_unset(*args, **kwargs) -> Any: ...
    def remove(draw_func) -> Any: ...
    def rna_ancestors(*args, **kwargs) -> Any: ...
    def type_recast(*args, **kwargs) -> Any: ...
    def values(*args, **kwargs) -> Any: ...

class PARTICLE_PT_physics_boids_movement:
    def __init__(self, /, *args, **kwargs) -> Any: ...
    def append(draw_func) -> Any: ...
    def as_pointer(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass_py(*args, **kwargs) -> Any: ...
    def draw(self, context) -> Any: ...
    def driver_add(*args, **kwargs) -> Any: ...
    def driver_remove(*args, **kwargs) -> Any: ...
    def get(*args, **kwargs) -> Any: ...
    id_data: Any
    def id_properties_clear(*args, **kwargs) -> Any: ...
    def id_properties_ensure(*args, **kwargs) -> Any: ...
    def id_properties_ui(*args, **kwargs) -> Any: ...
    def is_extended() -> Any: ...
    def is_property_hidden(*args, **kwargs) -> Any: ...
    def is_property_overridable_library(*args, **kwargs) -> Any: ...
    def is_property_readonly(*args, **kwargs) -> Any: ...
    def is_property_set(*args, **kwargs) -> Any: ...
    def items(*args, **kwargs) -> Any: ...
    def keyframe_delete(*args, **kwargs) -> Any: ...
    def keyframe_insert(*args, **kwargs) -> Any: ...
    def keys(*args, **kwargs) -> Any: ...
    def path_from_id(*args, **kwargs) -> Any: ...
    def path_from_module(*args, **kwargs) -> Any: ...
    def path_resolve(*args, **kwargs) -> Any: ...
    def poll(context) -> Any: ...
    def pop(*args, **kwargs) -> Any: ...
    def prepend(draw_func) -> Any: ...
    def property_overridable_library_set(*args, **kwargs) -> Any: ...
    def property_unset(*args, **kwargs) -> Any: ...
    def remove(draw_func) -> Any: ...
    def rna_ancestors(*args, **kwargs) -> Any: ...
    def type_recast(*args, **kwargs) -> Any: ...
    def values(*args, **kwargs) -> Any: ...

class PARTICLE_PT_physics_deflection:
    def __init__(self, /, *args, **kwargs) -> Any: ...
    def append(draw_func) -> Any: ...
    def as_pointer(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass_py(*args, **kwargs) -> Any: ...
    def draw(self, context) -> Any: ...
    def driver_add(*args, **kwargs) -> Any: ...
    def driver_remove(*args, **kwargs) -> Any: ...
    def get(*args, **kwargs) -> Any: ...
    id_data: Any
    def id_properties_clear(*args, **kwargs) -> Any: ...
    def id_properties_ensure(*args, **kwargs) -> Any: ...
    def id_properties_ui(*args, **kwargs) -> Any: ...
    def is_extended() -> Any: ...
    def is_property_hidden(*args, **kwargs) -> Any: ...
    def is_property_overridable_library(*args, **kwargs) -> Any: ...
    def is_property_readonly(*args, **kwargs) -> Any: ...
    def is_property_set(*args, **kwargs) -> Any: ...
    def items(*args, **kwargs) -> Any: ...
    def keyframe_delete(*args, **kwargs) -> Any: ...
    def keyframe_insert(*args, **kwargs) -> Any: ...
    def keys(*args, **kwargs) -> Any: ...
    def path_from_id(*args, **kwargs) -> Any: ...
    def path_from_module(*args, **kwargs) -> Any: ...
    def path_resolve(*args, **kwargs) -> Any: ...
    def poll(context) -> Any: ...
    def pop(*args, **kwargs) -> Any: ...
    def prepend(draw_func) -> Any: ...
    def property_overridable_library_set(*args, **kwargs) -> Any: ...
    def property_unset(*args, **kwargs) -> Any: ...
    def remove(draw_func) -> Any: ...
    def rna_ancestors(*args, **kwargs) -> Any: ...
    def type_recast(*args, **kwargs) -> Any: ...
    def values(*args, **kwargs) -> Any: ...

class PARTICLE_PT_physics_fluid_advanced:
    def __init__(self, /, *args, **kwargs) -> Any: ...
    def append(draw_func) -> Any: ...
    def as_pointer(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass_py(*args, **kwargs) -> Any: ...
    def draw(self, context) -> Any: ...
    def driver_add(*args, **kwargs) -> Any: ...
    def driver_remove(*args, **kwargs) -> Any: ...
    def get(*args, **kwargs) -> Any: ...
    id_data: Any
    def id_properties_clear(*args, **kwargs) -> Any: ...
    def id_properties_ensure(*args, **kwargs) -> Any: ...
    def id_properties_ui(*args, **kwargs) -> Any: ...
    def is_extended() -> Any: ...
    def is_property_hidden(*args, **kwargs) -> Any: ...
    def is_property_overridable_library(*args, **kwargs) -> Any: ...
    def is_property_readonly(*args, **kwargs) -> Any: ...
    def is_property_set(*args, **kwargs) -> Any: ...
    def items(*args, **kwargs) -> Any: ...
    def keyframe_delete(*args, **kwargs) -> Any: ...
    def keyframe_insert(*args, **kwargs) -> Any: ...
    def keys(*args, **kwargs) -> Any: ...
    def path_from_id(*args, **kwargs) -> Any: ...
    def path_from_module(*args, **kwargs) -> Any: ...
    def path_resolve(*args, **kwargs) -> Any: ...
    def poll(context) -> Any: ...
    def pop(*args, **kwargs) -> Any: ...
    def prepend(draw_func) -> Any: ...
    def property_overridable_library_set(*args, **kwargs) -> Any: ...
    def property_unset(*args, **kwargs) -> Any: ...
    def remove(draw_func) -> Any: ...
    def rna_ancestors(*args, **kwargs) -> Any: ...
    def type_recast(*args, **kwargs) -> Any: ...
    def values(*args, **kwargs) -> Any: ...

class PARTICLE_PT_physics_fluid_interaction:
    def __init__(self, /, *args, **kwargs) -> Any: ...
    def append(draw_func) -> Any: ...
    def as_pointer(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass_py(*args, **kwargs) -> Any: ...
    def draw(self, context) -> Any: ...
    def driver_add(*args, **kwargs) -> Any: ...
    def driver_remove(*args, **kwargs) -> Any: ...
    def get(*args, **kwargs) -> Any: ...
    id_data: Any
    def id_properties_clear(*args, **kwargs) -> Any: ...
    def id_properties_ensure(*args, **kwargs) -> Any: ...
    def id_properties_ui(*args, **kwargs) -> Any: ...
    def is_extended() -> Any: ...
    def is_property_hidden(*args, **kwargs) -> Any: ...
    def is_property_overridable_library(*args, **kwargs) -> Any: ...
    def is_property_readonly(*args, **kwargs) -> Any: ...
    def is_property_set(*args, **kwargs) -> Any: ...
    def items(*args, **kwargs) -> Any: ...
    def keyframe_delete(*args, **kwargs) -> Any: ...
    def keyframe_insert(*args, **kwargs) -> Any: ...
    def keys(*args, **kwargs) -> Any: ...
    def path_from_id(*args, **kwargs) -> Any: ...
    def path_from_module(*args, **kwargs) -> Any: ...
    def path_resolve(*args, **kwargs) -> Any: ...
    def poll(context) -> Any: ...
    def pop(*args, **kwargs) -> Any: ...
    def prepend(draw_func) -> Any: ...
    def property_overridable_library_set(*args, **kwargs) -> Any: ...
    def property_unset(*args, **kwargs) -> Any: ...
    def remove(draw_func) -> Any: ...
    def rna_ancestors(*args, **kwargs) -> Any: ...
    def type_recast(*args, **kwargs) -> Any: ...
    def values(*args, **kwargs) -> Any: ...

class PARTICLE_PT_physics_fluid_springs:
    def __init__(self, /, *args, **kwargs) -> Any: ...
    def append(draw_func) -> Any: ...
    def as_pointer(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass_py(*args, **kwargs) -> Any: ...
    def draw(self, context) -> Any: ...
    def driver_add(*args, **kwargs) -> Any: ...
    def driver_remove(*args, **kwargs) -> Any: ...
    def get(*args, **kwargs) -> Any: ...
    id_data: Any
    def id_properties_clear(*args, **kwargs) -> Any: ...
    def id_properties_ensure(*args, **kwargs) -> Any: ...
    def id_properties_ui(*args, **kwargs) -> Any: ...
    def is_extended() -> Any: ...
    def is_property_hidden(*args, **kwargs) -> Any: ...
    def is_property_overridable_library(*args, **kwargs) -> Any: ...
    def is_property_readonly(*args, **kwargs) -> Any: ...
    def is_property_set(*args, **kwargs) -> Any: ...
    def items(*args, **kwargs) -> Any: ...
    def keyframe_delete(*args, **kwargs) -> Any: ...
    def keyframe_insert(*args, **kwargs) -> Any: ...
    def keys(*args, **kwargs) -> Any: ...
    def path_from_id(*args, **kwargs) -> Any: ...
    def path_from_module(*args, **kwargs) -> Any: ...
    def path_resolve(*args, **kwargs) -> Any: ...
    def poll(context) -> Any: ...
    def pop(*args, **kwargs) -> Any: ...
    def prepend(draw_func) -> Any: ...
    def property_overridable_library_set(*args, **kwargs) -> Any: ...
    def property_unset(*args, **kwargs) -> Any: ...
    def remove(draw_func) -> Any: ...
    def rna_ancestors(*args, **kwargs) -> Any: ...
    def type_recast(*args, **kwargs) -> Any: ...
    def values(*args, **kwargs) -> Any: ...

class PARTICLE_PT_physics_fluid_springs_advanced:
    def __init__(self, /, *args, **kwargs) -> Any: ...
    def append(draw_func) -> Any: ...
    def as_pointer(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass_py(*args, **kwargs) -> Any: ...
    def draw(self, context) -> Any: ...
    def driver_add(*args, **kwargs) -> Any: ...
    def driver_remove(*args, **kwargs) -> Any: ...
    def get(*args, **kwargs) -> Any: ...
    id_data: Any
    def id_properties_clear(*args, **kwargs) -> Any: ...
    def id_properties_ensure(*args, **kwargs) -> Any: ...
    def id_properties_ui(*args, **kwargs) -> Any: ...
    def is_extended() -> Any: ...
    def is_property_hidden(*args, **kwargs) -> Any: ...
    def is_property_overridable_library(*args, **kwargs) -> Any: ...
    def is_property_readonly(*args, **kwargs) -> Any: ...
    def is_property_set(*args, **kwargs) -> Any: ...
    def items(*args, **kwargs) -> Any: ...
    def keyframe_delete(*args, **kwargs) -> Any: ...
    def keyframe_insert(*args, **kwargs) -> Any: ...
    def keys(*args, **kwargs) -> Any: ...
    def path_from_id(*args, **kwargs) -> Any: ...
    def path_from_module(*args, **kwargs) -> Any: ...
    def path_resolve(*args, **kwargs) -> Any: ...
    def poll(context) -> Any: ...
    def pop(*args, **kwargs) -> Any: ...
    def prepend(draw_func) -> Any: ...
    def property_overridable_library_set(*args, **kwargs) -> Any: ...
    def property_unset(*args, **kwargs) -> Any: ...
    def remove(draw_func) -> Any: ...
    def rna_ancestors(*args, **kwargs) -> Any: ...
    def type_recast(*args, **kwargs) -> Any: ...
    def values(*args, **kwargs) -> Any: ...

class PARTICLE_PT_physics_fluid_springs_viscoelastic:
    def __init__(self, /, *args, **kwargs) -> Any: ...
    def append(draw_func) -> Any: ...
    def as_pointer(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass_py(*args, **kwargs) -> Any: ...
    def draw(self, context) -> Any: ...
    def draw_header(self, context) -> Any: ...
    def driver_add(*args, **kwargs) -> Any: ...
    def driver_remove(*args, **kwargs) -> Any: ...
    def get(*args, **kwargs) -> Any: ...
    id_data: Any
    def id_properties_clear(*args, **kwargs) -> Any: ...
    def id_properties_ensure(*args, **kwargs) -> Any: ...
    def id_properties_ui(*args, **kwargs) -> Any: ...
    def is_extended() -> Any: ...
    def is_property_hidden(*args, **kwargs) -> Any: ...
    def is_property_overridable_library(*args, **kwargs) -> Any: ...
    def is_property_readonly(*args, **kwargs) -> Any: ...
    def is_property_set(*args, **kwargs) -> Any: ...
    def items(*args, **kwargs) -> Any: ...
    def keyframe_delete(*args, **kwargs) -> Any: ...
    def keyframe_insert(*args, **kwargs) -> Any: ...
    def keys(*args, **kwargs) -> Any: ...
    def path_from_id(*args, **kwargs) -> Any: ...
    def path_from_module(*args, **kwargs) -> Any: ...
    def path_resolve(*args, **kwargs) -> Any: ...
    def poll(context) -> Any: ...
    def pop(*args, **kwargs) -> Any: ...
    def prepend(draw_func) -> Any: ...
    def property_overridable_library_set(*args, **kwargs) -> Any: ...
    def property_unset(*args, **kwargs) -> Any: ...
    def remove(draw_func) -> Any: ...
    def rna_ancestors(*args, **kwargs) -> Any: ...
    def type_recast(*args, **kwargs) -> Any: ...
    def values(*args, **kwargs) -> Any: ...

class PARTICLE_PT_physics_forces:
    def __init__(self, /, *args, **kwargs) -> Any: ...
    def append(draw_func) -> Any: ...
    def as_pointer(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass_py(*args, **kwargs) -> Any: ...
    def draw(self, context) -> Any: ...
    def driver_add(*args, **kwargs) -> Any: ...
    def driver_remove(*args, **kwargs) -> Any: ...
    def get(*args, **kwargs) -> Any: ...
    id_data: Any
    def id_properties_clear(*args, **kwargs) -> Any: ...
    def id_properties_ensure(*args, **kwargs) -> Any: ...
    def id_properties_ui(*args, **kwargs) -> Any: ...
    def is_extended() -> Any: ...
    def is_property_hidden(*args, **kwargs) -> Any: ...
    def is_property_overridable_library(*args, **kwargs) -> Any: ...
    def is_property_readonly(*args, **kwargs) -> Any: ...
    def is_property_set(*args, **kwargs) -> Any: ...
    def items(*args, **kwargs) -> Any: ...
    def keyframe_delete(*args, **kwargs) -> Any: ...
    def keyframe_insert(*args, **kwargs) -> Any: ...
    def keys(*args, **kwargs) -> Any: ...
    def path_from_id(*args, **kwargs) -> Any: ...
    def path_from_module(*args, **kwargs) -> Any: ...
    def path_resolve(*args, **kwargs) -> Any: ...
    def poll(context) -> Any: ...
    def pop(*args, **kwargs) -> Any: ...
    def prepend(draw_func) -> Any: ...
    def property_overridable_library_set(*args, **kwargs) -> Any: ...
    def property_unset(*args, **kwargs) -> Any: ...
    def remove(draw_func) -> Any: ...
    def rna_ancestors(*args, **kwargs) -> Any: ...
    def type_recast(*args, **kwargs) -> Any: ...
    def values(*args, **kwargs) -> Any: ...

class PARTICLE_PT_physics_integration:
    def __init__(self, /, *args, **kwargs) -> Any: ...
    def append(draw_func) -> Any: ...
    def as_pointer(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass_py(*args, **kwargs) -> Any: ...
    def draw(self, context) -> Any: ...
    def driver_add(*args, **kwargs) -> Any: ...
    def driver_remove(*args, **kwargs) -> Any: ...
    def get(*args, **kwargs) -> Any: ...
    id_data: Any
    def id_properties_clear(*args, **kwargs) -> Any: ...
    def id_properties_ensure(*args, **kwargs) -> Any: ...
    def id_properties_ui(*args, **kwargs) -> Any: ...
    def is_extended() -> Any: ...
    def is_property_hidden(*args, **kwargs) -> Any: ...
    def is_property_overridable_library(*args, **kwargs) -> Any: ...
    def is_property_readonly(*args, **kwargs) -> Any: ...
    def is_property_set(*args, **kwargs) -> Any: ...
    def items(*args, **kwargs) -> Any: ...
    def keyframe_delete(*args, **kwargs) -> Any: ...
    def keyframe_insert(*args, **kwargs) -> Any: ...
    def keys(*args, **kwargs) -> Any: ...
    def path_from_id(*args, **kwargs) -> Any: ...
    def path_from_module(*args, **kwargs) -> Any: ...
    def path_resolve(*args, **kwargs) -> Any: ...
    def poll(context) -> Any: ...
    def pop(*args, **kwargs) -> Any: ...
    def prepend(draw_func) -> Any: ...
    def property_overridable_library_set(*args, **kwargs) -> Any: ...
    def property_unset(*args, **kwargs) -> Any: ...
    def remove(draw_func) -> Any: ...
    def rna_ancestors(*args, **kwargs) -> Any: ...
    def type_recast(*args, **kwargs) -> Any: ...
    def values(*args, **kwargs) -> Any: ...

class PARTICLE_PT_physics_relations:
    def __init__(self, /, *args, **kwargs) -> Any: ...
    def append(draw_func) -> Any: ...
    def as_pointer(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass_py(*args, **kwargs) -> Any: ...
    def draw(self, context) -> Any: ...
    def driver_add(*args, **kwargs) -> Any: ...
    def driver_remove(*args, **kwargs) -> Any: ...
    def get(*args, **kwargs) -> Any: ...
    id_data: Any
    def id_properties_clear(*args, **kwargs) -> Any: ...
    def id_properties_ensure(*args, **kwargs) -> Any: ...
    def id_properties_ui(*args, **kwargs) -> Any: ...
    def is_extended() -> Any: ...
    def is_property_hidden(*args, **kwargs) -> Any: ...
    def is_property_overridable_library(*args, **kwargs) -> Any: ...
    def is_property_readonly(*args, **kwargs) -> Any: ...
    def is_property_set(*args, **kwargs) -> Any: ...
    def items(*args, **kwargs) -> Any: ...
    def keyframe_delete(*args, **kwargs) -> Any: ...
    def keyframe_insert(*args, **kwargs) -> Any: ...
    def keys(*args, **kwargs) -> Any: ...
    def path_from_id(*args, **kwargs) -> Any: ...
    def path_from_module(*args, **kwargs) -> Any: ...
    def path_resolve(*args, **kwargs) -> Any: ...
    def poll(context) -> Any: ...
    def pop(*args, **kwargs) -> Any: ...
    def prepend(draw_func) -> Any: ...
    def property_overridable_library_set(*args, **kwargs) -> Any: ...
    def property_unset(*args, **kwargs) -> Any: ...
    def remove(draw_func) -> Any: ...
    def rna_ancestors(*args, **kwargs) -> Any: ...
    def type_recast(*args, **kwargs) -> Any: ...
    def values(*args, **kwargs) -> Any: ...

class PARTICLE_PT_render:
    def __init__(self, /, *args, **kwargs) -> Any: ...
    def append(draw_func) -> Any: ...
    def as_pointer(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass_py(*args, **kwargs) -> Any: ...
    def draw(self, context) -> Any: ...
    def driver_add(*args, **kwargs) -> Any: ...
    def driver_remove(*args, **kwargs) -> Any: ...
    def get(*args, **kwargs) -> Any: ...
    id_data: Any
    def id_properties_clear(*args, **kwargs) -> Any: ...
    def id_properties_ensure(*args, **kwargs) -> Any: ...
    def id_properties_ui(*args, **kwargs) -> Any: ...
    def is_extended() -> Any: ...
    def is_property_hidden(*args, **kwargs) -> Any: ...
    def is_property_overridable_library(*args, **kwargs) -> Any: ...
    def is_property_readonly(*args, **kwargs) -> Any: ...
    def is_property_set(*args, **kwargs) -> Any: ...
    def items(*args, **kwargs) -> Any: ...
    def keyframe_delete(*args, **kwargs) -> Any: ...
    def keyframe_insert(*args, **kwargs) -> Any: ...
    def keys(*args, **kwargs) -> Any: ...
    def path_from_id(*args, **kwargs) -> Any: ...
    def path_from_module(*args, **kwargs) -> Any: ...
    def path_resolve(*args, **kwargs) -> Any: ...
    def poll(context) -> Any: ...
    def pop(*args, **kwargs) -> Any: ...
    def prepend(draw_func) -> Any: ...
    def property_overridable_library_set(*args, **kwargs) -> Any: ...
    def property_unset(*args, **kwargs) -> Any: ...
    def remove(draw_func) -> Any: ...
    def rna_ancestors(*args, **kwargs) -> Any: ...
    def type_recast(*args, **kwargs) -> Any: ...
    def values(*args, **kwargs) -> Any: ...

class PARTICLE_PT_render_collection:
    def __init__(self, /, *args, **kwargs) -> Any: ...
    def append(draw_func) -> Any: ...
    def as_pointer(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass_py(*args, **kwargs) -> Any: ...
    def draw(self, context) -> Any: ...
    def driver_add(*args, **kwargs) -> Any: ...
    def driver_remove(*args, **kwargs) -> Any: ...
    def get(*args, **kwargs) -> Any: ...
    id_data: Any
    def id_properties_clear(*args, **kwargs) -> Any: ...
    def id_properties_ensure(*args, **kwargs) -> Any: ...
    def id_properties_ui(*args, **kwargs) -> Any: ...
    def is_extended() -> Any: ...
    def is_property_hidden(*args, **kwargs) -> Any: ...
    def is_property_overridable_library(*args, **kwargs) -> Any: ...
    def is_property_readonly(*args, **kwargs) -> Any: ...
    def is_property_set(*args, **kwargs) -> Any: ...
    def items(*args, **kwargs) -> Any: ...
    def keyframe_delete(*args, **kwargs) -> Any: ...
    def keyframe_insert(*args, **kwargs) -> Any: ...
    def keys(*args, **kwargs) -> Any: ...
    def path_from_id(*args, **kwargs) -> Any: ...
    def path_from_module(*args, **kwargs) -> Any: ...
    def path_resolve(*args, **kwargs) -> Any: ...
    def poll(context) -> Any: ...
    def pop(*args, **kwargs) -> Any: ...
    def prepend(draw_func) -> Any: ...
    def property_overridable_library_set(*args, **kwargs) -> Any: ...
    def property_unset(*args, **kwargs) -> Any: ...
    def remove(draw_func) -> Any: ...
    def rna_ancestors(*args, **kwargs) -> Any: ...
    def type_recast(*args, **kwargs) -> Any: ...
    def values(*args, **kwargs) -> Any: ...

class PARTICLE_PT_render_collection_use_count:
    def __init__(self, /, *args, **kwargs) -> Any: ...
    def append(draw_func) -> Any: ...
    def as_pointer(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass_py(*args, **kwargs) -> Any: ...
    def draw(self, context) -> Any: ...
    def draw_header(self, context) -> Any: ...
    def driver_add(*args, **kwargs) -> Any: ...
    def driver_remove(*args, **kwargs) -> Any: ...
    def get(*args, **kwargs) -> Any: ...
    id_data: Any
    def id_properties_clear(*args, **kwargs) -> Any: ...
    def id_properties_ensure(*args, **kwargs) -> Any: ...
    def id_properties_ui(*args, **kwargs) -> Any: ...
    def is_extended() -> Any: ...
    def is_property_hidden(*args, **kwargs) -> Any: ...
    def is_property_overridable_library(*args, **kwargs) -> Any: ...
    def is_property_readonly(*args, **kwargs) -> Any: ...
    def is_property_set(*args, **kwargs) -> Any: ...
    def items(*args, **kwargs) -> Any: ...
    def keyframe_delete(*args, **kwargs) -> Any: ...
    def keyframe_insert(*args, **kwargs) -> Any: ...
    def keys(*args, **kwargs) -> Any: ...
    def path_from_id(*args, **kwargs) -> Any: ...
    def path_from_module(*args, **kwargs) -> Any: ...
    def path_resolve(*args, **kwargs) -> Any: ...
    def poll(context) -> Any: ...
    def pop(*args, **kwargs) -> Any: ...
    def prepend(draw_func) -> Any: ...
    def property_overridable_library_set(*args, **kwargs) -> Any: ...
    def property_unset(*args, **kwargs) -> Any: ...
    def remove(draw_func) -> Any: ...
    def rna_ancestors(*args, **kwargs) -> Any: ...
    def type_recast(*args, **kwargs) -> Any: ...
    def values(*args, **kwargs) -> Any: ...

class PARTICLE_PT_render_extra:
    def __init__(self, /, *args, **kwargs) -> Any: ...
    def append(draw_func) -> Any: ...
    def as_pointer(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass_py(*args, **kwargs) -> Any: ...
    def draw(self, context) -> Any: ...
    def driver_add(*args, **kwargs) -> Any: ...
    def driver_remove(*args, **kwargs) -> Any: ...
    def get(*args, **kwargs) -> Any: ...
    id_data: Any
    def id_properties_clear(*args, **kwargs) -> Any: ...
    def id_properties_ensure(*args, **kwargs) -> Any: ...
    def id_properties_ui(*args, **kwargs) -> Any: ...
    def is_extended() -> Any: ...
    def is_property_hidden(*args, **kwargs) -> Any: ...
    def is_property_overridable_library(*args, **kwargs) -> Any: ...
    def is_property_readonly(*args, **kwargs) -> Any: ...
    def is_property_set(*args, **kwargs) -> Any: ...
    def items(*args, **kwargs) -> Any: ...
    def keyframe_delete(*args, **kwargs) -> Any: ...
    def keyframe_insert(*args, **kwargs) -> Any: ...
    def keys(*args, **kwargs) -> Any: ...
    def path_from_id(*args, **kwargs) -> Any: ...
    def path_from_module(*args, **kwargs) -> Any: ...
    def path_resolve(*args, **kwargs) -> Any: ...
    def poll(context) -> Any: ...
    def pop(*args, **kwargs) -> Any: ...
    def prepend(draw_func) -> Any: ...
    def property_overridable_library_set(*args, **kwargs) -> Any: ...
    def property_unset(*args, **kwargs) -> Any: ...
    def remove(draw_func) -> Any: ...
    def rna_ancestors(*args, **kwargs) -> Any: ...
    def type_recast(*args, **kwargs) -> Any: ...
    def values(*args, **kwargs) -> Any: ...

class PARTICLE_PT_render_object:
    def __init__(self, /, *args, **kwargs) -> Any: ...
    def append(draw_func) -> Any: ...
    def as_pointer(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass_py(*args, **kwargs) -> Any: ...
    def draw(self, context) -> Any: ...
    def driver_add(*args, **kwargs) -> Any: ...
    def driver_remove(*args, **kwargs) -> Any: ...
    def get(*args, **kwargs) -> Any: ...
    id_data: Any
    def id_properties_clear(*args, **kwargs) -> Any: ...
    def id_properties_ensure(*args, **kwargs) -> Any: ...
    def id_properties_ui(*args, **kwargs) -> Any: ...
    def is_extended() -> Any: ...
    def is_property_hidden(*args, **kwargs) -> Any: ...
    def is_property_overridable_library(*args, **kwargs) -> Any: ...
    def is_property_readonly(*args, **kwargs) -> Any: ...
    def is_property_set(*args, **kwargs) -> Any: ...
    def items(*args, **kwargs) -> Any: ...
    def keyframe_delete(*args, **kwargs) -> Any: ...
    def keyframe_insert(*args, **kwargs) -> Any: ...
    def keys(*args, **kwargs) -> Any: ...
    def path_from_id(*args, **kwargs) -> Any: ...
    def path_from_module(*args, **kwargs) -> Any: ...
    def path_resolve(*args, **kwargs) -> Any: ...
    def poll(context) -> Any: ...
    def pop(*args, **kwargs) -> Any: ...
    def prepend(draw_func) -> Any: ...
    def property_overridable_library_set(*args, **kwargs) -> Any: ...
    def property_unset(*args, **kwargs) -> Any: ...
    def remove(draw_func) -> Any: ...
    def rna_ancestors(*args, **kwargs) -> Any: ...
    def type_recast(*args, **kwargs) -> Any: ...
    def values(*args, **kwargs) -> Any: ...

class PARTICLE_PT_render_path:
    def __init__(self, /, *args, **kwargs) -> Any: ...
    def append(draw_func) -> Any: ...
    def as_pointer(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass_py(*args, **kwargs) -> Any: ...
    def draw(self, context) -> Any: ...
    def driver_add(*args, **kwargs) -> Any: ...
    def driver_remove(*args, **kwargs) -> Any: ...
    def get(*args, **kwargs) -> Any: ...
    id_data: Any
    def id_properties_clear(*args, **kwargs) -> Any: ...
    def id_properties_ensure(*args, **kwargs) -> Any: ...
    def id_properties_ui(*args, **kwargs) -> Any: ...
    def is_extended() -> Any: ...
    def is_property_hidden(*args, **kwargs) -> Any: ...
    def is_property_overridable_library(*args, **kwargs) -> Any: ...
    def is_property_readonly(*args, **kwargs) -> Any: ...
    def is_property_set(*args, **kwargs) -> Any: ...
    def items(*args, **kwargs) -> Any: ...
    def keyframe_delete(*args, **kwargs) -> Any: ...
    def keyframe_insert(*args, **kwargs) -> Any: ...
    def keys(*args, **kwargs) -> Any: ...
    def path_from_id(*args, **kwargs) -> Any: ...
    def path_from_module(*args, **kwargs) -> Any: ...
    def path_resolve(*args, **kwargs) -> Any: ...
    def poll(context) -> Any: ...
    def pop(*args, **kwargs) -> Any: ...
    def prepend(draw_func) -> Any: ...
    def property_overridable_library_set(*args, **kwargs) -> Any: ...
    def property_unset(*args, **kwargs) -> Any: ...
    def remove(draw_func) -> Any: ...
    def rna_ancestors(*args, **kwargs) -> Any: ...
    def type_recast(*args, **kwargs) -> Any: ...
    def values(*args, **kwargs) -> Any: ...

class PARTICLE_PT_render_path_timing:
    def __init__(self, /, *args, **kwargs) -> Any: ...
    def append(draw_func) -> Any: ...
    def as_pointer(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass_py(*args, **kwargs) -> Any: ...
    def draw(self, context) -> Any: ...
    def driver_add(*args, **kwargs) -> Any: ...
    def driver_remove(*args, **kwargs) -> Any: ...
    def get(*args, **kwargs) -> Any: ...
    id_data: Any
    def id_properties_clear(*args, **kwargs) -> Any: ...
    def id_properties_ensure(*args, **kwargs) -> Any: ...
    def id_properties_ui(*args, **kwargs) -> Any: ...
    def is_extended() -> Any: ...
    def is_property_hidden(*args, **kwargs) -> Any: ...
    def is_property_overridable_library(*args, **kwargs) -> Any: ...
    def is_property_readonly(*args, **kwargs) -> Any: ...
    def is_property_set(*args, **kwargs) -> Any: ...
    def items(*args, **kwargs) -> Any: ...
    def keyframe_delete(*args, **kwargs) -> Any: ...
    def keyframe_insert(*args, **kwargs) -> Any: ...
    def keys(*args, **kwargs) -> Any: ...
    def path_from_id(*args, **kwargs) -> Any: ...
    def path_from_module(*args, **kwargs) -> Any: ...
    def path_resolve(*args, **kwargs) -> Any: ...
    def poll(context) -> Any: ...
    def pop(*args, **kwargs) -> Any: ...
    def prepend(draw_func) -> Any: ...
    def property_overridable_library_set(*args, **kwargs) -> Any: ...
    def property_unset(*args, **kwargs) -> Any: ...
    def remove(draw_func) -> Any: ...
    def rna_ancestors(*args, **kwargs) -> Any: ...
    def type_recast(*args, **kwargs) -> Any: ...
    def values(*args, **kwargs) -> Any: ...

class PARTICLE_PT_rotation:
    def __init__(self, /, *args, **kwargs) -> Any: ...
    def append(draw_func) -> Any: ...
    def as_pointer(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass_py(*args, **kwargs) -> Any: ...
    def draw(self, context) -> Any: ...
    def draw_header(self, context) -> Any: ...
    def driver_add(*args, **kwargs) -> Any: ...
    def driver_remove(*args, **kwargs) -> Any: ...
    def get(*args, **kwargs) -> Any: ...
    id_data: Any
    def id_properties_clear(*args, **kwargs) -> Any: ...
    def id_properties_ensure(*args, **kwargs) -> Any: ...
    def id_properties_ui(*args, **kwargs) -> Any: ...
    def is_extended() -> Any: ...
    def is_property_hidden(*args, **kwargs) -> Any: ...
    def is_property_overridable_library(*args, **kwargs) -> Any: ...
    def is_property_readonly(*args, **kwargs) -> Any: ...
    def is_property_set(*args, **kwargs) -> Any: ...
    def items(*args, **kwargs) -> Any: ...
    def keyframe_delete(*args, **kwargs) -> Any: ...
    def keyframe_insert(*args, **kwargs) -> Any: ...
    def keys(*args, **kwargs) -> Any: ...
    def path_from_id(*args, **kwargs) -> Any: ...
    def path_from_module(*args, **kwargs) -> Any: ...
    def path_resolve(*args, **kwargs) -> Any: ...
    def poll(context) -> Any: ...
    def pop(*args, **kwargs) -> Any: ...
    def prepend(draw_func) -> Any: ...
    def property_overridable_library_set(*args, **kwargs) -> Any: ...
    def property_unset(*args, **kwargs) -> Any: ...
    def remove(draw_func) -> Any: ...
    def rna_ancestors(*args, **kwargs) -> Any: ...
    def type_recast(*args, **kwargs) -> Any: ...
    def values(*args, **kwargs) -> Any: ...

class PARTICLE_PT_rotation_angular_velocity:
    def __init__(self, /, *args, **kwargs) -> Any: ...
    def append(draw_func) -> Any: ...
    def as_pointer(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass_py(*args, **kwargs) -> Any: ...
    def draw(self, context) -> Any: ...
    def driver_add(*args, **kwargs) -> Any: ...
    def driver_remove(*args, **kwargs) -> Any: ...
    def get(*args, **kwargs) -> Any: ...
    id_data: Any
    def id_properties_clear(*args, **kwargs) -> Any: ...
    def id_properties_ensure(*args, **kwargs) -> Any: ...
    def id_properties_ui(*args, **kwargs) -> Any: ...
    def is_extended() -> Any: ...
    def is_property_hidden(*args, **kwargs) -> Any: ...
    def is_property_overridable_library(*args, **kwargs) -> Any: ...
    def is_property_readonly(*args, **kwargs) -> Any: ...
    def is_property_set(*args, **kwargs) -> Any: ...
    def items(*args, **kwargs) -> Any: ...
    def keyframe_delete(*args, **kwargs) -> Any: ...
    def keyframe_insert(*args, **kwargs) -> Any: ...
    def keys(*args, **kwargs) -> Any: ...
    def path_from_id(*args, **kwargs) -> Any: ...
    def path_from_module(*args, **kwargs) -> Any: ...
    def path_resolve(*args, **kwargs) -> Any: ...
    def poll(context) -> Any: ...
    def pop(*args, **kwargs) -> Any: ...
    def prepend(draw_func) -> Any: ...
    def property_overridable_library_set(*args, **kwargs) -> Any: ...
    def property_unset(*args, **kwargs) -> Any: ...
    def remove(draw_func) -> Any: ...
    def rna_ancestors(*args, **kwargs) -> Any: ...
    def type_recast(*args, **kwargs) -> Any: ...
    def values(*args, **kwargs) -> Any: ...

class PARTICLE_PT_textures:
    def __init__(self, /, *args, **kwargs) -> Any: ...
    def append(draw_func) -> Any: ...
    def as_pointer(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass_py(*args, **kwargs) -> Any: ...
    def draw(self, context) -> Any: ...
    def driver_add(*args, **kwargs) -> Any: ...
    def driver_remove(*args, **kwargs) -> Any: ...
    def get(*args, **kwargs) -> Any: ...
    id_data: Any
    def id_properties_clear(*args, **kwargs) -> Any: ...
    def id_properties_ensure(*args, **kwargs) -> Any: ...
    def id_properties_ui(*args, **kwargs) -> Any: ...
    def is_extended() -> Any: ...
    def is_property_hidden(*args, **kwargs) -> Any: ...
    def is_property_overridable_library(*args, **kwargs) -> Any: ...
    def is_property_readonly(*args, **kwargs) -> Any: ...
    def is_property_set(*args, **kwargs) -> Any: ...
    def items(*args, **kwargs) -> Any: ...
    def keyframe_delete(*args, **kwargs) -> Any: ...
    def keyframe_insert(*args, **kwargs) -> Any: ...
    def keys(*args, **kwargs) -> Any: ...
    def path_from_id(*args, **kwargs) -> Any: ...
    def path_from_module(*args, **kwargs) -> Any: ...
    def path_resolve(*args, **kwargs) -> Any: ...
    def poll(context) -> Any: ...
    def pop(*args, **kwargs) -> Any: ...
    def prepend(draw_func) -> Any: ...
    def property_overridable_library_set(*args, **kwargs) -> Any: ...
    def property_unset(*args, **kwargs) -> Any: ...
    def remove(draw_func) -> Any: ...
    def rna_ancestors(*args, **kwargs) -> Any: ...
    def type_recast(*args, **kwargs) -> Any: ...
    def values(*args, **kwargs) -> Any: ...

class PARTICLE_PT_velocity:
    def __init__(self, /, *args, **kwargs) -> Any: ...
    def append(draw_func) -> Any: ...
    def as_pointer(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass_py(*args, **kwargs) -> Any: ...
    def draw(self, context) -> Any: ...
    def driver_add(*args, **kwargs) -> Any: ...
    def driver_remove(*args, **kwargs) -> Any: ...
    def get(*args, **kwargs) -> Any: ...
    id_data: Any
    def id_properties_clear(*args, **kwargs) -> Any: ...
    def id_properties_ensure(*args, **kwargs) -> Any: ...
    def id_properties_ui(*args, **kwargs) -> Any: ...
    def is_extended() -> Any: ...
    def is_property_hidden(*args, **kwargs) -> Any: ...
    def is_property_overridable_library(*args, **kwargs) -> Any: ...
    def is_property_readonly(*args, **kwargs) -> Any: ...
    def is_property_set(*args, **kwargs) -> Any: ...
    def items(*args, **kwargs) -> Any: ...
    def keyframe_delete(*args, **kwargs) -> Any: ...
    def keyframe_insert(*args, **kwargs) -> Any: ...
    def keys(*args, **kwargs) -> Any: ...
    def path_from_id(*args, **kwargs) -> Any: ...
    def path_from_module(*args, **kwargs) -> Any: ...
    def path_resolve(*args, **kwargs) -> Any: ...
    def poll(context) -> Any: ...
    def pop(*args, **kwargs) -> Any: ...
    def prepend(draw_func) -> Any: ...
    def property_overridable_library_set(*args, **kwargs) -> Any: ...
    def property_unset(*args, **kwargs) -> Any: ...
    def remove(draw_func) -> Any: ...
    def rna_ancestors(*args, **kwargs) -> Any: ...
    def type_recast(*args, **kwargs) -> Any: ...
    def values(*args, **kwargs) -> Any: ...

class PARTICLE_PT_vertexgroups:
    def __init__(self, /, *args, **kwargs) -> Any: ...
    def append(draw_func) -> Any: ...
    def as_pointer(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass_py(*args, **kwargs) -> Any: ...
    def draw(self, context) -> Any: ...
    def driver_add(*args, **kwargs) -> Any: ...
    def driver_remove(*args, **kwargs) -> Any: ...
    def get(*args, **kwargs) -> Any: ...
    id_data: Any
    def id_properties_clear(*args, **kwargs) -> Any: ...
    def id_properties_ensure(*args, **kwargs) -> Any: ...
    def id_properties_ui(*args, **kwargs) -> Any: ...
    def is_extended() -> Any: ...
    def is_property_hidden(*args, **kwargs) -> Any: ...
    def is_property_overridable_library(*args, **kwargs) -> Any: ...
    def is_property_readonly(*args, **kwargs) -> Any: ...
    def is_property_set(*args, **kwargs) -> Any: ...
    def items(*args, **kwargs) -> Any: ...
    def keyframe_delete(*args, **kwargs) -> Any: ...
    def keyframe_insert(*args, **kwargs) -> Any: ...
    def keys(*args, **kwargs) -> Any: ...
    def path_from_id(*args, **kwargs) -> Any: ...
    def path_from_module(*args, **kwargs) -> Any: ...
    def path_resolve(*args, **kwargs) -> Any: ...
    def poll(context) -> Any: ...
    def pop(*args, **kwargs) -> Any: ...
    def prepend(draw_func) -> Any: ...
    def property_overridable_library_set(*args, **kwargs) -> Any: ...
    def property_unset(*args, **kwargs) -> Any: ...
    def remove(draw_func) -> Any: ...
    def rna_ancestors(*args, **kwargs) -> Any: ...
    def type_recast(*args, **kwargs) -> Any: ...
    def values(*args, **kwargs) -> Any: ...

class PARTICLE_UL_particle_systems:
    def __init__(self, /, *args, **kwargs) -> Any: ...
    def append(draw_func) -> Any: ...
    def as_pointer(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass_py(*args, **kwargs) -> Any: ...
    def draw_item(self, _context, layout, data, item, icon, _active_data, _active_propname, _index, _flt_flag) -> Any: ...
    def driver_add(*args, **kwargs) -> Any: ...
    def driver_remove(*args, **kwargs) -> Any: ...
    def get(*args, **kwargs) -> Any: ...
    id_data: Any
    def id_properties_clear(*args, **kwargs) -> Any: ...
    def id_properties_ensure(*args, **kwargs) -> Any: ...
    def id_properties_ui(*args, **kwargs) -> Any: ...
    def is_extended() -> Any: ...
    def is_property_hidden(*args, **kwargs) -> Any: ...
    def is_property_overridable_library(*args, **kwargs) -> Any: ...
    def is_property_readonly(*args, **kwargs) -> Any: ...
    def is_property_set(*args, **kwargs) -> Any: ...
    def items(*args, **kwargs) -> Any: ...
    def keyframe_delete(*args, **kwargs) -> Any: ...
    def keyframe_insert(*args, **kwargs) -> Any: ...
    def keys(*args, **kwargs) -> Any: ...
    def path_from_id(*args, **kwargs) -> Any: ...
    def path_from_module(*args, **kwargs) -> Any: ...
    def path_resolve(*args, **kwargs) -> Any: ...
    def pop(*args, **kwargs) -> Any: ...
    def prepend(draw_func) -> Any: ...
    def property_overridable_library_set(*args, **kwargs) -> Any: ...
    def property_unset(*args, **kwargs) -> Any: ...
    def remove(draw_func) -> Any: ...
    def rna_ancestors(*args, **kwargs) -> Any: ...
    def type_recast(*args, **kwargs) -> Any: ...
    def values(*args, **kwargs) -> Any: ...

class Panel:
    def __init__(self, /, *args, **kwargs) -> Any: ...
    def append(draw_func) -> Any: ...
    def as_pointer(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass_py(*args, **kwargs) -> Any: ...
    def driver_add(*args, **kwargs) -> Any: ...
    def driver_remove(*args, **kwargs) -> Any: ...
    def get(*args, **kwargs) -> Any: ...
    id_data: Any
    def id_properties_clear(*args, **kwargs) -> Any: ...
    def id_properties_ensure(*args, **kwargs) -> Any: ...
    def id_properties_ui(*args, **kwargs) -> Any: ...
    def is_extended() -> Any: ...
    def is_property_hidden(*args, **kwargs) -> Any: ...
    def is_property_overridable_library(*args, **kwargs) -> Any: ...
    def is_property_readonly(*args, **kwargs) -> Any: ...
    def is_property_set(*args, **kwargs) -> Any: ...
    def items(*args, **kwargs) -> Any: ...
    def keyframe_delete(*args, **kwargs) -> Any: ...
    def keyframe_insert(*args, **kwargs) -> Any: ...
    def keys(*args, **kwargs) -> Any: ...
    def path_from_id(*args, **kwargs) -> Any: ...
    def path_from_module(*args, **kwargs) -> Any: ...
    def path_resolve(*args, **kwargs) -> Any: ...
    def pop(*args, **kwargs) -> Any: ...
    def prepend(draw_func) -> Any: ...
    def property_overridable_library_set(*args, **kwargs) -> Any: ...
    def property_unset(*args, **kwargs) -> Any: ...
    def remove(draw_func) -> Any: ...
    def rna_ancestors(*args, **kwargs) -> Any: ...
    def type_recast(*args, **kwargs) -> Any: ...
    def values(*args, **kwargs) -> Any: ...

class ParticleButtonsPanel:
    def __init__(self, /, *args, **kwargs) -> Any: ...
    def poll(context) -> Any: ...

class PresetPanel:
    def __init__(self, /, *args, **kwargs) -> Any: ...
    def draw(self, context) -> Any: ...
    def draw_menu(layout, text=None) -> Any: ...
    def draw_panel_header(layout) -> Any: ...
    def path_menu(self, searchpaths, operator, *, props_default=None, prop_filepath='filepath', filter_ext=None, filter_path=None, display_name=None, add_operator=None, add_operator_props=None, translate=True) -> Any: ...

class PropertiesAnimationMixin:
    """Mix-in class for Animation panels.

    This class can be used to show a generic 'Animation' panel for IDs shown in
    the properties editor. Specific ID types need specific subclasses.

    For an example, see DATA_PT_camera_animation in properties_data_camera.py
    """
    def __init__(self, /, *args, **kwargs) -> Any: ...
    def draw(self, context) -> Any: ...
    def draw_action_and_slot_selector(context, layout, animated_id) -> Any: ...
    def poll(context) -> Any: ...

class PropertyPanel:
    """
    The subclass should have its own poll function
    and the variable '_context_path' MUST be set.
    """
    def __init__(self, /, *args, **kwargs) -> Any: ...
    def draw(self, context) -> Any: ...
    def poll(context) -> Any: ...

class UIList:
    def __init__(self, /, *args, **kwargs) -> Any: ...
    def append(draw_func) -> Any: ...
    def as_pointer(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass_py(*args, **kwargs) -> Any: ...
    def driver_add(*args, **kwargs) -> Any: ...
    def driver_remove(*args, **kwargs) -> Any: ...
    def get(*args, **kwargs) -> Any: ...
    id_data: Any
    def id_properties_clear(*args, **kwargs) -> Any: ...
    def id_properties_ensure(*args, **kwargs) -> Any: ...
    def id_properties_ui(*args, **kwargs) -> Any: ...
    def is_extended() -> Any: ...
    def is_property_hidden(*args, **kwargs) -> Any: ...
    def is_property_overridable_library(*args, **kwargs) -> Any: ...
    def is_property_readonly(*args, **kwargs) -> Any: ...
    def is_property_set(*args, **kwargs) -> Any: ...
    def items(*args, **kwargs) -> Any: ...
    def keyframe_delete(*args, **kwargs) -> Any: ...
    def keyframe_insert(*args, **kwargs) -> Any: ...
    def keys(*args, **kwargs) -> Any: ...
    def path_from_id(*args, **kwargs) -> Any: ...
    def path_from_module(*args, **kwargs) -> Any: ...
    def path_resolve(*args, **kwargs) -> Any: ...
    def pop(*args, **kwargs) -> Any: ...
    def prepend(draw_func) -> Any: ...
    def property_overridable_library_set(*args, **kwargs) -> Any: ...
    def property_unset(*args, **kwargs) -> Any: ...
    def remove(draw_func) -> Any: ...
    def rna_ancestors(*args, **kwargs) -> Any: ...
    def type_recast(*args, **kwargs) -> Any: ...
    def values(*args, **kwargs) -> Any: ...

def basic_force_field_falloff_ui(self, field) -> Any:
    ...

def basic_force_field_settings_ui(self, field) -> Any:
    ...

classes: Any
def effector_weights_ui(self, weights, weight_type) -> Any:
    ...

def find_modifier(ob, psys) -> Any:
    ...

i18n_contexts: Any
def iface_(*args, **kwargs) -> Any:
    ...

def particle_get_settings(context) -> Any:
    ...

def particle_panel_enabled(context, psys) -> Any:
    ...

def particle_panel_poll(cls, context) -> Any:
    ...

def point_cache_ui(self, cache, enabled, cachetype) -> Any:
    ...

def rpt_(*args, **kwargs) -> Any:
    ...
