"""
Online Documentation:
https://docs.blender.org/api/current/bpy_extras.anim_utils.html
"""

# Blender Probe Generated Stub for Blender 5.0.1
# noinspection PyPep8Naming
# noinspection PyUnresolvedReferences
# noqa: N801
# pylint: disable=invalid-name


import sys
import typing
from typing import Any, Union, Callable, Iterator

class Action:
    """
    Online Documentation:
    https://docs.blender.org/api/current/bpy_extras.anim_utils.html
    """
    def __init__(self, /, *args, **kwargs) -> Any: ...
    def as_pointer(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass_py(*args, **kwargs) -> Any: ...
    def driver_add(*args, **kwargs) -> Any: ...
    def driver_remove(*args, **kwargs) -> Any: ...
    def get(*args, **kwargs) -> Any: ...
    id_data: Any
    def id_properties_clear(*args, **kwargs) -> Any: ...
    def id_properties_ensure(*args, **kwargs) -> Any: ...
    def id_properties_ui(*args, **kwargs) -> Any: ...
    def is_property_hidden(*args, **kwargs) -> Any: ...
    def is_property_overridable_library(*args, **kwargs) -> Any: ...
    def is_property_readonly(*args, **kwargs) -> Any: ...
    def is_property_set(*args, **kwargs) -> Any: ...
    def items(*args, **kwargs) -> Any: ...
    def keyframe_delete(*args, **kwargs) -> Any: ...
    def keyframe_insert(*args, **kwargs) -> Any: ...
    def keys(*args, **kwargs) -> Any: ...
    def path_from_id(*args, **kwargs) -> Any: ...
    def path_from_module(*args, **kwargs) -> Any: ...
    def path_resolve(*args, **kwargs) -> Any: ...
    def pop(*args, **kwargs) -> Any: ...
    def property_overridable_library_set(*args, **kwargs) -> Any: ...
    def property_unset(*args, **kwargs) -> Any: ...
    def rna_ancestors(*args, **kwargs) -> Any: ...
    def type_recast(*args, **kwargs) -> Any: ...
    def values(*args, **kwargs) -> Any: ...

class ActionChannelbag:
    """
    Online Documentation:
    https://docs.blender.org/api/current/bpy_extras.anim_utils.html
    """
    def __init__(self, /, *args, **kwargs) -> Any: ...
    def as_pointer(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass_py(*args, **kwargs) -> Any: ...
    def driver_add(*args, **kwargs) -> Any: ...
    def driver_remove(*args, **kwargs) -> Any: ...
    def get(*args, **kwargs) -> Any: ...
    id_data: Any
    def id_properties_clear(*args, **kwargs) -> Any: ...
    def id_properties_ensure(*args, **kwargs) -> Any: ...
    def id_properties_ui(*args, **kwargs) -> Any: ...
    def is_property_hidden(*args, **kwargs) -> Any: ...
    def is_property_overridable_library(*args, **kwargs) -> Any: ...
    def is_property_readonly(*args, **kwargs) -> Any: ...
    def is_property_set(*args, **kwargs) -> Any: ...
    def items(*args, **kwargs) -> Any: ...
    def keyframe_delete(*args, **kwargs) -> Any: ...
    def keyframe_insert(*args, **kwargs) -> Any: ...
    def keys(*args, **kwargs) -> Any: ...
    def path_from_id(*args, **kwargs) -> Any: ...
    def path_from_module(*args, **kwargs) -> Any: ...
    def path_resolve(*args, **kwargs) -> Any: ...
    def pop(*args, **kwargs) -> Any: ...
    def property_overridable_library_set(*args, **kwargs) -> Any: ...
    def property_unset(*args, **kwargs) -> Any: ...
    def rna_ancestors(*args, **kwargs) -> Any: ...
    def type_recast(*args, **kwargs) -> Any: ...
    def values(*args, **kwargs) -> Any: ...

class ActionSlot:
    """
    Online Documentation:
    https://docs.blender.org/api/current/bpy_extras.anim_utils.html
    """
    def __init__(self, /, *args, **kwargs) -> Any: ...
    def as_pointer(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass_py(*args, **kwargs) -> Any: ...
    def driver_add(*args, **kwargs) -> Any: ...
    def driver_remove(*args, **kwargs) -> Any: ...
    def get(*args, **kwargs) -> Any: ...
    id_data: Any
    def id_properties_clear(*args, **kwargs) -> Any: ...
    def id_properties_ensure(*args, **kwargs) -> Any: ...
    def id_properties_ui(*args, **kwargs) -> Any: ...
    def is_property_hidden(*args, **kwargs) -> Any: ...
    def is_property_overridable_library(*args, **kwargs) -> Any: ...
    def is_property_readonly(*args, **kwargs) -> Any: ...
    def is_property_set(*args, **kwargs) -> Any: ...
    def items(*args, **kwargs) -> Any: ...
    def keyframe_delete(*args, **kwargs) -> Any: ...
    def keyframe_insert(*args, **kwargs) -> Any: ...
    def keys(*args, **kwargs) -> Any: ...
    def path_from_id(*args, **kwargs) -> Any: ...
    def path_from_module(*args, **kwargs) -> Any: ...
    def path_resolve(*args, **kwargs) -> Any: ...
    def pop(*args, **kwargs) -> Any: ...
    def property_overridable_library_set(*args, **kwargs) -> Any: ...
    def property_unset(*args, **kwargs) -> Any: ...
    def rna_ancestors(*args, **kwargs) -> Any: ...
    def type_recast(*args, **kwargs) -> Any: ...
    def values(*args, **kwargs) -> Any: ...

class AutoKeying:
    """Auto-keying support."""
    """
    Online Documentation:
    https://docs.blender.org/api/current/bpy_extras.anim_utils.html
    """
    def __init__(self, /, *args, **kwargs) -> Any: ...
    def active_keyingset(context: _bpy_types.Context) -> Any: ...
    def autokey_transformation(context: _bpy_types.Context, target: Union[_bpy_types.Object, _bpy_types.PoseBone]) -> Any: ...
    def autokeying_options(context: _bpy_types.Context) -> Any: ...
    def get_4d_rotlock(bone: _bpy_types.PoseBone) -> Any: ...
    def key_transformation(target: Union[_bpy_types.Object, _bpy_types.PoseBone], options: set[str]) -> Any: ...
    def key_transformation_via_keyingset(context: _bpy_types.Context, target: Union[_bpy_types.Object, _bpy_types.PoseBone], keyingset: bpy.types.KeyingSet) -> Any: ...
    def keyframe_channels(target: Union[_bpy_types.Object, _bpy_types.PoseBone], options: set[str], data_path: str, group: str, locks: Iterable[bool]) -> Any: ...
    def keying_options(context: _bpy_types.Context) -> Any: ...
    def keying_options_from_keyingset(context: _bpy_types.Context, keyingset: bpy.types.KeyingSet) -> Any: ...
    def keytype(the_keytype: str) -> Any: ...
    def options(*, keytype: str = '', use_loc: bool = True, use_rot: bool = True, use_scale: bool = True, force_autokey: bool = False) -> Any: ...

class BakeOptions:
    """BakeOptions(only_selected: bool, do_pose: bool, do_object: bool, do_visual_keying: bool, do_constraint_clear: bool, do_parents_clear: bool, do_clean: bool, do_location: bool, do_rotation: bool, do_scale: bool, do_bbone: bool, do_custom_props: bool)"""
    """
    Online Documentation:
    https://docs.blender.org/api/current/bpy_extras.anim_utils.html
    """
    def __init__(self, only_selected: bool, do_pose: bool, do_object: bool, do_visual_keying: bool, do_constraint_clear: bool, do_parents_clear: bool, do_clean: bool, do_location: bool, do_rotation: bool, do_scale: bool, do_bbone: bool, do_custom_props: bool) -> Any: ...

class Context:
    """
    Online Documentation:
    https://docs.blender.org/api/current/bpy_extras.anim_utils.html
    """
    def __init__(self, /, *args, **kwargs) -> Any: ...
    def as_pointer(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass_py(*args, **kwargs) -> Any: ...
    def copy(self) -> Any: ...
    def driver_add(*args, **kwargs) -> Any: ...
    def driver_remove(*args, **kwargs) -> Any: ...
    def get(*args, **kwargs) -> Any: ...
    id_data: Any
    def id_properties_clear(*args, **kwargs) -> Any: ...
    def id_properties_ensure(*args, **kwargs) -> Any: ...
    def id_properties_ui(*args, **kwargs) -> Any: ...
    def is_property_hidden(*args, **kwargs) -> Any: ...
    def is_property_overridable_library(*args, **kwargs) -> Any: ...
    def is_property_readonly(*args, **kwargs) -> Any: ...
    def is_property_set(*args, **kwargs) -> Any: ...
    def items(*args, **kwargs) -> Any: ...
    def keyframe_delete(*args, **kwargs) -> Any: ...
    def keyframe_insert(*args, **kwargs) -> Any: ...
    def keys(*args, **kwargs) -> Any: ...
    def path_from_id(*args, **kwargs) -> Any: ...
    def path_from_module(*args, **kwargs) -> Any: ...
    def path_resolve(self, path, coerce=True) -> Any: ...
    def pop(*args, **kwargs) -> Any: ...
    def property_overridable_library_set(*args, **kwargs) -> Any: ...
    def property_unset(*args, **kwargs) -> Any: ...
    def rna_ancestors(*args, **kwargs) -> Any: ...
    def temp_override(*args, **kwargs) -> Any: ...
    def type_recast(*args, **kwargs) -> Any: ...
    def values(*args, **kwargs) -> Any: ...
    # --- Injected Methods ---
    selected_objects: list[Any]
    active_object: Any
    view_layer: Any
    scene: Any
    screen: Any
    area: Any
    region: Any
    window: Any
    window_manager: Any
    preferences: Any
    def temp_override(self, window=None, area=None, region=None, **kwargs) -> Any:
        """
        **⚠️ Warning (Stub)**:
        This method is provided by the IDE plugin.
        """
        ...
    def __getattr__(self, name) -> Any:
        """
        **⚠️ Warning (Stub)**:
        This method is provided by the IDE plugin.
        """
        ...

FCurveKey: Any
Iterable: Any
Iterator: Any
class KeyframesCo:
    """
    A buffer for keyframe Co unpacked values per ``FCurveKey``. ``FCurveKeys`` are added using
    ``add_paths()``, Co values stored using extend_co_values(), then finally use
    ``insert_keyframes_into_*_action()`` for efficiently inserting keys into the F-curves.

    Users are limited to one Action Group per instance.
    """
    """
    Online Documentation:
    https://docs.blender.org/api/current/bpy_extras.anim_utils.html
    """
    def __init__(self) -> Any: ...
    def add_paths(self, rna_path: str, total_indices: int) -> Any: ...
    def extend_co_value(self, rna_path: str, frame: float, value: float) -> Any: ...
    def extend_co_values(self, rna_path: str, total_indices: int, frame: float, values: collections.abc.Sequence[float]) -> Any: ...
    def insert_keyframes_into_existing_action(self, lookup_fcurves: collections.abc.Mapping[tuple[str, int], bpy.types.FCurve], total_new_keys: int, channelbag: bpy.types.ActionChannelbag) -> Any: ...
    def insert_keyframes_into_new_action(self, total_new_keys: int, channelbag: bpy.types.ActionChannelbag, group_name: str) -> Any: ...
    keyframes_from_fcurve: Any

class KeyingSet:
    """
    Online Documentation:
    https://docs.blender.org/api/current/bpy_extras.anim_utils.html
    """
    def __init__(self, /, *args, **kwargs) -> Any: ...
    def as_pointer(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass_py(*args, **kwargs) -> Any: ...
    def driver_add(*args, **kwargs) -> Any: ...
    def driver_remove(*args, **kwargs) -> Any: ...
    def get(*args, **kwargs) -> Any: ...
    id_data: Any
    def id_properties_clear(*args, **kwargs) -> Any: ...
    def id_properties_ensure(*args, **kwargs) -> Any: ...
    def id_properties_ui(*args, **kwargs) -> Any: ...
    def is_property_hidden(*args, **kwargs) -> Any: ...
    def is_property_overridable_library(*args, **kwargs) -> Any: ...
    def is_property_readonly(*args, **kwargs) -> Any: ...
    def is_property_set(*args, **kwargs) -> Any: ...
    def items(*args, **kwargs) -> Any: ...
    def keyframe_delete(*args, **kwargs) -> Any: ...
    def keyframe_insert(*args, **kwargs) -> Any: ...
    def keys(*args, **kwargs) -> Any: ...
    def path_from_id(*args, **kwargs) -> Any: ...
    def path_from_module(*args, **kwargs) -> Any: ...
    def path_resolve(*args, **kwargs) -> Any: ...
    def pop(*args, **kwargs) -> Any: ...
    def property_overridable_library_set(*args, **kwargs) -> Any: ...
    def property_unset(*args, **kwargs) -> Any: ...
    def rna_ancestors(*args, **kwargs) -> Any: ...
    def type_recast(*args, **kwargs) -> Any: ...
    def values(*args, **kwargs) -> Any: ...

ListKeyframes: Any
class Mapping:
    """A Mapping is a generic container for associating key/value
    pairs.

    This class provides concrete generic implementations of all
    methods except for __getitem__, __iter__, and __len__.
    """
    """
    Online Documentation:
    https://docs.blender.org/api/current/bpy_extras.anim_utils.html
    """
    def __init__(self, /, *args, **kwargs) -> Any: ...
    def get(self, key, default=None) -> Any: ...
    def items(self) -> Any: ...
    def keys(self) -> Any: ...
    def values(self) -> Any: ...

class Object:
    """
    Online Documentation:
    https://docs.blender.org/api/current/bpy_extras.anim_utils.html
    """
    def __init__(self, /, *args, **kwargs) -> Any: ...
    def as_pointer(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass_py(*args, **kwargs) -> Any: ...
    children: Any
    children_recursive: Any
    def driver_add(*args, **kwargs) -> Any: ...
    def driver_remove(*args, **kwargs) -> Any: ...
    def evaluated_geometry(self) -> Any: ...
    def get(*args, **kwargs) -> Any: ...
    id_data: Any
    def id_properties_clear(*args, **kwargs) -> Any: ...
    def id_properties_ensure(*args, **kwargs) -> Any: ...
    def id_properties_ui(*args, **kwargs) -> Any: ...
    def is_property_hidden(*args, **kwargs) -> Any: ...
    def is_property_overridable_library(*args, **kwargs) -> Any: ...
    def is_property_readonly(*args, **kwargs) -> Any: ...
    def is_property_set(*args, **kwargs) -> Any: ...
    def items(*args, **kwargs) -> Any: ...
    def keyframe_delete(*args, **kwargs) -> Any: ...
    def keyframe_insert(*args, **kwargs) -> Any: ...
    def keys(*args, **kwargs) -> Any: ...
    def path_from_id(*args, **kwargs) -> Any: ...
    def path_from_module(*args, **kwargs) -> Any: ...
    def path_resolve(*args, **kwargs) -> Any: ...
    def pop(*args, **kwargs) -> Any: ...
    def property_overridable_library_set(*args, **kwargs) -> Any: ...
    def property_unset(*args, **kwargs) -> Any: ...
    def rna_ancestors(*args, **kwargs) -> Any: ...
    def type_recast(*args, **kwargs) -> Any: ...
    users_collection: Any
    users_scene: Any
    def values(*args, **kwargs) -> Any: ...
    # --- Injected Methods ---
    def select_set(self, state: bool) -> None: ...
    def select_get(self) -> bool: ...
    def hide_set(self, state: bool) -> None: ...
    def hide_get(self) -> bool: ...
    def hide_viewport_set(self, state: bool) -> None: ...
    def hide_render_set(self, state: bool) -> None: ...
    def temp_override(self, window=None, area=None, region=None, **kwargs) -> Any: ...

Optional: Any
class PoseBone:
    """
    Online Documentation:
    https://docs.blender.org/api/current/bpy_extras.anim_utils.html
    """
    def __init__(self, /, *args, **kwargs) -> Any: ...
    def as_pointer(*args, **kwargs) -> Any: ...
    basename: Any
    def bl_rna_get_subclass(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass_py(*args, **kwargs) -> Any: ...
    center: Any
    children: Any
    children_recursive: Any
    children_recursive_basename: Any
    def driver_add(*args, **kwargs) -> Any: ...
    def driver_remove(*args, **kwargs) -> Any: ...
    def get(*args, **kwargs) -> Any: ...
    id_data: Any
    def id_properties_clear(*args, **kwargs) -> Any: ...
    def id_properties_ensure(*args, **kwargs) -> Any: ...
    def id_properties_ui(*args, **kwargs) -> Any: ...
    def is_property_hidden(*args, **kwargs) -> Any: ...
    def is_property_overridable_library(*args, **kwargs) -> Any: ...
    def is_property_readonly(*args, **kwargs) -> Any: ...
    def is_property_set(*args, **kwargs) -> Any: ...
    def items(*args, **kwargs) -> Any: ...
    def keyframe_delete(*args, **kwargs) -> Any: ...
    def keyframe_insert(*args, **kwargs) -> Any: ...
    def keys(*args, **kwargs) -> Any: ...
    def parent_index(self, parent_test) -> Any: ...
    parent_recursive: Any
    def path_from_id(*args, **kwargs) -> Any: ...
    def path_from_module(*args, **kwargs) -> Any: ...
    def path_resolve(*args, **kwargs) -> Any: ...
    def pop(*args, **kwargs) -> Any: ...
    def property_overridable_library_set(*args, **kwargs) -> Any: ...
    def property_unset(*args, **kwargs) -> Any: ...
    def rna_ancestors(*args, **kwargs) -> Any: ...
    def translate(self, vec) -> Any: ...
    def type_recast(*args, **kwargs) -> Any: ...
    def values(*args, **kwargs) -> Any: ...
    vector: Any
    x_axis: Any
    y_axis: Any
    z_axis: Any

class Sequence:
    """All the operations on a read-only sequence.

    Concrete subclasses must override __new__ or __init__,
    __getitem__, and __len__.
    """
    """
    Online Documentation:
    https://docs.blender.org/api/current/bpy_extras.anim_utils.html
    """
    def __init__(self, /, *args, **kwargs) -> Any: ...
    def count(self, value) -> Any: ...
    def index(self, value, start=0, stop=None) -> Any: ...

Union: Any
def action_ensure_channelbag_for_slot(action: bpy.types.Action, slot: bpy.types.ActionSlot) -> Any:
    """
    Online Documentation:
    https://docs.blender.org/api/current/bpy_extras.anim_utils.html
    """
    ...

def action_get_channelbag_for_slot(action: bpy.types.Action | None, slot: bpy.types.ActionSlot | None) -> Any:
    """
    Online Documentation:
    https://docs.blender.org/api/current/bpy_extras.anim_utils.html
    """
    ...

def action_get_first_suitable_slot(action: bpy.types.Action | None, target_id_type: str) -> Any:
    """
    Online Documentation:
    https://docs.blender.org/api/current/bpy_extras.anim_utils.html
    """
    ...

def animdata_get_channelbag_for_assigned_slot(anim_data) -> Any:
    """
    Online Documentation:
    https://docs.blender.org/api/current/bpy_extras.anim_utils.html
    """
    ...

def bake_action(obj, *, action, frames, bake_options) -> Any:
    """
    Online Documentation:
    https://docs.blender.org/api/current/bpy_extras.anim_utils.html
    """
    ...

def bake_action_iter(obj, *, action, bake_options) -> Any:
    """
    Online Documentation:
    https://docs.blender.org/api/current/bpy_extras.anim_utils.html
    """
    ...

def bake_action_objects(object_action_pairs, *, frames, bake_options) -> Any:
    """
    Online Documentation:
    https://docs.blender.org/api/current/bpy_extras.anim_utils.html
    """
    ...

def bake_action_objects_iter(object_action_pairs, bake_options) -> Any:
    """
    Online Documentation:
    https://docs.blender.org/api/current/bpy_extras.anim_utils.html
    """
    ...

def dataclass(cls=None, /, *, init=True, repr=True, eq=True, order=False, unsafe_hash=False, frozen=False, match_args=True, kw_only=False, slots=False, weakref_slot=False) -> Any:
    """
    Online Documentation:
    https://docs.blender.org/api/current/bpy_extras.anim_utils.html
    """
    ...

def rna_idprop_value_to_python(value) -> Any:
    """
    Online Documentation:
    https://docs.blender.org/api/current/bpy_extras.anim_utils.html
    """
    ...
