# Blender Probe Generated Stub for Blender 5.0.1
# noinspection PyPep8Naming
# noinspection PyUnresolvedReferences
# noqa: N801
# pylint: disable=invalid-name


import sys
import typing
from typing import Any, Union, Callable, Iterator

class AddNodeMenu:
    def __init__(self, /, *args, **kwargs) -> Any: ...
    def append(draw_func) -> Any: ...
    def as_pointer(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass_py(*args, **kwargs) -> Any: ...
    def closure_zone(layout, label) -> Any: ...
    def color_mix_node(context, layout) -> Any: ...
    def draw_assets_for_catalog(layout, catalog_path) -> Any: ...
    def draw_collapsible(context, layout) -> Any: ...
    def draw_group_menu(context, layout) -> Any: ...
    def draw_menu(layout, path) -> Any: ...
    def draw_preset(self, _context) -> Any: ...
    def draw_root_assets(layout) -> Any: ...
    def driver_add(*args, **kwargs) -> Any: ...
    def driver_remove(*args, **kwargs) -> Any: ...
    def for_each_element_zone(layout, label) -> Any: ...
    def get(*args, **kwargs) -> Any: ...
    id_data: Any
    def id_properties_clear(*args, **kwargs) -> Any: ...
    def id_properties_ensure(*args, **kwargs) -> Any: ...
    def id_properties_ui(*args, **kwargs) -> Any: ...
    def is_extended() -> Any: ...
    def is_property_hidden(*args, **kwargs) -> Any: ...
    def is_property_overridable_library(*args, **kwargs) -> Any: ...
    def is_property_readonly(*args, **kwargs) -> Any: ...
    def is_property_set(*args, **kwargs) -> Any: ...
    def items(*args, **kwargs) -> Any: ...
    def keyframe_delete(*args, **kwargs) -> Any: ...
    def keyframe_insert(*args, **kwargs) -> Any: ...
    def keys(*args, **kwargs) -> Any: ...
    def new_empty_group(layout) -> Any: ...
    def node_operator(layout, node_type, *, label=None, poll=None, search_weight=0.0, translate=True) -> Any: ...
    def node_operator_with_outputs(context, layout, node_type, subnames, *, label=None, search_weight=0.0) -> Any: ...
    def node_operator_with_searchable_enum(context, layout, node_idname, property_name, search_weight=0.0) -> Any: ...
    def node_operator_with_searchable_enum_socket(context, layout, node_idname, socket_identifier, enum_names, search_weight=0.0) -> Any: ...
    def path_from_id(*args, **kwargs) -> Any: ...
    def path_from_module(*args, **kwargs) -> Any: ...
    def path_menu(self, searchpaths, operator, *, props_default=None, prop_filepath='filepath', filter_ext=None, filter_path=None, display_name=None, add_operator=None, add_operator_props=None, translate=True) -> Any: ...
    def path_resolve(*args, **kwargs) -> Any: ...
    def poll(context) -> Any: ...
    def pop(*args, **kwargs) -> Any: ...
    def prepend(draw_func) -> Any: ...
    def property_overridable_library_set(*args, **kwargs) -> Any: ...
    def property_unset(*args, **kwargs) -> Any: ...
    def remove(draw_func) -> Any: ...
    def repeat_zone(layout, label) -> Any: ...
    def rna_ancestors(*args, **kwargs) -> Any: ...
    def simulation_zone(layout, label) -> Any: ...
    def type_recast(*args, **kwargs) -> Any: ...
    def values(*args, **kwargs) -> Any: ...

class Menu:
    def __init__(self, /, *args, **kwargs) -> Any: ...
    def append(draw_func) -> Any: ...
    def as_pointer(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass_py(*args, **kwargs) -> Any: ...
    def draw_collapsible(context, layout) -> Any: ...
    def draw_preset(self, _context) -> Any: ...
    def driver_add(*args, **kwargs) -> Any: ...
    def driver_remove(*args, **kwargs) -> Any: ...
    def get(*args, **kwargs) -> Any: ...
    id_data: Any
    def id_properties_clear(*args, **kwargs) -> Any: ...
    def id_properties_ensure(*args, **kwargs) -> Any: ...
    def id_properties_ui(*args, **kwargs) -> Any: ...
    def is_extended() -> Any: ...
    def is_property_hidden(*args, **kwargs) -> Any: ...
    def is_property_overridable_library(*args, **kwargs) -> Any: ...
    def is_property_readonly(*args, **kwargs) -> Any: ...
    def is_property_set(*args, **kwargs) -> Any: ...
    def items(*args, **kwargs) -> Any: ...
    def keyframe_delete(*args, **kwargs) -> Any: ...
    def keyframe_insert(*args, **kwargs) -> Any: ...
    def keys(*args, **kwargs) -> Any: ...
    def path_from_id(*args, **kwargs) -> Any: ...
    def path_from_module(*args, **kwargs) -> Any: ...
    def path_menu(self, searchpaths, operator, *, props_default=None, prop_filepath='filepath', filter_ext=None, filter_path=None, display_name=None, add_operator=None, add_operator_props=None, translate=True) -> Any: ...
    def path_resolve(*args, **kwargs) -> Any: ...
    def pop(*args, **kwargs) -> Any: ...
    def prepend(draw_func) -> Any: ...
    def property_overridable_library_set(*args, **kwargs) -> Any: ...
    def property_unset(*args, **kwargs) -> Any: ...
    def remove(draw_func) -> Any: ...
    def rna_ancestors(*args, **kwargs) -> Any: ...
    def type_recast(*args, **kwargs) -> Any: ...
    def values(*args, **kwargs) -> Any: ...

class NODE_MT_group_base:
    def __init__(self, /, *args, **kwargs) -> Any: ...
    def append(draw_func) -> Any: ...
    def as_pointer(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass_py(*args, **kwargs) -> Any: ...
    def closure_zone(layout, label) -> Any: ...
    def color_mix_node(context, layout) -> Any: ...
    def draw(self, context) -> Any: ...
    def draw_collapsible(context, layout) -> Any: ...
    def draw_group_menu(context, layout) -> Any: ...
    def draw_menu(layout, path) -> Any: ...
    def draw_preset(self, _context) -> Any: ...
    def draw_root_assets(layout) -> Any: ...
    def driver_add(*args, **kwargs) -> Any: ...
    def driver_remove(*args, **kwargs) -> Any: ...
    def for_each_element_zone(layout, label) -> Any: ...
    def get(*args, **kwargs) -> Any: ...
    id_data: Any
    def id_properties_clear(*args, **kwargs) -> Any: ...
    def id_properties_ensure(*args, **kwargs) -> Any: ...
    def id_properties_ui(*args, **kwargs) -> Any: ...
    def is_extended() -> Any: ...
    def is_property_hidden(*args, **kwargs) -> Any: ...
    def is_property_overridable_library(*args, **kwargs) -> Any: ...
    def is_property_readonly(*args, **kwargs) -> Any: ...
    def is_property_set(*args, **kwargs) -> Any: ...
    def items(*args, **kwargs) -> Any: ...
    def keyframe_delete(*args, **kwargs) -> Any: ...
    def keyframe_insert(*args, **kwargs) -> Any: ...
    def keys(*args, **kwargs) -> Any: ...
    def new_empty_group(layout) -> Any: ...
    def node_operator(layout, node_type, *, label=None, poll=None, search_weight=0.0, translate=True) -> Any: ...
    def node_operator_with_outputs(context, layout, node_type, subnames, *, label=None, search_weight=0.0) -> Any: ...
    def node_operator_with_searchable_enum(context, layout, node_idname, property_name, search_weight=0.0) -> Any: ...
    def node_operator_with_searchable_enum_socket(context, layout, node_idname, socket_identifier, enum_names, search_weight=0.0) -> Any: ...
    def path_from_id(*args, **kwargs) -> Any: ...
    def path_from_module(*args, **kwargs) -> Any: ...
    def path_menu(self, searchpaths, operator, *, props_default=None, prop_filepath='filepath', filter_ext=None, filter_path=None, display_name=None, add_operator=None, add_operator_props=None, translate=True) -> Any: ...
    def path_resolve(*args, **kwargs) -> Any: ...
    def poll(context) -> Any: ...
    def pop(*args, **kwargs) -> Any: ...
    def prepend(draw_func) -> Any: ...
    def property_overridable_library_set(*args, **kwargs) -> Any: ...
    def property_unset(*args, **kwargs) -> Any: ...
    def remove(draw_func) -> Any: ...
    def repeat_zone(layout, label) -> Any: ...
    def rna_ancestors(*args, **kwargs) -> Any: ...
    def simulation_zone(layout, label) -> Any: ...
    def type_recast(*args, **kwargs) -> Any: ...
    def values(*args, **kwargs) -> Any: ...

class NODE_MT_layout_base:
    def __init__(self, /, *args, **kwargs) -> Any: ...
    def append(draw_func) -> Any: ...
    def as_pointer(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass_py(*args, **kwargs) -> Any: ...
    def closure_zone(layout, label) -> Any: ...
    def color_mix_node(context, layout) -> Any: ...
    def draw(self, _context) -> Any: ...
    def draw_collapsible(context, layout) -> Any: ...
    def draw_group_menu(context, layout) -> Any: ...
    def draw_menu(layout, path) -> Any: ...
    def draw_preset(self, _context) -> Any: ...
    def draw_root_assets(layout) -> Any: ...
    def driver_add(*args, **kwargs) -> Any: ...
    def driver_remove(*args, **kwargs) -> Any: ...
    def for_each_element_zone(layout, label) -> Any: ...
    def get(*args, **kwargs) -> Any: ...
    id_data: Any
    def id_properties_clear(*args, **kwargs) -> Any: ...
    def id_properties_ensure(*args, **kwargs) -> Any: ...
    def id_properties_ui(*args, **kwargs) -> Any: ...
    def is_extended() -> Any: ...
    def is_property_hidden(*args, **kwargs) -> Any: ...
    def is_property_overridable_library(*args, **kwargs) -> Any: ...
    def is_property_readonly(*args, **kwargs) -> Any: ...
    def is_property_set(*args, **kwargs) -> Any: ...
    def items(*args, **kwargs) -> Any: ...
    def keyframe_delete(*args, **kwargs) -> Any: ...
    def keyframe_insert(*args, **kwargs) -> Any: ...
    def keys(*args, **kwargs) -> Any: ...
    def new_empty_group(layout) -> Any: ...
    def node_operator(layout, node_type, *, label=None, poll=None, search_weight=0.0, translate=True) -> Any: ...
    def node_operator_with_outputs(context, layout, node_type, subnames, *, label=None, search_weight=0.0) -> Any: ...
    def node_operator_with_searchable_enum(context, layout, node_idname, property_name, search_weight=0.0) -> Any: ...
    def node_operator_with_searchable_enum_socket(context, layout, node_idname, socket_identifier, enum_names, search_weight=0.0) -> Any: ...
    def path_from_id(*args, **kwargs) -> Any: ...
    def path_from_module(*args, **kwargs) -> Any: ...
    def path_menu(self, searchpaths, operator, *, props_default=None, prop_filepath='filepath', filter_ext=None, filter_path=None, display_name=None, add_operator=None, add_operator_props=None, translate=True) -> Any: ...
    def path_resolve(*args, **kwargs) -> Any: ...
    def poll(context) -> Any: ...
    def pop(*args, **kwargs) -> Any: ...
    def prepend(draw_func) -> Any: ...
    def property_overridable_library_set(*args, **kwargs) -> Any: ...
    def property_unset(*args, **kwargs) -> Any: ...
    def remove(draw_func) -> Any: ...
    def repeat_zone(layout, label) -> Any: ...
    def rna_ancestors(*args, **kwargs) -> Any: ...
    def simulation_zone(layout, label) -> Any: ...
    def type_recast(*args, **kwargs) -> Any: ...
    def values(*args, **kwargs) -> Any: ...

class NodeMenu:
    """A baseclass defining the shared methods for AddNodeMenu and SwapNodeMenu."""
    def __init__(self, /, *args, **kwargs) -> Any: ...
    def append(draw_func) -> Any: ...
    def as_pointer(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass_py(*args, **kwargs) -> Any: ...
    def closure_zone(layout, label) -> Any: ...
    def color_mix_node(context, layout) -> Any: ...
    def draw_collapsible(context, layout) -> Any: ...
    def draw_group_menu(context, layout) -> Any: ...
    def draw_menu(layout, path) -> Any: ...
    def draw_preset(self, _context) -> Any: ...
    def draw_root_assets(layout) -> Any: ...
    def driver_add(*args, **kwargs) -> Any: ...
    def driver_remove(*args, **kwargs) -> Any: ...
    def for_each_element_zone(layout, label) -> Any: ...
    def get(*args, **kwargs) -> Any: ...
    id_data: Any
    def id_properties_clear(*args, **kwargs) -> Any: ...
    def id_properties_ensure(*args, **kwargs) -> Any: ...
    def id_properties_ui(*args, **kwargs) -> Any: ...
    def is_extended() -> Any: ...
    def is_property_hidden(*args, **kwargs) -> Any: ...
    def is_property_overridable_library(*args, **kwargs) -> Any: ...
    def is_property_readonly(*args, **kwargs) -> Any: ...
    def is_property_set(*args, **kwargs) -> Any: ...
    def items(*args, **kwargs) -> Any: ...
    def keyframe_delete(*args, **kwargs) -> Any: ...
    def keyframe_insert(*args, **kwargs) -> Any: ...
    def keys(*args, **kwargs) -> Any: ...
    def new_empty_group(layout) -> Any: ...
    def node_operator(layout, node_type, *, label=None, poll=None, search_weight=0.0, translate=True) -> Any: ...
    def node_operator_with_outputs(context, layout, node_type, subnames, *, label=None, search_weight=0.0) -> Any: ...
    def node_operator_with_searchable_enum(context, layout, node_idname, property_name, search_weight=0.0) -> Any: ...
    def node_operator_with_searchable_enum_socket(context, layout, node_idname, socket_identifier, enum_names, search_weight=0.0) -> Any: ...
    def path_from_id(*args, **kwargs) -> Any: ...
    def path_from_module(*args, **kwargs) -> Any: ...
    def path_menu(self, searchpaths, operator, *, props_default=None, prop_filepath='filepath', filter_ext=None, filter_path=None, display_name=None, add_operator=None, add_operator_props=None, translate=True) -> Any: ...
    def path_resolve(*args, **kwargs) -> Any: ...
    def poll(context) -> Any: ...
    def pop(*args, **kwargs) -> Any: ...
    def prepend(draw_func) -> Any: ...
    def property_overridable_library_set(*args, **kwargs) -> Any: ...
    def property_unset(*args, **kwargs) -> Any: ...
    def remove(draw_func) -> Any: ...
    def repeat_zone(layout, label) -> Any: ...
    def rna_ancestors(*args, **kwargs) -> Any: ...
    def simulation_zone(layout, label) -> Any: ...
    def type_recast(*args, **kwargs) -> Any: ...
    def values(*args, **kwargs) -> Any: ...

class SwapNodeMenu:
    def __init__(self, /, *args, **kwargs) -> Any: ...
    def append(draw_func) -> Any: ...
    def as_pointer(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass_py(*args, **kwargs) -> Any: ...
    def closure_zone(layout, label) -> Any: ...
    def color_mix_node(context, layout) -> Any: ...
    def draw_assets_for_catalog(layout, catalog_path) -> Any: ...
    def draw_collapsible(context, layout) -> Any: ...
    def draw_group_menu(context, layout) -> Any: ...
    def draw_menu(layout, path) -> Any: ...
    def draw_preset(self, _context) -> Any: ...
    def draw_root_assets(layout) -> Any: ...
    def driver_add(*args, **kwargs) -> Any: ...
    def driver_remove(*args, **kwargs) -> Any: ...
    def for_each_element_zone(layout, label) -> Any: ...
    def get(*args, **kwargs) -> Any: ...
    id_data: Any
    def id_properties_clear(*args, **kwargs) -> Any: ...
    def id_properties_ensure(*args, **kwargs) -> Any: ...
    def id_properties_ui(*args, **kwargs) -> Any: ...
    def is_extended() -> Any: ...
    def is_property_hidden(*args, **kwargs) -> Any: ...
    def is_property_overridable_library(*args, **kwargs) -> Any: ...
    def is_property_readonly(*args, **kwargs) -> Any: ...
    def is_property_set(*args, **kwargs) -> Any: ...
    def items(*args, **kwargs) -> Any: ...
    def keyframe_delete(*args, **kwargs) -> Any: ...
    def keyframe_insert(*args, **kwargs) -> Any: ...
    def keys(*args, **kwargs) -> Any: ...
    def new_empty_group(layout) -> Any: ...
    def node_operator(layout, node_type, *, label=None, poll=None, search_weight=0.0, translate=True) -> Any: ...
    def node_operator_with_outputs(context, layout, node_type, subnames, *, label=None, search_weight=0.0) -> Any: ...
    def node_operator_with_searchable_enum(context, layout, node_idname, property_name, search_weight=0.0) -> Any: ...
    def node_operator_with_searchable_enum_socket(context, layout, node_idname, socket_identifier, enum_names, search_weight=0.0) -> Any: ...
    def path_from_id(*args, **kwargs) -> Any: ...
    def path_from_module(*args, **kwargs) -> Any: ...
    def path_menu(self, searchpaths, operator, *, props_default=None, prop_filepath='filepath', filter_ext=None, filter_path=None, display_name=None, add_operator=None, add_operator_props=None, translate=True) -> Any: ...
    def path_resolve(*args, **kwargs) -> Any: ...
    def poll(context) -> Any: ...
    def pop(*args, **kwargs) -> Any: ...
    def prepend(draw_func) -> Any: ...
    def property_overridable_library_set(*args, **kwargs) -> Any: ...
    def property_unset(*args, **kwargs) -> Any: ...
    def remove(draw_func) -> Any: ...
    def repeat_zone(layout, label) -> Any: ...
    def rna_ancestors(*args, **kwargs) -> Any: ...
    def simulation_zone(layout, label) -> Any: ...
    def type_recast(*args, **kwargs) -> Any: ...
    def values(*args, **kwargs) -> Any: ...

add_base_pathing_dict: Any
def add_closure_zone(layout, label) -> Any:
    ...

def add_color_mix_node(context, layout) -> Any:
    ...

def add_empty_group(layout) -> Any:
    ...

def add_foreach_geometry_element_zone(layout, label) -> Any:
    ...

def add_node_type(layout, node_type, *, label=None, poll=None, search_weight=0.0, translate=True) -> Any:
    ...

def add_node_type_with_outputs(context, layout, node_type, subnames, *, label=None, search_weight=0.0) -> Any:
    ...

def add_node_type_with_searchable_enum(context, layout, node_idname, property_name, search_weight=0.0) -> Any:
    ...

def add_node_type_with_searchable_enum_socket(context, layout, node_idname, socket_identifier, enum_names, search_weight=0.0) -> Any:
    ...

def add_repeat_zone(layout, label) -> Any:
    ...

def add_simulation_zone(layout, label) -> Any:
    ...

classes: Any
def draw_node_group_add_menu(context, layout) -> Any:
    ...

def generate_menu(bl_idname: str, template: _bpy_types.Menu, layout_base: _bpy_types.Menu, pathing_dict: dict = None) -> Any:
    ...

def generate_menus(menus: dict, template: _bpy_types.Menu, base_dict: dict) -> Any:
    ...

def generate_pathing_dict(pathing_dict, menus) -> Any:
    ...

i18n_contexts: Any
def iface_(*args, **kwargs) -> Any:
    ...

swap_base_pathing_dict: Any