# Blender Probe Generated Stub for Blender 5.0.1
# noinspection PyPep8Naming
# noinspection PyUnresolvedReferences
# noqa: N801
# pylint: disable=invalid-name


import sys
import typing
from typing import Any, Union, Callable, Iterator

class DopesheetFilterPopoverBase:
    def __init__(self, /, *args, **kwargs) -> Any: ...
    def draw_generic_filters(context, layout) -> Any: ...
    def draw_search_filters(context, layout, generic_filters_only=False) -> Any: ...
    def draw_standard_filters(context, layout) -> Any: ...

class GRAPH_HT_header:
    def __init__(self, /, *args, **kwargs) -> Any: ...
    def append(draw_func) -> Any: ...
    def as_pointer(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass_py(*args, **kwargs) -> Any: ...
    def draw(self, context) -> Any: ...
    def driver_add(*args, **kwargs) -> Any: ...
    def driver_remove(*args, **kwargs) -> Any: ...
    def get(*args, **kwargs) -> Any: ...
    id_data: Any
    def id_properties_clear(*args, **kwargs) -> Any: ...
    def id_properties_ensure(*args, **kwargs) -> Any: ...
    def id_properties_ui(*args, **kwargs) -> Any: ...
    def is_extended() -> Any: ...
    def is_property_hidden(*args, **kwargs) -> Any: ...
    def is_property_overridable_library(*args, **kwargs) -> Any: ...
    def is_property_readonly(*args, **kwargs) -> Any: ...
    def is_property_set(*args, **kwargs) -> Any: ...
    def items(*args, **kwargs) -> Any: ...
    def keyframe_delete(*args, **kwargs) -> Any: ...
    def keyframe_insert(*args, **kwargs) -> Any: ...
    def keys(*args, **kwargs) -> Any: ...
    def path_from_id(*args, **kwargs) -> Any: ...
    def path_from_module(*args, **kwargs) -> Any: ...
    def path_resolve(*args, **kwargs) -> Any: ...
    def pop(*args, **kwargs) -> Any: ...
    def prepend(draw_func) -> Any: ...
    def property_overridable_library_set(*args, **kwargs) -> Any: ...
    def property_unset(*args, **kwargs) -> Any: ...
    def remove(draw_func) -> Any: ...
    def rna_ancestors(*args, **kwargs) -> Any: ...
    def type_recast(*args, **kwargs) -> Any: ...
    def values(*args, **kwargs) -> Any: ...

class GRAPH_HT_playback_controls:
    def __init__(self, /, *args, **kwargs) -> Any: ...
    def append(draw_func) -> Any: ...
    def as_pointer(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass_py(*args, **kwargs) -> Any: ...
    def draw(self, context) -> Any: ...
    def driver_add(*args, **kwargs) -> Any: ...
    def driver_remove(*args, **kwargs) -> Any: ...
    def get(*args, **kwargs) -> Any: ...
    id_data: Any
    def id_properties_clear(*args, **kwargs) -> Any: ...
    def id_properties_ensure(*args, **kwargs) -> Any: ...
    def id_properties_ui(*args, **kwargs) -> Any: ...
    def is_extended() -> Any: ...
    def is_property_hidden(*args, **kwargs) -> Any: ...
    def is_property_overridable_library(*args, **kwargs) -> Any: ...
    def is_property_readonly(*args, **kwargs) -> Any: ...
    def is_property_set(*args, **kwargs) -> Any: ...
    def items(*args, **kwargs) -> Any: ...
    def keyframe_delete(*args, **kwargs) -> Any: ...
    def keyframe_insert(*args, **kwargs) -> Any: ...
    def keys(*args, **kwargs) -> Any: ...
    def path_from_id(*args, **kwargs) -> Any: ...
    def path_from_module(*args, **kwargs) -> Any: ...
    def path_resolve(*args, **kwargs) -> Any: ...
    def pop(*args, **kwargs) -> Any: ...
    def prepend(draw_func) -> Any: ...
    def property_overridable_library_set(*args, **kwargs) -> Any: ...
    def property_unset(*args, **kwargs) -> Any: ...
    def remove(draw_func) -> Any: ...
    def rna_ancestors(*args, **kwargs) -> Any: ...
    def type_recast(*args, **kwargs) -> Any: ...
    def values(*args, **kwargs) -> Any: ...

class GRAPH_MT_channel:
    def __init__(self, /, *args, **kwargs) -> Any: ...
    def append(draw_func) -> Any: ...
    def as_pointer(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass_py(*args, **kwargs) -> Any: ...
    def draw(self, context) -> Any: ...
    def draw_collapsible(context, layout) -> Any: ...
    def draw_preset(self, _context) -> Any: ...
    def driver_add(*args, **kwargs) -> Any: ...
    def driver_remove(*args, **kwargs) -> Any: ...
    def get(*args, **kwargs) -> Any: ...
    id_data: Any
    def id_properties_clear(*args, **kwargs) -> Any: ...
    def id_properties_ensure(*args, **kwargs) -> Any: ...
    def id_properties_ui(*args, **kwargs) -> Any: ...
    def is_extended() -> Any: ...
    def is_property_hidden(*args, **kwargs) -> Any: ...
    def is_property_overridable_library(*args, **kwargs) -> Any: ...
    def is_property_readonly(*args, **kwargs) -> Any: ...
    def is_property_set(*args, **kwargs) -> Any: ...
    def items(*args, **kwargs) -> Any: ...
    def keyframe_delete(*args, **kwargs) -> Any: ...
    def keyframe_insert(*args, **kwargs) -> Any: ...
    def keys(*args, **kwargs) -> Any: ...
    def path_from_id(*args, **kwargs) -> Any: ...
    def path_from_module(*args, **kwargs) -> Any: ...
    def path_menu(self, searchpaths, operator, *, props_default=None, prop_filepath='filepath', filter_ext=None, filter_path=None, display_name=None, add_operator=None, add_operator_props=None, translate=True) -> Any: ...
    def path_resolve(*args, **kwargs) -> Any: ...
    def pop(*args, **kwargs) -> Any: ...
    def prepend(draw_func) -> Any: ...
    def property_overridable_library_set(*args, **kwargs) -> Any: ...
    def property_unset(*args, **kwargs) -> Any: ...
    def remove(draw_func) -> Any: ...
    def rna_ancestors(*args, **kwargs) -> Any: ...
    def type_recast(*args, **kwargs) -> Any: ...
    def values(*args, **kwargs) -> Any: ...

class GRAPH_MT_context_menu:
    def __init__(self, /, *args, **kwargs) -> Any: ...
    def append(draw_func) -> Any: ...
    def as_pointer(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass_py(*args, **kwargs) -> Any: ...
    def draw(self, _context) -> Any: ...
    def draw_collapsible(context, layout) -> Any: ...
    def draw_preset(self, _context) -> Any: ...
    def driver_add(*args, **kwargs) -> Any: ...
    def driver_remove(*args, **kwargs) -> Any: ...
    def get(*args, **kwargs) -> Any: ...
    id_data: Any
    def id_properties_clear(*args, **kwargs) -> Any: ...
    def id_properties_ensure(*args, **kwargs) -> Any: ...
    def id_properties_ui(*args, **kwargs) -> Any: ...
    def is_extended() -> Any: ...
    def is_property_hidden(*args, **kwargs) -> Any: ...
    def is_property_overridable_library(*args, **kwargs) -> Any: ...
    def is_property_readonly(*args, **kwargs) -> Any: ...
    def is_property_set(*args, **kwargs) -> Any: ...
    def items(*args, **kwargs) -> Any: ...
    def keyframe_delete(*args, **kwargs) -> Any: ...
    def keyframe_insert(*args, **kwargs) -> Any: ...
    def keys(*args, **kwargs) -> Any: ...
    def path_from_id(*args, **kwargs) -> Any: ...
    def path_from_module(*args, **kwargs) -> Any: ...
    def path_menu(self, searchpaths, operator, *, props_default=None, prop_filepath='filepath', filter_ext=None, filter_path=None, display_name=None, add_operator=None, add_operator_props=None, translate=True) -> Any: ...
    def path_resolve(*args, **kwargs) -> Any: ...
    def pop(*args, **kwargs) -> Any: ...
    def prepend(draw_func) -> Any: ...
    def property_overridable_library_set(*args, **kwargs) -> Any: ...
    def property_unset(*args, **kwargs) -> Any: ...
    def remove(draw_func) -> Any: ...
    def rna_ancestors(*args, **kwargs) -> Any: ...
    def type_recast(*args, **kwargs) -> Any: ...
    def values(*args, **kwargs) -> Any: ...

class GRAPH_MT_delete:
    def __init__(self, /, *args, **kwargs) -> Any: ...
    def append(draw_func) -> Any: ...
    def as_pointer(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass_py(*args, **kwargs) -> Any: ...
    def draw(self, _context) -> Any: ...
    def draw_collapsible(context, layout) -> Any: ...
    def draw_preset(self, _context) -> Any: ...
    def driver_add(*args, **kwargs) -> Any: ...
    def driver_remove(*args, **kwargs) -> Any: ...
    def get(*args, **kwargs) -> Any: ...
    id_data: Any
    def id_properties_clear(*args, **kwargs) -> Any: ...
    def id_properties_ensure(*args, **kwargs) -> Any: ...
    def id_properties_ui(*args, **kwargs) -> Any: ...
    def is_extended() -> Any: ...
    def is_property_hidden(*args, **kwargs) -> Any: ...
    def is_property_overridable_library(*args, **kwargs) -> Any: ...
    def is_property_readonly(*args, **kwargs) -> Any: ...
    def is_property_set(*args, **kwargs) -> Any: ...
    def items(*args, **kwargs) -> Any: ...
    def keyframe_delete(*args, **kwargs) -> Any: ...
    def keyframe_insert(*args, **kwargs) -> Any: ...
    def keys(*args, **kwargs) -> Any: ...
    def path_from_id(*args, **kwargs) -> Any: ...
    def path_from_module(*args, **kwargs) -> Any: ...
    def path_menu(self, searchpaths, operator, *, props_default=None, prop_filepath='filepath', filter_ext=None, filter_path=None, display_name=None, add_operator=None, add_operator_props=None, translate=True) -> Any: ...
    def path_resolve(*args, **kwargs) -> Any: ...
    def pop(*args, **kwargs) -> Any: ...
    def prepend(draw_func) -> Any: ...
    def property_overridable_library_set(*args, **kwargs) -> Any: ...
    def property_unset(*args, **kwargs) -> Any: ...
    def remove(draw_func) -> Any: ...
    def rna_ancestors(*args, **kwargs) -> Any: ...
    def type_recast(*args, **kwargs) -> Any: ...
    def values(*args, **kwargs) -> Any: ...

class GRAPH_MT_editor_menus:
    def __init__(self, /, *args, **kwargs) -> Any: ...
    def append(draw_func) -> Any: ...
    def as_pointer(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass_py(*args, **kwargs) -> Any: ...
    def draw(self, context) -> Any: ...
    def draw_collapsible(context, layout) -> Any: ...
    def draw_preset(self, _context) -> Any: ...
    def driver_add(*args, **kwargs) -> Any: ...
    def driver_remove(*args, **kwargs) -> Any: ...
    def get(*args, **kwargs) -> Any: ...
    id_data: Any
    def id_properties_clear(*args, **kwargs) -> Any: ...
    def id_properties_ensure(*args, **kwargs) -> Any: ...
    def id_properties_ui(*args, **kwargs) -> Any: ...
    def is_extended() -> Any: ...
    def is_property_hidden(*args, **kwargs) -> Any: ...
    def is_property_overridable_library(*args, **kwargs) -> Any: ...
    def is_property_readonly(*args, **kwargs) -> Any: ...
    def is_property_set(*args, **kwargs) -> Any: ...
    def items(*args, **kwargs) -> Any: ...
    def keyframe_delete(*args, **kwargs) -> Any: ...
    def keyframe_insert(*args, **kwargs) -> Any: ...
    def keys(*args, **kwargs) -> Any: ...
    def path_from_id(*args, **kwargs) -> Any: ...
    def path_from_module(*args, **kwargs) -> Any: ...
    def path_menu(self, searchpaths, operator, *, props_default=None, prop_filepath='filepath', filter_ext=None, filter_path=None, display_name=None, add_operator=None, add_operator_props=None, translate=True) -> Any: ...
    def path_resolve(*args, **kwargs) -> Any: ...
    def pop(*args, **kwargs) -> Any: ...
    def prepend(draw_func) -> Any: ...
    def property_overridable_library_set(*args, **kwargs) -> Any: ...
    def property_unset(*args, **kwargs) -> Any: ...
    def remove(draw_func) -> Any: ...
    def rna_ancestors(*args, **kwargs) -> Any: ...
    def type_recast(*args, **kwargs) -> Any: ...
    def values(*args, **kwargs) -> Any: ...

class GRAPH_MT_key:
    def __init__(self, /, *args, **kwargs) -> Any: ...
    def append(draw_func) -> Any: ...
    def as_pointer(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass_py(*args, **kwargs) -> Any: ...
    def draw(self, _context) -> Any: ...
    def draw_collapsible(context, layout) -> Any: ...
    def draw_preset(self, _context) -> Any: ...
    def driver_add(*args, **kwargs) -> Any: ...
    def driver_remove(*args, **kwargs) -> Any: ...
    def get(*args, **kwargs) -> Any: ...
    id_data: Any
    def id_properties_clear(*args, **kwargs) -> Any: ...
    def id_properties_ensure(*args, **kwargs) -> Any: ...
    def id_properties_ui(*args, **kwargs) -> Any: ...
    def is_extended() -> Any: ...
    def is_property_hidden(*args, **kwargs) -> Any: ...
    def is_property_overridable_library(*args, **kwargs) -> Any: ...
    def is_property_readonly(*args, **kwargs) -> Any: ...
    def is_property_set(*args, **kwargs) -> Any: ...
    def items(*args, **kwargs) -> Any: ...
    def keyframe_delete(*args, **kwargs) -> Any: ...
    def keyframe_insert(*args, **kwargs) -> Any: ...
    def keys(*args, **kwargs) -> Any: ...
    def path_from_id(*args, **kwargs) -> Any: ...
    def path_from_module(*args, **kwargs) -> Any: ...
    def path_menu(self, searchpaths, operator, *, props_default=None, prop_filepath='filepath', filter_ext=None, filter_path=None, display_name=None, add_operator=None, add_operator_props=None, translate=True) -> Any: ...
    def path_resolve(*args, **kwargs) -> Any: ...
    def pop(*args, **kwargs) -> Any: ...
    def prepend(draw_func) -> Any: ...
    def property_overridable_library_set(*args, **kwargs) -> Any: ...
    def property_unset(*args, **kwargs) -> Any: ...
    def remove(draw_func) -> Any: ...
    def rna_ancestors(*args, **kwargs) -> Any: ...
    def type_recast(*args, **kwargs) -> Any: ...
    def values(*args, **kwargs) -> Any: ...

class GRAPH_MT_key_blending:
    def __init__(self, /, *args, **kwargs) -> Any: ...
    def append(draw_func) -> Any: ...
    def as_pointer(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass_py(*args, **kwargs) -> Any: ...
    def draw(self, _context) -> Any: ...
    def draw_collapsible(context, layout) -> Any: ...
    def draw_preset(self, _context) -> Any: ...
    def driver_add(*args, **kwargs) -> Any: ...
    def driver_remove(*args, **kwargs) -> Any: ...
    def get(*args, **kwargs) -> Any: ...
    id_data: Any
    def id_properties_clear(*args, **kwargs) -> Any: ...
    def id_properties_ensure(*args, **kwargs) -> Any: ...
    def id_properties_ui(*args, **kwargs) -> Any: ...
    def is_extended() -> Any: ...
    def is_property_hidden(*args, **kwargs) -> Any: ...
    def is_property_overridable_library(*args, **kwargs) -> Any: ...
    def is_property_readonly(*args, **kwargs) -> Any: ...
    def is_property_set(*args, **kwargs) -> Any: ...
    def items(*args, **kwargs) -> Any: ...
    def keyframe_delete(*args, **kwargs) -> Any: ...
    def keyframe_insert(*args, **kwargs) -> Any: ...
    def keys(*args, **kwargs) -> Any: ...
    def path_from_id(*args, **kwargs) -> Any: ...
    def path_from_module(*args, **kwargs) -> Any: ...
    def path_menu(self, searchpaths, operator, *, props_default=None, prop_filepath='filepath', filter_ext=None, filter_path=None, display_name=None, add_operator=None, add_operator_props=None, translate=True) -> Any: ...
    def path_resolve(*args, **kwargs) -> Any: ...
    def pop(*args, **kwargs) -> Any: ...
    def prepend(draw_func) -> Any: ...
    def property_overridable_library_set(*args, **kwargs) -> Any: ...
    def property_unset(*args, **kwargs) -> Any: ...
    def remove(draw_func) -> Any: ...
    def rna_ancestors(*args, **kwargs) -> Any: ...
    def type_recast(*args, **kwargs) -> Any: ...
    def values(*args, **kwargs) -> Any: ...

class GRAPH_MT_key_density:
    def __init__(self, /, *args, **kwargs) -> Any: ...
    def append(draw_func) -> Any: ...
    def as_pointer(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass_py(*args, **kwargs) -> Any: ...
    def draw(self, _context) -> Any: ...
    def draw_collapsible(context, layout) -> Any: ...
    def draw_preset(self, _context) -> Any: ...
    def driver_add(*args, **kwargs) -> Any: ...
    def driver_remove(*args, **kwargs) -> Any: ...
    def get(*args, **kwargs) -> Any: ...
    id_data: Any
    def id_properties_clear(*args, **kwargs) -> Any: ...
    def id_properties_ensure(*args, **kwargs) -> Any: ...
    def id_properties_ui(*args, **kwargs) -> Any: ...
    def is_extended() -> Any: ...
    def is_property_hidden(*args, **kwargs) -> Any: ...
    def is_property_overridable_library(*args, **kwargs) -> Any: ...
    def is_property_readonly(*args, **kwargs) -> Any: ...
    def is_property_set(*args, **kwargs) -> Any: ...
    def items(*args, **kwargs) -> Any: ...
    def keyframe_delete(*args, **kwargs) -> Any: ...
    def keyframe_insert(*args, **kwargs) -> Any: ...
    def keys(*args, **kwargs) -> Any: ...
    def path_from_id(*args, **kwargs) -> Any: ...
    def path_from_module(*args, **kwargs) -> Any: ...
    def path_menu(self, searchpaths, operator, *, props_default=None, prop_filepath='filepath', filter_ext=None, filter_path=None, display_name=None, add_operator=None, add_operator_props=None, translate=True) -> Any: ...
    def path_resolve(*args, **kwargs) -> Any: ...
    def pop(*args, **kwargs) -> Any: ...
    def prepend(draw_func) -> Any: ...
    def property_overridable_library_set(*args, **kwargs) -> Any: ...
    def property_unset(*args, **kwargs) -> Any: ...
    def remove(draw_func) -> Any: ...
    def rna_ancestors(*args, **kwargs) -> Any: ...
    def type_recast(*args, **kwargs) -> Any: ...
    def values(*args, **kwargs) -> Any: ...

class GRAPH_MT_key_smoothing:
    def __init__(self, /, *args, **kwargs) -> Any: ...
    def append(draw_func) -> Any: ...
    def as_pointer(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass_py(*args, **kwargs) -> Any: ...
    def draw(self, _context) -> Any: ...
    def draw_collapsible(context, layout) -> Any: ...
    def draw_preset(self, _context) -> Any: ...
    def driver_add(*args, **kwargs) -> Any: ...
    def driver_remove(*args, **kwargs) -> Any: ...
    def get(*args, **kwargs) -> Any: ...
    id_data: Any
    def id_properties_clear(*args, **kwargs) -> Any: ...
    def id_properties_ensure(*args, **kwargs) -> Any: ...
    def id_properties_ui(*args, **kwargs) -> Any: ...
    def is_extended() -> Any: ...
    def is_property_hidden(*args, **kwargs) -> Any: ...
    def is_property_overridable_library(*args, **kwargs) -> Any: ...
    def is_property_readonly(*args, **kwargs) -> Any: ...
    def is_property_set(*args, **kwargs) -> Any: ...
    def items(*args, **kwargs) -> Any: ...
    def keyframe_delete(*args, **kwargs) -> Any: ...
    def keyframe_insert(*args, **kwargs) -> Any: ...
    def keys(*args, **kwargs) -> Any: ...
    def path_from_id(*args, **kwargs) -> Any: ...
    def path_from_module(*args, **kwargs) -> Any: ...
    def path_menu(self, searchpaths, operator, *, props_default=None, prop_filepath='filepath', filter_ext=None, filter_path=None, display_name=None, add_operator=None, add_operator_props=None, translate=True) -> Any: ...
    def path_resolve(*args, **kwargs) -> Any: ...
    def pop(*args, **kwargs) -> Any: ...
    def prepend(draw_func) -> Any: ...
    def property_overridable_library_set(*args, **kwargs) -> Any: ...
    def property_unset(*args, **kwargs) -> Any: ...
    def remove(draw_func) -> Any: ...
    def rna_ancestors(*args, **kwargs) -> Any: ...
    def type_recast(*args, **kwargs) -> Any: ...
    def values(*args, **kwargs) -> Any: ...

class GRAPH_MT_key_snap:
    def __init__(self, /, *args, **kwargs) -> Any: ...
    def append(draw_func) -> Any: ...
    def as_pointer(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass_py(*args, **kwargs) -> Any: ...
    def draw(self, _context) -> Any: ...
    def draw_collapsible(context, layout) -> Any: ...
    def draw_preset(self, _context) -> Any: ...
    def driver_add(*args, **kwargs) -> Any: ...
    def driver_remove(*args, **kwargs) -> Any: ...
    def get(*args, **kwargs) -> Any: ...
    id_data: Any
    def id_properties_clear(*args, **kwargs) -> Any: ...
    def id_properties_ensure(*args, **kwargs) -> Any: ...
    def id_properties_ui(*args, **kwargs) -> Any: ...
    def is_extended() -> Any: ...
    def is_property_hidden(*args, **kwargs) -> Any: ...
    def is_property_overridable_library(*args, **kwargs) -> Any: ...
    def is_property_readonly(*args, **kwargs) -> Any: ...
    def is_property_set(*args, **kwargs) -> Any: ...
    def items(*args, **kwargs) -> Any: ...
    def keyframe_delete(*args, **kwargs) -> Any: ...
    def keyframe_insert(*args, **kwargs) -> Any: ...
    def keys(*args, **kwargs) -> Any: ...
    def path_from_id(*args, **kwargs) -> Any: ...
    def path_from_module(*args, **kwargs) -> Any: ...
    def path_menu(self, searchpaths, operator, *, props_default=None, prop_filepath='filepath', filter_ext=None, filter_path=None, display_name=None, add_operator=None, add_operator_props=None, translate=True) -> Any: ...
    def path_resolve(*args, **kwargs) -> Any: ...
    def pop(*args, **kwargs) -> Any: ...
    def prepend(draw_func) -> Any: ...
    def property_overridable_library_set(*args, **kwargs) -> Any: ...
    def property_unset(*args, **kwargs) -> Any: ...
    def remove(draw_func) -> Any: ...
    def rna_ancestors(*args, **kwargs) -> Any: ...
    def type_recast(*args, **kwargs) -> Any: ...
    def values(*args, **kwargs) -> Any: ...

class GRAPH_MT_key_transform:
    def __init__(self, /, *args, **kwargs) -> Any: ...
    def append(draw_func) -> Any: ...
    def as_pointer(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass_py(*args, **kwargs) -> Any: ...
    def draw(self, _context) -> Any: ...
    def draw_collapsible(context, layout) -> Any: ...
    def draw_preset(self, _context) -> Any: ...
    def driver_add(*args, **kwargs) -> Any: ...
    def driver_remove(*args, **kwargs) -> Any: ...
    def get(*args, **kwargs) -> Any: ...
    id_data: Any
    def id_properties_clear(*args, **kwargs) -> Any: ...
    def id_properties_ensure(*args, **kwargs) -> Any: ...
    def id_properties_ui(*args, **kwargs) -> Any: ...
    def is_extended() -> Any: ...
    def is_property_hidden(*args, **kwargs) -> Any: ...
    def is_property_overridable_library(*args, **kwargs) -> Any: ...
    def is_property_readonly(*args, **kwargs) -> Any: ...
    def is_property_set(*args, **kwargs) -> Any: ...
    def items(*args, **kwargs) -> Any: ...
    def keyframe_delete(*args, **kwargs) -> Any: ...
    def keyframe_insert(*args, **kwargs) -> Any: ...
    def keys(*args, **kwargs) -> Any: ...
    def path_from_id(*args, **kwargs) -> Any: ...
    def path_from_module(*args, **kwargs) -> Any: ...
    def path_menu(self, searchpaths, operator, *, props_default=None, prop_filepath='filepath', filter_ext=None, filter_path=None, display_name=None, add_operator=None, add_operator_props=None, translate=True) -> Any: ...
    def path_resolve(*args, **kwargs) -> Any: ...
    def pop(*args, **kwargs) -> Any: ...
    def prepend(draw_func) -> Any: ...
    def property_overridable_library_set(*args, **kwargs) -> Any: ...
    def property_unset(*args, **kwargs) -> Any: ...
    def remove(draw_func) -> Any: ...
    def rna_ancestors(*args, **kwargs) -> Any: ...
    def type_recast(*args, **kwargs) -> Any: ...
    def values(*args, **kwargs) -> Any: ...

class GRAPH_MT_marker:
    def __init__(self, /, *args, **kwargs) -> Any: ...
    def append(draw_func) -> Any: ...
    def as_pointer(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass_py(*args, **kwargs) -> Any: ...
    def draw(self, context) -> Any: ...
    def draw_collapsible(context, layout) -> Any: ...
    def draw_preset(self, _context) -> Any: ...
    def driver_add(*args, **kwargs) -> Any: ...
    def driver_remove(*args, **kwargs) -> Any: ...
    def get(*args, **kwargs) -> Any: ...
    id_data: Any
    def id_properties_clear(*args, **kwargs) -> Any: ...
    def id_properties_ensure(*args, **kwargs) -> Any: ...
    def id_properties_ui(*args, **kwargs) -> Any: ...
    def is_extended() -> Any: ...
    def is_property_hidden(*args, **kwargs) -> Any: ...
    def is_property_overridable_library(*args, **kwargs) -> Any: ...
    def is_property_readonly(*args, **kwargs) -> Any: ...
    def is_property_set(*args, **kwargs) -> Any: ...
    def items(*args, **kwargs) -> Any: ...
    def keyframe_delete(*args, **kwargs) -> Any: ...
    def keyframe_insert(*args, **kwargs) -> Any: ...
    def keys(*args, **kwargs) -> Any: ...
    def path_from_id(*args, **kwargs) -> Any: ...
    def path_from_module(*args, **kwargs) -> Any: ...
    def path_menu(self, searchpaths, operator, *, props_default=None, prop_filepath='filepath', filter_ext=None, filter_path=None, display_name=None, add_operator=None, add_operator_props=None, translate=True) -> Any: ...
    def path_resolve(*args, **kwargs) -> Any: ...
    def pop(*args, **kwargs) -> Any: ...
    def prepend(draw_func) -> Any: ...
    def property_overridable_library_set(*args, **kwargs) -> Any: ...
    def property_unset(*args, **kwargs) -> Any: ...
    def remove(draw_func) -> Any: ...
    def rna_ancestors(*args, **kwargs) -> Any: ...
    def type_recast(*args, **kwargs) -> Any: ...
    def values(*args, **kwargs) -> Any: ...

class GRAPH_MT_pivot_pie:
    def __init__(self, /, *args, **kwargs) -> Any: ...
    def append(draw_func) -> Any: ...
    def as_pointer(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass_py(*args, **kwargs) -> Any: ...
    def draw(self, context) -> Any: ...
    def draw_collapsible(context, layout) -> Any: ...
    def draw_preset(self, _context) -> Any: ...
    def driver_add(*args, **kwargs) -> Any: ...
    def driver_remove(*args, **kwargs) -> Any: ...
    def get(*args, **kwargs) -> Any: ...
    id_data: Any
    def id_properties_clear(*args, **kwargs) -> Any: ...
    def id_properties_ensure(*args, **kwargs) -> Any: ...
    def id_properties_ui(*args, **kwargs) -> Any: ...
    def is_extended() -> Any: ...
    def is_property_hidden(*args, **kwargs) -> Any: ...
    def is_property_overridable_library(*args, **kwargs) -> Any: ...
    def is_property_readonly(*args, **kwargs) -> Any: ...
    def is_property_set(*args, **kwargs) -> Any: ...
    def items(*args, **kwargs) -> Any: ...
    def keyframe_delete(*args, **kwargs) -> Any: ...
    def keyframe_insert(*args, **kwargs) -> Any: ...
    def keys(*args, **kwargs) -> Any: ...
    def path_from_id(*args, **kwargs) -> Any: ...
    def path_from_module(*args, **kwargs) -> Any: ...
    def path_menu(self, searchpaths, operator, *, props_default=None, prop_filepath='filepath', filter_ext=None, filter_path=None, display_name=None, add_operator=None, add_operator_props=None, translate=True) -> Any: ...
    def path_resolve(*args, **kwargs) -> Any: ...
    def pop(*args, **kwargs) -> Any: ...
    def prepend(draw_func) -> Any: ...
    def property_overridable_library_set(*args, **kwargs) -> Any: ...
    def property_unset(*args, **kwargs) -> Any: ...
    def remove(draw_func) -> Any: ...
    def rna_ancestors(*args, **kwargs) -> Any: ...
    def type_recast(*args, **kwargs) -> Any: ...
    def values(*args, **kwargs) -> Any: ...

class GRAPH_MT_select:
    def __init__(self, /, *args, **kwargs) -> Any: ...
    def append(draw_func) -> Any: ...
    def as_pointer(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass_py(*args, **kwargs) -> Any: ...
    def draw(self, _context) -> Any: ...
    def draw_collapsible(context, layout) -> Any: ...
    def draw_preset(self, _context) -> Any: ...
    def driver_add(*args, **kwargs) -> Any: ...
    def driver_remove(*args, **kwargs) -> Any: ...
    def get(*args, **kwargs) -> Any: ...
    id_data: Any
    def id_properties_clear(*args, **kwargs) -> Any: ...
    def id_properties_ensure(*args, **kwargs) -> Any: ...
    def id_properties_ui(*args, **kwargs) -> Any: ...
    def is_extended() -> Any: ...
    def is_property_hidden(*args, **kwargs) -> Any: ...
    def is_property_overridable_library(*args, **kwargs) -> Any: ...
    def is_property_readonly(*args, **kwargs) -> Any: ...
    def is_property_set(*args, **kwargs) -> Any: ...
    def items(*args, **kwargs) -> Any: ...
    def keyframe_delete(*args, **kwargs) -> Any: ...
    def keyframe_insert(*args, **kwargs) -> Any: ...
    def keys(*args, **kwargs) -> Any: ...
    def path_from_id(*args, **kwargs) -> Any: ...
    def path_from_module(*args, **kwargs) -> Any: ...
    def path_menu(self, searchpaths, operator, *, props_default=None, prop_filepath='filepath', filter_ext=None, filter_path=None, display_name=None, add_operator=None, add_operator_props=None, translate=True) -> Any: ...
    def path_resolve(*args, **kwargs) -> Any: ...
    def pop(*args, **kwargs) -> Any: ...
    def prepend(draw_func) -> Any: ...
    def property_overridable_library_set(*args, **kwargs) -> Any: ...
    def property_unset(*args, **kwargs) -> Any: ...
    def remove(draw_func) -> Any: ...
    def rna_ancestors(*args, **kwargs) -> Any: ...
    def type_recast(*args, **kwargs) -> Any: ...
    def values(*args, **kwargs) -> Any: ...

class GRAPH_MT_snap_pie:
    def __init__(self, /, *args, **kwargs) -> Any: ...
    def append(draw_func) -> Any: ...
    def as_pointer(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass_py(*args, **kwargs) -> Any: ...
    def draw(self, _context) -> Any: ...
    def draw_collapsible(context, layout) -> Any: ...
    def draw_preset(self, _context) -> Any: ...
    def driver_add(*args, **kwargs) -> Any: ...
    def driver_remove(*args, **kwargs) -> Any: ...
    def get(*args, **kwargs) -> Any: ...
    id_data: Any
    def id_properties_clear(*args, **kwargs) -> Any: ...
    def id_properties_ensure(*args, **kwargs) -> Any: ...
    def id_properties_ui(*args, **kwargs) -> Any: ...
    def is_extended() -> Any: ...
    def is_property_hidden(*args, **kwargs) -> Any: ...
    def is_property_overridable_library(*args, **kwargs) -> Any: ...
    def is_property_readonly(*args, **kwargs) -> Any: ...
    def is_property_set(*args, **kwargs) -> Any: ...
    def items(*args, **kwargs) -> Any: ...
    def keyframe_delete(*args, **kwargs) -> Any: ...
    def keyframe_insert(*args, **kwargs) -> Any: ...
    def keys(*args, **kwargs) -> Any: ...
    def path_from_id(*args, **kwargs) -> Any: ...
    def path_from_module(*args, **kwargs) -> Any: ...
    def path_menu(self, searchpaths, operator, *, props_default=None, prop_filepath='filepath', filter_ext=None, filter_path=None, display_name=None, add_operator=None, add_operator_props=None, translate=True) -> Any: ...
    def path_resolve(*args, **kwargs) -> Any: ...
    def pop(*args, **kwargs) -> Any: ...
    def prepend(draw_func) -> Any: ...
    def property_overridable_library_set(*args, **kwargs) -> Any: ...
    def property_unset(*args, **kwargs) -> Any: ...
    def remove(draw_func) -> Any: ...
    def rna_ancestors(*args, **kwargs) -> Any: ...
    def type_recast(*args, **kwargs) -> Any: ...
    def values(*args, **kwargs) -> Any: ...

class GRAPH_MT_view:
    def __init__(self, /, *args, **kwargs) -> Any: ...
    def append(draw_func) -> Any: ...
    def as_pointer(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass_py(*args, **kwargs) -> Any: ...
    def draw(self, context) -> Any: ...
    def draw_collapsible(context, layout) -> Any: ...
    def draw_preset(self, _context) -> Any: ...
    def driver_add(*args, **kwargs) -> Any: ...
    def driver_remove(*args, **kwargs) -> Any: ...
    def get(*args, **kwargs) -> Any: ...
    id_data: Any
    def id_properties_clear(*args, **kwargs) -> Any: ...
    def id_properties_ensure(*args, **kwargs) -> Any: ...
    def id_properties_ui(*args, **kwargs) -> Any: ...
    def is_extended() -> Any: ...
    def is_property_hidden(*args, **kwargs) -> Any: ...
    def is_property_overridable_library(*args, **kwargs) -> Any: ...
    def is_property_readonly(*args, **kwargs) -> Any: ...
    def is_property_set(*args, **kwargs) -> Any: ...
    def items(*args, **kwargs) -> Any: ...
    def keyframe_delete(*args, **kwargs) -> Any: ...
    def keyframe_insert(*args, **kwargs) -> Any: ...
    def keys(*args, **kwargs) -> Any: ...
    def path_from_id(*args, **kwargs) -> Any: ...
    def path_from_module(*args, **kwargs) -> Any: ...
    def path_menu(self, searchpaths, operator, *, props_default=None, prop_filepath='filepath', filter_ext=None, filter_path=None, display_name=None, add_operator=None, add_operator_props=None, translate=True) -> Any: ...
    def path_resolve(*args, **kwargs) -> Any: ...
    def pop(*args, **kwargs) -> Any: ...
    def prepend(draw_func) -> Any: ...
    def property_overridable_library_set(*args, **kwargs) -> Any: ...
    def property_unset(*args, **kwargs) -> Any: ...
    def remove(draw_func) -> Any: ...
    def rna_ancestors(*args, **kwargs) -> Any: ...
    def type_recast(*args, **kwargs) -> Any: ...
    def values(*args, **kwargs) -> Any: ...

class GRAPH_MT_view_pie:
    def __init__(self, /, *args, **kwargs) -> Any: ...
    def append(draw_func) -> Any: ...
    def as_pointer(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass_py(*args, **kwargs) -> Any: ...
    def draw(self, context) -> Any: ...
    def draw_collapsible(context, layout) -> Any: ...
    def draw_preset(self, _context) -> Any: ...
    def driver_add(*args, **kwargs) -> Any: ...
    def driver_remove(*args, **kwargs) -> Any: ...
    def get(*args, **kwargs) -> Any: ...
    id_data: Any
    def id_properties_clear(*args, **kwargs) -> Any: ...
    def id_properties_ensure(*args, **kwargs) -> Any: ...
    def id_properties_ui(*args, **kwargs) -> Any: ...
    def is_extended() -> Any: ...
    def is_property_hidden(*args, **kwargs) -> Any: ...
    def is_property_overridable_library(*args, **kwargs) -> Any: ...
    def is_property_readonly(*args, **kwargs) -> Any: ...
    def is_property_set(*args, **kwargs) -> Any: ...
    def items(*args, **kwargs) -> Any: ...
    def keyframe_delete(*args, **kwargs) -> Any: ...
    def keyframe_insert(*args, **kwargs) -> Any: ...
    def keys(*args, **kwargs) -> Any: ...
    def path_from_id(*args, **kwargs) -> Any: ...
    def path_from_module(*args, **kwargs) -> Any: ...
    def path_menu(self, searchpaths, operator, *, props_default=None, prop_filepath='filepath', filter_ext=None, filter_path=None, display_name=None, add_operator=None, add_operator_props=None, translate=True) -> Any: ...
    def path_resolve(*args, **kwargs) -> Any: ...
    def pop(*args, **kwargs) -> Any: ...
    def prepend(draw_func) -> Any: ...
    def property_overridable_library_set(*args, **kwargs) -> Any: ...
    def property_unset(*args, **kwargs) -> Any: ...
    def remove(draw_func) -> Any: ...
    def rna_ancestors(*args, **kwargs) -> Any: ...
    def type_recast(*args, **kwargs) -> Any: ...
    def values(*args, **kwargs) -> Any: ...

class GRAPH_PT_driver_snapping:
    def __init__(self, /, *args, **kwargs) -> Any: ...
    def append(draw_func) -> Any: ...
    def as_pointer(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass_py(*args, **kwargs) -> Any: ...
    def draw(self, context) -> Any: ...
    def driver_add(*args, **kwargs) -> Any: ...
    def driver_remove(*args, **kwargs) -> Any: ...
    def get(*args, **kwargs) -> Any: ...
    id_data: Any
    def id_properties_clear(*args, **kwargs) -> Any: ...
    def id_properties_ensure(*args, **kwargs) -> Any: ...
    def id_properties_ui(*args, **kwargs) -> Any: ...
    def is_extended() -> Any: ...
    def is_property_hidden(*args, **kwargs) -> Any: ...
    def is_property_overridable_library(*args, **kwargs) -> Any: ...
    def is_property_readonly(*args, **kwargs) -> Any: ...
    def is_property_set(*args, **kwargs) -> Any: ...
    def items(*args, **kwargs) -> Any: ...
    def keyframe_delete(*args, **kwargs) -> Any: ...
    def keyframe_insert(*args, **kwargs) -> Any: ...
    def keys(*args, **kwargs) -> Any: ...
    def path_from_id(*args, **kwargs) -> Any: ...
    def path_from_module(*args, **kwargs) -> Any: ...
    def path_resolve(*args, **kwargs) -> Any: ...
    def pop(*args, **kwargs) -> Any: ...
    def prepend(draw_func) -> Any: ...
    def property_overridable_library_set(*args, **kwargs) -> Any: ...
    def property_unset(*args, **kwargs) -> Any: ...
    def remove(draw_func) -> Any: ...
    def rna_ancestors(*args, **kwargs) -> Any: ...
    def type_recast(*args, **kwargs) -> Any: ...
    def values(*args, **kwargs) -> Any: ...

class GRAPH_PT_filters:
    def __init__(self, /, *args, **kwargs) -> Any: ...
    def append(draw_func) -> Any: ...
    def as_pointer(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass_py(*args, **kwargs) -> Any: ...
    def draw(self, context) -> Any: ...
    def draw_generic_filters(context, layout) -> Any: ...
    def draw_search_filters(context, layout, generic_filters_only=False) -> Any: ...
    def draw_standard_filters(context, layout) -> Any: ...
    def driver_add(*args, **kwargs) -> Any: ...
    def driver_remove(*args, **kwargs) -> Any: ...
    def get(*args, **kwargs) -> Any: ...
    id_data: Any
    def id_properties_clear(*args, **kwargs) -> Any: ...
    def id_properties_ensure(*args, **kwargs) -> Any: ...
    def id_properties_ui(*args, **kwargs) -> Any: ...
    def is_extended() -> Any: ...
    def is_property_hidden(*args, **kwargs) -> Any: ...
    def is_property_overridable_library(*args, **kwargs) -> Any: ...
    def is_property_readonly(*args, **kwargs) -> Any: ...
    def is_property_set(*args, **kwargs) -> Any: ...
    def items(*args, **kwargs) -> Any: ...
    def keyframe_delete(*args, **kwargs) -> Any: ...
    def keyframe_insert(*args, **kwargs) -> Any: ...
    def keys(*args, **kwargs) -> Any: ...
    def path_from_id(*args, **kwargs) -> Any: ...
    def path_from_module(*args, **kwargs) -> Any: ...
    def path_resolve(*args, **kwargs) -> Any: ...
    def pop(*args, **kwargs) -> Any: ...
    def prepend(draw_func) -> Any: ...
    def property_overridable_library_set(*args, **kwargs) -> Any: ...
    def property_unset(*args, **kwargs) -> Any: ...
    def remove(draw_func) -> Any: ...
    def rna_ancestors(*args, **kwargs) -> Any: ...
    def type_recast(*args, **kwargs) -> Any: ...
    def values(*args, **kwargs) -> Any: ...

class GRAPH_PT_proportional_edit:
    def __init__(self, /, *args, **kwargs) -> Any: ...
    def append(draw_func) -> Any: ...
    def as_pointer(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass_py(*args, **kwargs) -> Any: ...
    def draw(self, context) -> Any: ...
    def driver_add(*args, **kwargs) -> Any: ...
    def driver_remove(*args, **kwargs) -> Any: ...
    def get(*args, **kwargs) -> Any: ...
    id_data: Any
    def id_properties_clear(*args, **kwargs) -> Any: ...
    def id_properties_ensure(*args, **kwargs) -> Any: ...
    def id_properties_ui(*args, **kwargs) -> Any: ...
    def is_extended() -> Any: ...
    def is_property_hidden(*args, **kwargs) -> Any: ...
    def is_property_overridable_library(*args, **kwargs) -> Any: ...
    def is_property_readonly(*args, **kwargs) -> Any: ...
    def is_property_set(*args, **kwargs) -> Any: ...
    def items(*args, **kwargs) -> Any: ...
    def keyframe_delete(*args, **kwargs) -> Any: ...
    def keyframe_insert(*args, **kwargs) -> Any: ...
    def keys(*args, **kwargs) -> Any: ...
    def path_from_id(*args, **kwargs) -> Any: ...
    def path_from_module(*args, **kwargs) -> Any: ...
    def path_resolve(*args, **kwargs) -> Any: ...
    def pop(*args, **kwargs) -> Any: ...
    def prepend(draw_func) -> Any: ...
    def property_overridable_library_set(*args, **kwargs) -> Any: ...
    def property_unset(*args, **kwargs) -> Any: ...
    def remove(draw_func) -> Any: ...
    def rna_ancestors(*args, **kwargs) -> Any: ...
    def type_recast(*args, **kwargs) -> Any: ...
    def values(*args, **kwargs) -> Any: ...

class GRAPH_PT_snapping:
    def __init__(self, /, *args, **kwargs) -> Any: ...
    def append(draw_func) -> Any: ...
    def as_pointer(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass_py(*args, **kwargs) -> Any: ...
    def draw(self, context) -> Any: ...
    def driver_add(*args, **kwargs) -> Any: ...
    def driver_remove(*args, **kwargs) -> Any: ...
    def get(*args, **kwargs) -> Any: ...
    id_data: Any
    def id_properties_clear(*args, **kwargs) -> Any: ...
    def id_properties_ensure(*args, **kwargs) -> Any: ...
    def id_properties_ui(*args, **kwargs) -> Any: ...
    def is_extended() -> Any: ...
    def is_property_hidden(*args, **kwargs) -> Any: ...
    def is_property_overridable_library(*args, **kwargs) -> Any: ...
    def is_property_readonly(*args, **kwargs) -> Any: ...
    def is_property_set(*args, **kwargs) -> Any: ...
    def items(*args, **kwargs) -> Any: ...
    def keyframe_delete(*args, **kwargs) -> Any: ...
    def keyframe_insert(*args, **kwargs) -> Any: ...
    def keys(*args, **kwargs) -> Any: ...
    def path_from_id(*args, **kwargs) -> Any: ...
    def path_from_module(*args, **kwargs) -> Any: ...
    def path_resolve(*args, **kwargs) -> Any: ...
    def pop(*args, **kwargs) -> Any: ...
    def prepend(draw_func) -> Any: ...
    def property_overridable_library_set(*args, **kwargs) -> Any: ...
    def property_unset(*args, **kwargs) -> Any: ...
    def remove(draw_func) -> Any: ...
    def rna_ancestors(*args, **kwargs) -> Any: ...
    def type_recast(*args, **kwargs) -> Any: ...
    def values(*args, **kwargs) -> Any: ...

class Header:
    def __init__(self, /, *args, **kwargs) -> Any: ...
    def append(draw_func) -> Any: ...
    def as_pointer(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass_py(*args, **kwargs) -> Any: ...
    def driver_add(*args, **kwargs) -> Any: ...
    def driver_remove(*args, **kwargs) -> Any: ...
    def get(*args, **kwargs) -> Any: ...
    id_data: Any
    def id_properties_clear(*args, **kwargs) -> Any: ...
    def id_properties_ensure(*args, **kwargs) -> Any: ...
    def id_properties_ui(*args, **kwargs) -> Any: ...
    def is_extended() -> Any: ...
    def is_property_hidden(*args, **kwargs) -> Any: ...
    def is_property_overridable_library(*args, **kwargs) -> Any: ...
    def is_property_readonly(*args, **kwargs) -> Any: ...
    def is_property_set(*args, **kwargs) -> Any: ...
    def items(*args, **kwargs) -> Any: ...
    def keyframe_delete(*args, **kwargs) -> Any: ...
    def keyframe_insert(*args, **kwargs) -> Any: ...
    def keys(*args, **kwargs) -> Any: ...
    def path_from_id(*args, **kwargs) -> Any: ...
    def path_from_module(*args, **kwargs) -> Any: ...
    def path_resolve(*args, **kwargs) -> Any: ...
    def pop(*args, **kwargs) -> Any: ...
    def prepend(draw_func) -> Any: ...
    def property_overridable_library_set(*args, **kwargs) -> Any: ...
    def property_unset(*args, **kwargs) -> Any: ...
    def remove(draw_func) -> Any: ...
    def rna_ancestors(*args, **kwargs) -> Any: ...
    def type_recast(*args, **kwargs) -> Any: ...
    def values(*args, **kwargs) -> Any: ...

class Menu:
    def __init__(self, /, *args, **kwargs) -> Any: ...
    def append(draw_func) -> Any: ...
    def as_pointer(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass_py(*args, **kwargs) -> Any: ...
    def draw_collapsible(context, layout) -> Any: ...
    def draw_preset(self, _context) -> Any: ...
    def driver_add(*args, **kwargs) -> Any: ...
    def driver_remove(*args, **kwargs) -> Any: ...
    def get(*args, **kwargs) -> Any: ...
    id_data: Any
    def id_properties_clear(*args, **kwargs) -> Any: ...
    def id_properties_ensure(*args, **kwargs) -> Any: ...
    def id_properties_ui(*args, **kwargs) -> Any: ...
    def is_extended() -> Any: ...
    def is_property_hidden(*args, **kwargs) -> Any: ...
    def is_property_overridable_library(*args, **kwargs) -> Any: ...
    def is_property_readonly(*args, **kwargs) -> Any: ...
    def is_property_set(*args, **kwargs) -> Any: ...
    def items(*args, **kwargs) -> Any: ...
    def keyframe_delete(*args, **kwargs) -> Any: ...
    def keyframe_insert(*args, **kwargs) -> Any: ...
    def keys(*args, **kwargs) -> Any: ...
    def path_from_id(*args, **kwargs) -> Any: ...
    def path_from_module(*args, **kwargs) -> Any: ...
    def path_menu(self, searchpaths, operator, *, props_default=None, prop_filepath='filepath', filter_ext=None, filter_path=None, display_name=None, add_operator=None, add_operator_props=None, translate=True) -> Any: ...
    def path_resolve(*args, **kwargs) -> Any: ...
    def pop(*args, **kwargs) -> Any: ...
    def prepend(draw_func) -> Any: ...
    def property_overridable_library_set(*args, **kwargs) -> Any: ...
    def property_unset(*args, **kwargs) -> Any: ...
    def remove(draw_func) -> Any: ...
    def rna_ancestors(*args, **kwargs) -> Any: ...
    def type_recast(*args, **kwargs) -> Any: ...
    def values(*args, **kwargs) -> Any: ...

class Panel:
    def __init__(self, /, *args, **kwargs) -> Any: ...
    def append(draw_func) -> Any: ...
    def as_pointer(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass_py(*args, **kwargs) -> Any: ...
    def driver_add(*args, **kwargs) -> Any: ...
    def driver_remove(*args, **kwargs) -> Any: ...
    def get(*args, **kwargs) -> Any: ...
    id_data: Any
    def id_properties_clear(*args, **kwargs) -> Any: ...
    def id_properties_ensure(*args, **kwargs) -> Any: ...
    def id_properties_ui(*args, **kwargs) -> Any: ...
    def is_extended() -> Any: ...
    def is_property_hidden(*args, **kwargs) -> Any: ...
    def is_property_overridable_library(*args, **kwargs) -> Any: ...
    def is_property_readonly(*args, **kwargs) -> Any: ...
    def is_property_set(*args, **kwargs) -> Any: ...
    def items(*args, **kwargs) -> Any: ...
    def keyframe_delete(*args, **kwargs) -> Any: ...
    def keyframe_insert(*args, **kwargs) -> Any: ...
    def keys(*args, **kwargs) -> Any: ...
    def path_from_id(*args, **kwargs) -> Any: ...
    def path_from_module(*args, **kwargs) -> Any: ...
    def path_resolve(*args, **kwargs) -> Any: ...
    def pop(*args, **kwargs) -> Any: ...
    def prepend(draw_func) -> Any: ...
    def property_overridable_library_set(*args, **kwargs) -> Any: ...
    def property_unset(*args, **kwargs) -> Any: ...
    def remove(draw_func) -> Any: ...
    def rna_ancestors(*args, **kwargs) -> Any: ...
    def type_recast(*args, **kwargs) -> Any: ...
    def values(*args, **kwargs) -> Any: ...

classes: Any
def dopesheet_filter(layout, context) -> Any:
    ...

def drivers_editor_footer(layout, context) -> Any:
    ...

i18n_contexts: Any
def iface_(*args, **kwargs) -> Any:
    ...

def playback_controls(layout, context) -> Any:
    ...
