"""
Online Documentation:
https://docs.blender.org/api/current/bpy_extras.asset_utils.html
"""

# Blender Probe Generated Stub for Blender 5.0.1
# noinspection PyPep8Naming
# noinspection PyUnresolvedReferences
# noqa: N801
# pylint: disable=invalid-name


import sys
import typing
from typing import Any, Union, Callable, Iterator

class AssetBrowserPanel:
    """
    Online Documentation:
    https://docs.blender.org/api/current/bpy_extras.asset_utils.html
    """
    def __init__(self, /, *args, **kwargs) -> Any: ...
    def asset_browser_panel_poll(context) -> Any: ...
    def poll(context) -> Any: ...

class AssetMetaDataPanel:
    """
    Online Documentation:
    https://docs.blender.org/api/current/bpy_extras.asset_utils.html
    """
    def __init__(self, /, *args, **kwargs) -> Any: ...
    def poll(context) -> Any: ...

class Context:
    """
    Online Documentation:
    https://docs.blender.org/api/current/bpy_extras.asset_utils.html
    """
    def __init__(self, /, *args, **kwargs) -> Any: ...
    def as_pointer(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass_py(*args, **kwargs) -> Any: ...
    def copy(self) -> Any: ...
    def driver_add(*args, **kwargs) -> Any: ...
    def driver_remove(*args, **kwargs) -> Any: ...
    def get(*args, **kwargs) -> Any: ...
    id_data: Any
    def id_properties_clear(*args, **kwargs) -> Any: ...
    def id_properties_ensure(*args, **kwargs) -> Any: ...
    def id_properties_ui(*args, **kwargs) -> Any: ...
    def is_property_hidden(*args, **kwargs) -> Any: ...
    def is_property_overridable_library(*args, **kwargs) -> Any: ...
    def is_property_readonly(*args, **kwargs) -> Any: ...
    def is_property_set(*args, **kwargs) -> Any: ...
    def items(*args, **kwargs) -> Any: ...
    def keyframe_delete(*args, **kwargs) -> Any: ...
    def keyframe_insert(*args, **kwargs) -> Any: ...
    def keys(*args, **kwargs) -> Any: ...
    def path_from_id(*args, **kwargs) -> Any: ...
    def path_from_module(*args, **kwargs) -> Any: ...
    def path_resolve(self, path, coerce=True) -> Any: ...
    def pop(*args, **kwargs) -> Any: ...
    def property_overridable_library_set(*args, **kwargs) -> Any: ...
    def property_unset(*args, **kwargs) -> Any: ...
    def rna_ancestors(*args, **kwargs) -> Any: ...
    def temp_override(*args, **kwargs) -> Any: ...
    def type_recast(*args, **kwargs) -> Any: ...
    def values(*args, **kwargs) -> Any: ...
    # --- Injected Methods ---
    selected_objects: list[Any]
    active_object: Any
    view_layer: Any
    scene: Any
    screen: Any
    area: Any
    region: Any
    window: Any
    window_manager: Any
    preferences: Any
    def temp_override(self, window=None, area=None, region=None, **kwargs) -> Any:
        """
        **⚠️ Warning (Stub)**:
        This method is provided by the IDE plugin.
        """
        ...
    def __getattr__(self, name) -> Any:
        """
        **⚠️ Warning (Stub)**:
        This method is provided by the IDE plugin.
        """
        ...

class SpaceAssetInfo:
    """
    Online Documentation:
    https://docs.blender.org/api/current/bpy_extras.asset_utils.html
    """
    def __init__(self, /, *args, **kwargs) -> Any: ...
    def is_asset_browser(space_data: bpy.types.Space) -> Any: ...
    def is_asset_browser_poll(context: _bpy_types.Context) -> Any: ...
