# Blender Probe Generated Stub for Blender 5.0.1
# noinspection PyPep8Naming
# noinspection PyUnresolvedReferences
# noqa: N801
# pylint: disable=invalid-name


import sys
import typing
from typing import Any, Union, Callable, Iterator

class Menu:
    def __init__(self, /, *args, **kwargs) -> Any: ...
    def append(draw_func) -> Any: ...
    def as_pointer(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass_py(*args, **kwargs) -> Any: ...
    def draw_collapsible(context, layout) -> Any: ...
    def draw_preset(self, _context) -> Any: ...
    def driver_add(*args, **kwargs) -> Any: ...
    def driver_remove(*args, **kwargs) -> Any: ...
    def get(*args, **kwargs) -> Any: ...
    id_data: Any
    def id_properties_clear(*args, **kwargs) -> Any: ...
    def id_properties_ensure(*args, **kwargs) -> Any: ...
    def id_properties_ui(*args, **kwargs) -> Any: ...
    def is_extended() -> Any: ...
    def is_property_hidden(*args, **kwargs) -> Any: ...
    def is_property_overridable_library(*args, **kwargs) -> Any: ...
    def is_property_readonly(*args, **kwargs) -> Any: ...
    def is_property_set(*args, **kwargs) -> Any: ...
    def items(*args, **kwargs) -> Any: ...
    def keyframe_delete(*args, **kwargs) -> Any: ...
    def keyframe_insert(*args, **kwargs) -> Any: ...
    def keys(*args, **kwargs) -> Any: ...
    def path_from_id(*args, **kwargs) -> Any: ...
    def path_from_module(*args, **kwargs) -> Any: ...
    def path_menu(self, searchpaths, operator, *, props_default=None, prop_filepath='filepath', filter_ext=None, filter_path=None, display_name=None, add_operator=None, add_operator_props=None, translate=True) -> Any: ...
    def path_resolve(*args, **kwargs) -> Any: ...
    def pop(*args, **kwargs) -> Any: ...
    def prepend(draw_func) -> Any: ...
    def property_overridable_library_set(*args, **kwargs) -> Any: ...
    def property_unset(*args, **kwargs) -> Any: ...
    def remove(draw_func) -> Any: ...
    def rna_ancestors(*args, **kwargs) -> Any: ...
    def type_recast(*args, **kwargs) -> Any: ...
    def values(*args, **kwargs) -> Any: ...

class ToolActivePanelHelper:
    def __init__(self, /, *args, **kwargs) -> Any: ...
    def draw(self, context) -> Any: ...

class ToolDef:
    """ToolDef(idname, label, description, icon, cursor, widget_properties, widget, keymap, brush_type, data_block, operator, draw_settings, draw_cursor, options)"""
    def __init__(self, /, *args, **kwargs) -> Any: ...
    brush_type: Any
    def count(self, value, /) -> Any: ...
    cursor: Any
    data_block: Any
    description: Any
    draw_cursor: Any
    draw_settings: Any
    def from_dict(kw_args) -> Any: ...
    def from_fn(fn) -> Any: ...
    icon: Any
    idname: Any
    def index(self, value, start=0, stop=9223372036854775807, /) -> Any: ...
    keymap: Any
    label: Any
    operator: Any
    options: Any
    widget: Any
    widget_properties: Any

class ToolSelectPanelHelper:
    """
    Generic Class, can be used for any toolbar.

    - keymap_prefix:
      The text prefix for each key-map for this spaces tools.
    - tools_all():
      Generator (context_mode, tools) tuple pairs for all tools defined.
    - tools_from_context(context, mode=None):
      A generator for all tools available in the current context.

    Tool Sequence Structure
    =======================

    Sequences of tools as returned by tools_all() and tools_from_context() are comprised of:

    - A `ToolDef` instance (representing a tool that can be activated).
    - None (a visual separator in the tool list).
    - A tuple of `ToolDef` or None values
      (representing a group of tools that can be selected between using a click-drag action).
      Note that only a single level of nesting is supported (groups cannot contain sub-groups).
    - A callable which takes a single context argument and returns a tuple of values described above.
      When the context is None, all potential tools must be returned.
    """
    def __init__(self, /, *args, **kwargs) -> Any: ...
    def draw(self, context) -> Any: ...
    def draw_active_tool_fallback(context, layout, tool, *, is_horizontal_layout=False) -> Any: ...
    def draw_active_tool_header(context, layout, *, show_tool_icon_always=False, tool_key=None) -> Any: ...
    def draw_cls(layout, context, detect_layout=True, scale_y=1.75) -> Any: ...
    def draw_fallback_tool_items(layout, context) -> Any: ...
    def draw_fallback_tool_items_for_pie_menu(layout, context) -> Any: ...
    def keymap_ui_hierarchy(context_mode) -> Any: ...
    def register() -> Any: ...
    def register_ensure() -> Any: ...
    def tool_active_from_context(context) -> Any: ...
    def tools_all() -> Any: ...
    def tools_from_context(context, mode=None) -> Any: ...

class WM_MT_toolsystem_submenu:
    def __init__(self, /, *args, **kwargs) -> Any: ...
    def append(draw_func) -> Any: ...
    def as_pointer(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass_py(*args, **kwargs) -> Any: ...
    def draw(self, context) -> Any: ...
    def draw_collapsible(context, layout) -> Any: ...
    def draw_preset(self, _context) -> Any: ...
    def driver_add(*args, **kwargs) -> Any: ...
    def driver_remove(*args, **kwargs) -> Any: ...
    def get(*args, **kwargs) -> Any: ...
    id_data: Any
    def id_properties_clear(*args, **kwargs) -> Any: ...
    def id_properties_ensure(*args, **kwargs) -> Any: ...
    def id_properties_ui(*args, **kwargs) -> Any: ...
    def is_extended() -> Any: ...
    def is_property_hidden(*args, **kwargs) -> Any: ...
    def is_property_overridable_library(*args, **kwargs) -> Any: ...
    def is_property_readonly(*args, **kwargs) -> Any: ...
    def is_property_set(*args, **kwargs) -> Any: ...
    def items(*args, **kwargs) -> Any: ...
    def keyframe_delete(*args, **kwargs) -> Any: ...
    def keyframe_insert(*args, **kwargs) -> Any: ...
    def keys(*args, **kwargs) -> Any: ...
    def path_from_id(*args, **kwargs) -> Any: ...
    def path_from_module(*args, **kwargs) -> Any: ...
    def path_menu(self, searchpaths, operator, *, props_default=None, prop_filepath='filepath', filter_ext=None, filter_path=None, display_name=None, add_operator=None, add_operator_props=None, translate=True) -> Any: ...
    def path_resolve(*args, **kwargs) -> Any: ...
    def pop(*args, **kwargs) -> Any: ...
    def prepend(draw_func) -> Any: ...
    def property_overridable_library_set(*args, **kwargs) -> Any: ...
    def property_unset(*args, **kwargs) -> Any: ...
    def remove(draw_func) -> Any: ...
    def rna_ancestors(*args, **kwargs) -> Any: ...
    def type_recast(*args, **kwargs) -> Any: ...
    def values(*args, **kwargs) -> Any: ...

def activate_by_id(context, space_type, idname, *, as_fallback=False) -> Any:
    ...

def activate_by_id_or_cycle(context, space_type, idname, *, offset=1, as_fallback=False) -> Any:
    ...

classes: Any
def description_from_id(context, space_type, idname, *, use_operator=True) -> Any:
    ...

i18n_contexts: Any
def iface_(*args, **kwargs) -> Any:
    ...

def item_from_flat_index(context, space_type, index) -> Any:
    ...

def item_from_id(context, space_type, idname) -> Any:
    ...

def item_from_id_active(context, space_type, idname) -> Any:
    ...

def item_from_id_active_with_group(context, space_type, idname) -> Any:
    ...

def item_from_index_active(context, space_type, index) -> Any:
    ...

def item_group_from_id(context, space_type, idname, *, coerce=False) -> Any:
    ...

def keymap_from_id(context, space_type, idname) -> Any:
    ...

def tip_(*args, **kwargs) -> Any:
    ...
