# Blender Probe Generated Stub for Blender 5.0.1
# noinspection PyPep8Naming
# noinspection PyUnresolvedReferences
# noqa: N801
# pylint: disable=invalid-name


import sys
import typing
from typing import Any, Union, Callable, Iterator

class CLOTH_PT_presets:
    def __init__(self, /, *args, **kwargs) -> Any: ...
    def append(draw_func) -> Any: ...
    def as_pointer(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass_py(*args, **kwargs) -> Any: ...
    def draw(self, context) -> Any: ...
    def draw_menu(layout, text=None) -> Any: ...
    def draw_panel_header(layout) -> Any: ...
    def driver_add(*args, **kwargs) -> Any: ...
    def driver_remove(*args, **kwargs) -> Any: ...
    def get(*args, **kwargs) -> Any: ...
    id_data: Any
    def id_properties_clear(*args, **kwargs) -> Any: ...
    def id_properties_ensure(*args, **kwargs) -> Any: ...
    def id_properties_ui(*args, **kwargs) -> Any: ...
    def is_extended() -> Any: ...
    def is_property_hidden(*args, **kwargs) -> Any: ...
    def is_property_overridable_library(*args, **kwargs) -> Any: ...
    def is_property_readonly(*args, **kwargs) -> Any: ...
    def is_property_set(*args, **kwargs) -> Any: ...
    def items(*args, **kwargs) -> Any: ...
    def keyframe_delete(*args, **kwargs) -> Any: ...
    def keyframe_insert(*args, **kwargs) -> Any: ...
    def keys(*args, **kwargs) -> Any: ...
    def path_from_id(*args, **kwargs) -> Any: ...
    def path_from_module(*args, **kwargs) -> Any: ...
    def path_menu(self, searchpaths, operator, *, props_default=None, prop_filepath='filepath', filter_ext=None, filter_path=None, display_name=None, add_operator=None, add_operator_props=None, translate=True) -> Any: ...
    def path_resolve(*args, **kwargs) -> Any: ...
    def pop(*args, **kwargs) -> Any: ...
    def prepend(draw_func) -> Any: ...
    def property_overridable_library_set(*args, **kwargs) -> Any: ...
    def property_unset(*args, **kwargs) -> Any: ...
    def remove(draw_func) -> Any: ...
    def rna_ancestors(*args, **kwargs) -> Any: ...
    def type_recast(*args, **kwargs) -> Any: ...
    def values(*args, **kwargs) -> Any: ...

class PHYSICS_PT_cloth:
    def __init__(self, /, *args, **kwargs) -> Any: ...
    def append(draw_func) -> Any: ...
    def as_pointer(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass_py(*args, **kwargs) -> Any: ...
    def draw(self, context) -> Any: ...
    def draw_header_preset(self, _context) -> Any: ...
    def driver_add(*args, **kwargs) -> Any: ...
    def driver_remove(*args, **kwargs) -> Any: ...
    def get(*args, **kwargs) -> Any: ...
    id_data: Any
    def id_properties_clear(*args, **kwargs) -> Any: ...
    def id_properties_ensure(*args, **kwargs) -> Any: ...
    def id_properties_ui(*args, **kwargs) -> Any: ...
    def is_extended() -> Any: ...
    def is_property_hidden(*args, **kwargs) -> Any: ...
    def is_property_overridable_library(*args, **kwargs) -> Any: ...
    def is_property_readonly(*args, **kwargs) -> Any: ...
    def is_property_set(*args, **kwargs) -> Any: ...
    def items(*args, **kwargs) -> Any: ...
    def keyframe_delete(*args, **kwargs) -> Any: ...
    def keyframe_insert(*args, **kwargs) -> Any: ...
    def keys(*args, **kwargs) -> Any: ...
    def path_from_id(*args, **kwargs) -> Any: ...
    def path_from_module(*args, **kwargs) -> Any: ...
    def path_resolve(*args, **kwargs) -> Any: ...
    def poll(context) -> Any: ...
    def pop(*args, **kwargs) -> Any: ...
    def prepend(draw_func) -> Any: ...
    def property_overridable_library_set(*args, **kwargs) -> Any: ...
    def property_unset(*args, **kwargs) -> Any: ...
    def remove(draw_func) -> Any: ...
    def rna_ancestors(*args, **kwargs) -> Any: ...
    def type_recast(*args, **kwargs) -> Any: ...
    def values(*args, **kwargs) -> Any: ...

class PHYSICS_PT_cloth_cache:
    def __init__(self, /, *args, **kwargs) -> Any: ...
    def append(draw_func) -> Any: ...
    def as_pointer(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass_py(*args, **kwargs) -> Any: ...
    def draw(self, context) -> Any: ...
    def driver_add(*args, **kwargs) -> Any: ...
    def driver_remove(*args, **kwargs) -> Any: ...
    def get(*args, **kwargs) -> Any: ...
    id_data: Any
    def id_properties_clear(*args, **kwargs) -> Any: ...
    def id_properties_ensure(*args, **kwargs) -> Any: ...
    def id_properties_ui(*args, **kwargs) -> Any: ...
    def is_extended() -> Any: ...
    def is_property_hidden(*args, **kwargs) -> Any: ...
    def is_property_overridable_library(*args, **kwargs) -> Any: ...
    def is_property_readonly(*args, **kwargs) -> Any: ...
    def is_property_set(*args, **kwargs) -> Any: ...
    def items(*args, **kwargs) -> Any: ...
    def keyframe_delete(*args, **kwargs) -> Any: ...
    def keyframe_insert(*args, **kwargs) -> Any: ...
    def keys(*args, **kwargs) -> Any: ...
    def path_from_id(*args, **kwargs) -> Any: ...
    def path_from_module(*args, **kwargs) -> Any: ...
    def path_resolve(*args, **kwargs) -> Any: ...
    def poll(context) -> Any: ...
    def pop(*args, **kwargs) -> Any: ...
    def prepend(draw_func) -> Any: ...
    def property_overridable_library_set(*args, **kwargs) -> Any: ...
    def property_unset(*args, **kwargs) -> Any: ...
    def remove(draw_func) -> Any: ...
    def rna_ancestors(*args, **kwargs) -> Any: ...
    def type_recast(*args, **kwargs) -> Any: ...
    def values(*args, **kwargs) -> Any: ...

class PHYSICS_PT_cloth_collision:
    def __init__(self, /, *args, **kwargs) -> Any: ...
    def append(draw_func) -> Any: ...
    def as_pointer(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass_py(*args, **kwargs) -> Any: ...
    def draw(self, context) -> Any: ...
    def driver_add(*args, **kwargs) -> Any: ...
    def driver_remove(*args, **kwargs) -> Any: ...
    def get(*args, **kwargs) -> Any: ...
    id_data: Any
    def id_properties_clear(*args, **kwargs) -> Any: ...
    def id_properties_ensure(*args, **kwargs) -> Any: ...
    def id_properties_ui(*args, **kwargs) -> Any: ...
    def is_extended() -> Any: ...
    def is_property_hidden(*args, **kwargs) -> Any: ...
    def is_property_overridable_library(*args, **kwargs) -> Any: ...
    def is_property_readonly(*args, **kwargs) -> Any: ...
    def is_property_set(*args, **kwargs) -> Any: ...
    def items(*args, **kwargs) -> Any: ...
    def keyframe_delete(*args, **kwargs) -> Any: ...
    def keyframe_insert(*args, **kwargs) -> Any: ...
    def keys(*args, **kwargs) -> Any: ...
    def path_from_id(*args, **kwargs) -> Any: ...
    def path_from_module(*args, **kwargs) -> Any: ...
    def path_resolve(*args, **kwargs) -> Any: ...
    def poll(context) -> Any: ...
    def pop(*args, **kwargs) -> Any: ...
    def prepend(draw_func) -> Any: ...
    def property_overridable_library_set(*args, **kwargs) -> Any: ...
    def property_unset(*args, **kwargs) -> Any: ...
    def remove(draw_func) -> Any: ...
    def rna_ancestors(*args, **kwargs) -> Any: ...
    def type_recast(*args, **kwargs) -> Any: ...
    def values(*args, **kwargs) -> Any: ...

class PHYSICS_PT_cloth_damping:
    def __init__(self, /, *args, **kwargs) -> Any: ...
    def append(draw_func) -> Any: ...
    def as_pointer(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass_py(*args, **kwargs) -> Any: ...
    def draw(self, context) -> Any: ...
    def driver_add(*args, **kwargs) -> Any: ...
    def driver_remove(*args, **kwargs) -> Any: ...
    def get(*args, **kwargs) -> Any: ...
    id_data: Any
    def id_properties_clear(*args, **kwargs) -> Any: ...
    def id_properties_ensure(*args, **kwargs) -> Any: ...
    def id_properties_ui(*args, **kwargs) -> Any: ...
    def is_extended() -> Any: ...
    def is_property_hidden(*args, **kwargs) -> Any: ...
    def is_property_overridable_library(*args, **kwargs) -> Any: ...
    def is_property_readonly(*args, **kwargs) -> Any: ...
    def is_property_set(*args, **kwargs) -> Any: ...
    def items(*args, **kwargs) -> Any: ...
    def keyframe_delete(*args, **kwargs) -> Any: ...
    def keyframe_insert(*args, **kwargs) -> Any: ...
    def keys(*args, **kwargs) -> Any: ...
    def path_from_id(*args, **kwargs) -> Any: ...
    def path_from_module(*args, **kwargs) -> Any: ...
    def path_resolve(*args, **kwargs) -> Any: ...
    def poll(context) -> Any: ...
    def pop(*args, **kwargs) -> Any: ...
    def prepend(draw_func) -> Any: ...
    def property_overridable_library_set(*args, **kwargs) -> Any: ...
    def property_unset(*args, **kwargs) -> Any: ...
    def remove(draw_func) -> Any: ...
    def rna_ancestors(*args, **kwargs) -> Any: ...
    def type_recast(*args, **kwargs) -> Any: ...
    def values(*args, **kwargs) -> Any: ...

class PHYSICS_PT_cloth_field_weights:
    def __init__(self, /, *args, **kwargs) -> Any: ...
    def append(draw_func) -> Any: ...
    def as_pointer(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass_py(*args, **kwargs) -> Any: ...
    def draw(self, context) -> Any: ...
    def driver_add(*args, **kwargs) -> Any: ...
    def driver_remove(*args, **kwargs) -> Any: ...
    def get(*args, **kwargs) -> Any: ...
    id_data: Any
    def id_properties_clear(*args, **kwargs) -> Any: ...
    def id_properties_ensure(*args, **kwargs) -> Any: ...
    def id_properties_ui(*args, **kwargs) -> Any: ...
    def is_extended() -> Any: ...
    def is_property_hidden(*args, **kwargs) -> Any: ...
    def is_property_overridable_library(*args, **kwargs) -> Any: ...
    def is_property_readonly(*args, **kwargs) -> Any: ...
    def is_property_set(*args, **kwargs) -> Any: ...
    def items(*args, **kwargs) -> Any: ...
    def keyframe_delete(*args, **kwargs) -> Any: ...
    def keyframe_insert(*args, **kwargs) -> Any: ...
    def keys(*args, **kwargs) -> Any: ...
    def path_from_id(*args, **kwargs) -> Any: ...
    def path_from_module(*args, **kwargs) -> Any: ...
    def path_resolve(*args, **kwargs) -> Any: ...
    def poll(context) -> Any: ...
    def pop(*args, **kwargs) -> Any: ...
    def prepend(draw_func) -> Any: ...
    def property_overridable_library_set(*args, **kwargs) -> Any: ...
    def property_unset(*args, **kwargs) -> Any: ...
    def remove(draw_func) -> Any: ...
    def rna_ancestors(*args, **kwargs) -> Any: ...
    def type_recast(*args, **kwargs) -> Any: ...
    def values(*args, **kwargs) -> Any: ...

class PHYSICS_PT_cloth_internal_springs:
    def __init__(self, /, *args, **kwargs) -> Any: ...
    def append(draw_func) -> Any: ...
    def as_pointer(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass_py(*args, **kwargs) -> Any: ...
    def draw(self, context) -> Any: ...
    def draw_header(self, context) -> Any: ...
    def driver_add(*args, **kwargs) -> Any: ...
    def driver_remove(*args, **kwargs) -> Any: ...
    def get(*args, **kwargs) -> Any: ...
    id_data: Any
    def id_properties_clear(*args, **kwargs) -> Any: ...
    def id_properties_ensure(*args, **kwargs) -> Any: ...
    def id_properties_ui(*args, **kwargs) -> Any: ...
    def is_extended() -> Any: ...
    def is_property_hidden(*args, **kwargs) -> Any: ...
    def is_property_overridable_library(*args, **kwargs) -> Any: ...
    def is_property_readonly(*args, **kwargs) -> Any: ...
    def is_property_set(*args, **kwargs) -> Any: ...
    def items(*args, **kwargs) -> Any: ...
    def keyframe_delete(*args, **kwargs) -> Any: ...
    def keyframe_insert(*args, **kwargs) -> Any: ...
    def keys(*args, **kwargs) -> Any: ...
    def path_from_id(*args, **kwargs) -> Any: ...
    def path_from_module(*args, **kwargs) -> Any: ...
    def path_resolve(*args, **kwargs) -> Any: ...
    def poll(context) -> Any: ...
    def pop(*args, **kwargs) -> Any: ...
    def prepend(draw_func) -> Any: ...
    def property_overridable_library_set(*args, **kwargs) -> Any: ...
    def property_unset(*args, **kwargs) -> Any: ...
    def remove(draw_func) -> Any: ...
    def rna_ancestors(*args, **kwargs) -> Any: ...
    def type_recast(*args, **kwargs) -> Any: ...
    def values(*args, **kwargs) -> Any: ...

class PHYSICS_PT_cloth_object_collision:
    def __init__(self, /, *args, **kwargs) -> Any: ...
    def append(draw_func) -> Any: ...
    def as_pointer(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass_py(*args, **kwargs) -> Any: ...
    def draw(self, context) -> Any: ...
    def draw_header(self, context) -> Any: ...
    def driver_add(*args, **kwargs) -> Any: ...
    def driver_remove(*args, **kwargs) -> Any: ...
    def get(*args, **kwargs) -> Any: ...
    id_data: Any
    def id_properties_clear(*args, **kwargs) -> Any: ...
    def id_properties_ensure(*args, **kwargs) -> Any: ...
    def id_properties_ui(*args, **kwargs) -> Any: ...
    def is_extended() -> Any: ...
    def is_property_hidden(*args, **kwargs) -> Any: ...
    def is_property_overridable_library(*args, **kwargs) -> Any: ...
    def is_property_readonly(*args, **kwargs) -> Any: ...
    def is_property_set(*args, **kwargs) -> Any: ...
    def items(*args, **kwargs) -> Any: ...
    def keyframe_delete(*args, **kwargs) -> Any: ...
    def keyframe_insert(*args, **kwargs) -> Any: ...
    def keys(*args, **kwargs) -> Any: ...
    def path_from_id(*args, **kwargs) -> Any: ...
    def path_from_module(*args, **kwargs) -> Any: ...
    def path_resolve(*args, **kwargs) -> Any: ...
    def poll(context) -> Any: ...
    def pop(*args, **kwargs) -> Any: ...
    def prepend(draw_func) -> Any: ...
    def property_overridable_library_set(*args, **kwargs) -> Any: ...
    def property_unset(*args, **kwargs) -> Any: ...
    def remove(draw_func) -> Any: ...
    def rna_ancestors(*args, **kwargs) -> Any: ...
    def type_recast(*args, **kwargs) -> Any: ...
    def values(*args, **kwargs) -> Any: ...

class PHYSICS_PT_cloth_physical_properties:
    def __init__(self, /, *args, **kwargs) -> Any: ...
    def append(draw_func) -> Any: ...
    def as_pointer(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass_py(*args, **kwargs) -> Any: ...
    def draw(self, context) -> Any: ...
    def driver_add(*args, **kwargs) -> Any: ...
    def driver_remove(*args, **kwargs) -> Any: ...
    def get(*args, **kwargs) -> Any: ...
    id_data: Any
    def id_properties_clear(*args, **kwargs) -> Any: ...
    def id_properties_ensure(*args, **kwargs) -> Any: ...
    def id_properties_ui(*args, **kwargs) -> Any: ...
    def is_extended() -> Any: ...
    def is_property_hidden(*args, **kwargs) -> Any: ...
    def is_property_overridable_library(*args, **kwargs) -> Any: ...
    def is_property_readonly(*args, **kwargs) -> Any: ...
    def is_property_set(*args, **kwargs) -> Any: ...
    def items(*args, **kwargs) -> Any: ...
    def keyframe_delete(*args, **kwargs) -> Any: ...
    def keyframe_insert(*args, **kwargs) -> Any: ...
    def keys(*args, **kwargs) -> Any: ...
    def path_from_id(*args, **kwargs) -> Any: ...
    def path_from_module(*args, **kwargs) -> Any: ...
    def path_resolve(*args, **kwargs) -> Any: ...
    def poll(context) -> Any: ...
    def pop(*args, **kwargs) -> Any: ...
    def prepend(draw_func) -> Any: ...
    def property_overridable_library_set(*args, **kwargs) -> Any: ...
    def property_unset(*args, **kwargs) -> Any: ...
    def remove(draw_func) -> Any: ...
    def rna_ancestors(*args, **kwargs) -> Any: ...
    def type_recast(*args, **kwargs) -> Any: ...
    def values(*args, **kwargs) -> Any: ...

class PHYSICS_PT_cloth_pressure:
    def __init__(self, /, *args, **kwargs) -> Any: ...
    def append(draw_func) -> Any: ...
    def as_pointer(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass_py(*args, **kwargs) -> Any: ...
    def draw(self, context) -> Any: ...
    def draw_header(self, context) -> Any: ...
    def driver_add(*args, **kwargs) -> Any: ...
    def driver_remove(*args, **kwargs) -> Any: ...
    def get(*args, **kwargs) -> Any: ...
    id_data: Any
    def id_properties_clear(*args, **kwargs) -> Any: ...
    def id_properties_ensure(*args, **kwargs) -> Any: ...
    def id_properties_ui(*args, **kwargs) -> Any: ...
    def is_extended() -> Any: ...
    def is_property_hidden(*args, **kwargs) -> Any: ...
    def is_property_overridable_library(*args, **kwargs) -> Any: ...
    def is_property_readonly(*args, **kwargs) -> Any: ...
    def is_property_set(*args, **kwargs) -> Any: ...
    def items(*args, **kwargs) -> Any: ...
    def keyframe_delete(*args, **kwargs) -> Any: ...
    def keyframe_insert(*args, **kwargs) -> Any: ...
    def keys(*args, **kwargs) -> Any: ...
    def path_from_id(*args, **kwargs) -> Any: ...
    def path_from_module(*args, **kwargs) -> Any: ...
    def path_resolve(*args, **kwargs) -> Any: ...
    def poll(context) -> Any: ...
    def pop(*args, **kwargs) -> Any: ...
    def prepend(draw_func) -> Any: ...
    def property_overridable_library_set(*args, **kwargs) -> Any: ...
    def property_unset(*args, **kwargs) -> Any: ...
    def remove(draw_func) -> Any: ...
    def rna_ancestors(*args, **kwargs) -> Any: ...
    def type_recast(*args, **kwargs) -> Any: ...
    def values(*args, **kwargs) -> Any: ...

class PHYSICS_PT_cloth_property_weights:
    def __init__(self, /, *args, **kwargs) -> Any: ...
    def append(draw_func) -> Any: ...
    def as_pointer(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass_py(*args, **kwargs) -> Any: ...
    def draw(self, context) -> Any: ...
    def driver_add(*args, **kwargs) -> Any: ...
    def driver_remove(*args, **kwargs) -> Any: ...
    def get(*args, **kwargs) -> Any: ...
    id_data: Any
    def id_properties_clear(*args, **kwargs) -> Any: ...
    def id_properties_ensure(*args, **kwargs) -> Any: ...
    def id_properties_ui(*args, **kwargs) -> Any: ...
    def is_extended() -> Any: ...
    def is_property_hidden(*args, **kwargs) -> Any: ...
    def is_property_overridable_library(*args, **kwargs) -> Any: ...
    def is_property_readonly(*args, **kwargs) -> Any: ...
    def is_property_set(*args, **kwargs) -> Any: ...
    def items(*args, **kwargs) -> Any: ...
    def keyframe_delete(*args, **kwargs) -> Any: ...
    def keyframe_insert(*args, **kwargs) -> Any: ...
    def keys(*args, **kwargs) -> Any: ...
    def path_from_id(*args, **kwargs) -> Any: ...
    def path_from_module(*args, **kwargs) -> Any: ...
    def path_resolve(*args, **kwargs) -> Any: ...
    def poll(context) -> Any: ...
    def pop(*args, **kwargs) -> Any: ...
    def prepend(draw_func) -> Any: ...
    def property_overridable_library_set(*args, **kwargs) -> Any: ...
    def property_unset(*args, **kwargs) -> Any: ...
    def remove(draw_func) -> Any: ...
    def rna_ancestors(*args, **kwargs) -> Any: ...
    def type_recast(*args, **kwargs) -> Any: ...
    def values(*args, **kwargs) -> Any: ...

class PHYSICS_PT_cloth_self_collision:
    def __init__(self, /, *args, **kwargs) -> Any: ...
    def append(draw_func) -> Any: ...
    def as_pointer(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass_py(*args, **kwargs) -> Any: ...
    def draw(self, context) -> Any: ...
    def draw_header(self, context) -> Any: ...
    def driver_add(*args, **kwargs) -> Any: ...
    def driver_remove(*args, **kwargs) -> Any: ...
    def get(*args, **kwargs) -> Any: ...
    id_data: Any
    def id_properties_clear(*args, **kwargs) -> Any: ...
    def id_properties_ensure(*args, **kwargs) -> Any: ...
    def id_properties_ui(*args, **kwargs) -> Any: ...
    def is_extended() -> Any: ...
    def is_property_hidden(*args, **kwargs) -> Any: ...
    def is_property_overridable_library(*args, **kwargs) -> Any: ...
    def is_property_readonly(*args, **kwargs) -> Any: ...
    def is_property_set(*args, **kwargs) -> Any: ...
    def items(*args, **kwargs) -> Any: ...
    def keyframe_delete(*args, **kwargs) -> Any: ...
    def keyframe_insert(*args, **kwargs) -> Any: ...
    def keys(*args, **kwargs) -> Any: ...
    def path_from_id(*args, **kwargs) -> Any: ...
    def path_from_module(*args, **kwargs) -> Any: ...
    def path_resolve(*args, **kwargs) -> Any: ...
    def poll(context) -> Any: ...
    def pop(*args, **kwargs) -> Any: ...
    def prepend(draw_func) -> Any: ...
    def property_overridable_library_set(*args, **kwargs) -> Any: ...
    def property_unset(*args, **kwargs) -> Any: ...
    def remove(draw_func) -> Any: ...
    def rna_ancestors(*args, **kwargs) -> Any: ...
    def type_recast(*args, **kwargs) -> Any: ...
    def values(*args, **kwargs) -> Any: ...

class PHYSICS_PT_cloth_shape:
    def __init__(self, /, *args, **kwargs) -> Any: ...
    def append(draw_func) -> Any: ...
    def as_pointer(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass_py(*args, **kwargs) -> Any: ...
    def draw(self, context) -> Any: ...
    def driver_add(*args, **kwargs) -> Any: ...
    def driver_remove(*args, **kwargs) -> Any: ...
    def get(*args, **kwargs) -> Any: ...
    id_data: Any
    def id_properties_clear(*args, **kwargs) -> Any: ...
    def id_properties_ensure(*args, **kwargs) -> Any: ...
    def id_properties_ui(*args, **kwargs) -> Any: ...
    def is_extended() -> Any: ...
    def is_property_hidden(*args, **kwargs) -> Any: ...
    def is_property_overridable_library(*args, **kwargs) -> Any: ...
    def is_property_readonly(*args, **kwargs) -> Any: ...
    def is_property_set(*args, **kwargs) -> Any: ...
    def items(*args, **kwargs) -> Any: ...
    def keyframe_delete(*args, **kwargs) -> Any: ...
    def keyframe_insert(*args, **kwargs) -> Any: ...
    def keys(*args, **kwargs) -> Any: ...
    def path_from_id(*args, **kwargs) -> Any: ...
    def path_from_module(*args, **kwargs) -> Any: ...
    def path_resolve(*args, **kwargs) -> Any: ...
    def poll(context) -> Any: ...
    def pop(*args, **kwargs) -> Any: ...
    def prepend(draw_func) -> Any: ...
    def property_overridable_library_set(*args, **kwargs) -> Any: ...
    def property_unset(*args, **kwargs) -> Any: ...
    def remove(draw_func) -> Any: ...
    def rna_ancestors(*args, **kwargs) -> Any: ...
    def type_recast(*args, **kwargs) -> Any: ...
    def values(*args, **kwargs) -> Any: ...

class PHYSICS_PT_cloth_stiffness:
    def __init__(self, /, *args, **kwargs) -> Any: ...
    def append(draw_func) -> Any: ...
    def as_pointer(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass_py(*args, **kwargs) -> Any: ...
    def draw(self, context) -> Any: ...
    def driver_add(*args, **kwargs) -> Any: ...
    def driver_remove(*args, **kwargs) -> Any: ...
    def get(*args, **kwargs) -> Any: ...
    id_data: Any
    def id_properties_clear(*args, **kwargs) -> Any: ...
    def id_properties_ensure(*args, **kwargs) -> Any: ...
    def id_properties_ui(*args, **kwargs) -> Any: ...
    def is_extended() -> Any: ...
    def is_property_hidden(*args, **kwargs) -> Any: ...
    def is_property_overridable_library(*args, **kwargs) -> Any: ...
    def is_property_readonly(*args, **kwargs) -> Any: ...
    def is_property_set(*args, **kwargs) -> Any: ...
    def items(*args, **kwargs) -> Any: ...
    def keyframe_delete(*args, **kwargs) -> Any: ...
    def keyframe_insert(*args, **kwargs) -> Any: ...
    def keys(*args, **kwargs) -> Any: ...
    def path_from_id(*args, **kwargs) -> Any: ...
    def path_from_module(*args, **kwargs) -> Any: ...
    def path_resolve(*args, **kwargs) -> Any: ...
    def poll(context) -> Any: ...
    def pop(*args, **kwargs) -> Any: ...
    def prepend(draw_func) -> Any: ...
    def property_overridable_library_set(*args, **kwargs) -> Any: ...
    def property_unset(*args, **kwargs) -> Any: ...
    def remove(draw_func) -> Any: ...
    def rna_ancestors(*args, **kwargs) -> Any: ...
    def type_recast(*args, **kwargs) -> Any: ...
    def values(*args, **kwargs) -> Any: ...

class Panel:
    def __init__(self, /, *args, **kwargs) -> Any: ...
    def append(draw_func) -> Any: ...
    def as_pointer(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass(*args, **kwargs) -> Any: ...
    def bl_rna_get_subclass_py(*args, **kwargs) -> Any: ...
    def driver_add(*args, **kwargs) -> Any: ...
    def driver_remove(*args, **kwargs) -> Any: ...
    def get(*args, **kwargs) -> Any: ...
    id_data: Any
    def id_properties_clear(*args, **kwargs) -> Any: ...
    def id_properties_ensure(*args, **kwargs) -> Any: ...
    def id_properties_ui(*args, **kwargs) -> Any: ...
    def is_extended() -> Any: ...
    def is_property_hidden(*args, **kwargs) -> Any: ...
    def is_property_overridable_library(*args, **kwargs) -> Any: ...
    def is_property_readonly(*args, **kwargs) -> Any: ...
    def is_property_set(*args, **kwargs) -> Any: ...
    def items(*args, **kwargs) -> Any: ...
    def keyframe_delete(*args, **kwargs) -> Any: ...
    def keyframe_insert(*args, **kwargs) -> Any: ...
    def keys(*args, **kwargs) -> Any: ...
    def path_from_id(*args, **kwargs) -> Any: ...
    def path_from_module(*args, **kwargs) -> Any: ...
    def path_resolve(*args, **kwargs) -> Any: ...
    def pop(*args, **kwargs) -> Any: ...
    def prepend(draw_func) -> Any: ...
    def property_overridable_library_set(*args, **kwargs) -> Any: ...
    def property_unset(*args, **kwargs) -> Any: ...
    def remove(draw_func) -> Any: ...
    def rna_ancestors(*args, **kwargs) -> Any: ...
    def type_recast(*args, **kwargs) -> Any: ...
    def values(*args, **kwargs) -> Any: ...

class PhysicButtonsPanel:
    def __init__(self, /, *args, **kwargs) -> Any: ...
    def poll(context) -> Any: ...

class PresetPanel:
    def __init__(self, /, *args, **kwargs) -> Any: ...
    def draw(self, context) -> Any: ...
    def draw_menu(layout, text=None) -> Any: ...
    def draw_panel_header(layout) -> Any: ...
    def path_menu(self, searchpaths, operator, *, props_default=None, prop_filepath='filepath', filter_ext=None, filter_path=None, display_name=None, add_operator=None, add_operator_props=None, translate=True) -> Any: ...

classes: Any
def cloth_panel_enabled(md) -> Any:
    ...

def effector_weights_ui(self, weights, weight_type) -> Any:
    ...

def point_cache_ui(self, cache, enabled, cachetype) -> Any:
    ...
