# Blender Probe Generated Stub for Blender 5.0.1
# noinspection PyPep8Naming
# noinspection PyUnresolvedReferences
# noqa: N801
# pylint: disable=invalid-name

import typing
import bpy
from typing import Any, Optional, Union

def active_frame_delete(override_context: Optional[Union[dict, 'bpy.types.Context']] = None, execution_context: Optional[str] = None, undo: Optional[bool] = None, *, all: bool = ...) -> set[str]:
    """Delete the active Grease Pencil frame(s)"""
    ...

def bake_grease_pencil_animation(override_context: Optional[Union[dict, 'bpy.types.Context']] = None, execution_context: Optional[str] = None, undo: Optional[bool] = None, *, frame_start: int = ..., frame_end: int = ..., step: int = ..., only_selected: bool = ..., frame_target: int = ..., project_type: str = ...) -> set[str]:
    """Bake Grease Pencil object transform to Grease Pencil keyframes"""
    ...

def brush_stroke(override_context: Optional[Union[dict, 'bpy.types.Context']] = None, execution_context: Optional[str] = None, undo: Optional[bool] = None, *, stroke: bpy_prop_collection['OperatorStrokeElement'] = ..., mode: str = ..., pen_flip: bool = ...) -> set[str]:
    """Draw a new stroke in the active Grease Pencil object"""
    ...

def caps_set(override_context: Optional[Union[dict, 'bpy.types.Context']] = None, execution_context: Optional[str] = None, undo: Optional[bool] = None, *, type: str = ...) -> set[str]:
    """Change curve caps mode (rounded or flat)"""
    ...

def clean_loose(override_context: Optional[Union[dict, 'bpy.types.Context']] = None, execution_context: Optional[str] = None, undo: Optional[bool] = None, *, limit: int = ...) -> set[str]:
    """Remove loose points"""
    ...

def convert_curve_type(override_context: Optional[Union[dict, 'bpy.types.Context']] = None, execution_context: Optional[str] = None, undo: Optional[bool] = None, *, type: str = ..., threshold: float = ...) -> set[str]:
    """Convert type of selected curves"""
    ...

def copy(override_context: Optional[Union[dict, 'bpy.types.Context']] = None, execution_context: Optional[str] = None, undo: Optional[bool] = None) -> set[str]:
    """Copy the selected Grease Pencil points or strokes to the internal clipboard"""
    ...

def cyclical_set(override_context: Optional[Union[dict, 'bpy.types.Context']] = None, execution_context: Optional[str] = None, undo: Optional[bool] = None, *, type: str = ..., subdivide_cyclic_segment: bool = ...) -> set[str]:
    """Close or open the selected stroke adding a segment from last to first point"""
    ...

def delete(override_context: Optional[Union[dict, 'bpy.types.Context']] = None, execution_context: Optional[str] = None, undo: Optional[bool] = None) -> set[str]:
    """Delete selected strokes or points"""
    ...

def delete_breakdown(override_context: Optional[Union[dict, 'bpy.types.Context']] = None, execution_context: Optional[str] = None, undo: Optional[bool] = None) -> set[str]:
    """Remove breakdown frames generated by interpolating between two Grease Pencil frames"""
    ...

def delete_frame(override_context: Optional[Union[dict, 'bpy.types.Context']] = None, execution_context: Optional[str] = None, undo: Optional[bool] = None, *, type: str = ...) -> set[str]:
    """Delete Grease Pencil Frame(s)"""
    ...

def dissolve(override_context: Optional[Union[dict, 'bpy.types.Context']] = None, execution_context: Optional[str] = None, undo: Optional[bool] = None, *, type: str = ...) -> set[str]:
    """Delete selected points without splitting strokes"""
    ...

def duplicate(override_context: Optional[Union[dict, 'bpy.types.Context']] = None, execution_context: Optional[str] = None, undo: Optional[bool] = None) -> set[str]:
    """Duplicate the selected points"""
    ...

def duplicate_move(override_context: Optional[Union[dict, 'bpy.types.Context']] = None, execution_context: Optional[str] = None, undo: Optional[bool] = None, *, GREASE_PENCIL_OT_duplicate: 'GREASE_PENCIL_OT_duplicate' = ..., TRANSFORM_OT_translate: 'TRANSFORM_OT_translate' = ...) -> set[str]:
    """Make copies of the selected Grease Pencil strokes and move them"""
    ...

def erase_box(override_context: Optional[Union[dict, 'bpy.types.Context']] = None, execution_context: Optional[str] = None, undo: Optional[bool] = None, *, xmin: int = ..., xmax: int = ..., ymin: int = ..., ymax: int = ..., wait_for_input: bool = ...) -> set[str]:
    """Erase points in the box region"""
    ...

def erase_lasso(override_context: Optional[Union[dict, 'bpy.types.Context']] = None, execution_context: Optional[str] = None, undo: Optional[bool] = None, *, path: bpy_prop_collection['OperatorMousePath'] = ..., use_smooth_stroke: bool = ..., smooth_stroke_factor: float = ..., smooth_stroke_radius: int = ...) -> set[str]:
    """Erase points in the lasso region"""
    ...

def extrude(override_context: Optional[Union[dict, 'bpy.types.Context']] = None, execution_context: Optional[str] = None, undo: Optional[bool] = None) -> set[str]:
    """Extrude the selected points"""
    ...

def extrude_move(override_context: Optional[Union[dict, 'bpy.types.Context']] = None, execution_context: Optional[str] = None, undo: Optional[bool] = None, *, GREASE_PENCIL_OT_extrude: 'GREASE_PENCIL_OT_extrude' = ..., TRANSFORM_OT_translate: 'TRANSFORM_OT_translate' = ...) -> set[str]:
    """Extrude selected points and move them"""
    ...

def fill(override_context: Optional[Union[dict, 'bpy.types.Context']] = None, execution_context: Optional[str] = None, undo: Optional[bool] = None, *, invert: bool = ..., precision: bool = ...) -> set[str]:
    """Fill with color the shape formed by strokes"""
    ...

def frame_clean_duplicate(override_context: Optional[Union[dict, 'bpy.types.Context']] = None, execution_context: Optional[str] = None, undo: Optional[bool] = None, *, selected: bool = ...) -> set[str]:
    """Remove any keyframe that is a duplicate of the previous one"""
    ...

def frame_duplicate(override_context: Optional[Union[dict, 'bpy.types.Context']] = None, execution_context: Optional[str] = None, undo: Optional[bool] = None, *, all: bool = ...) -> set[str]:
    """Make a copy of the active Grease Pencil frame(s)"""
    ...

def insert_blank_frame(override_context: Optional[Union[dict, 'bpy.types.Context']] = None, execution_context: Optional[str] = None, undo: Optional[bool] = None, *, all_layers: bool = ..., duration: int = ...) -> set[str]:
    """Insert a blank frame on the current scene frame"""
    ...

def interpolate(override_context: Optional[Union[dict, 'bpy.types.Context']] = None, execution_context: Optional[str] = None, undo: Optional[bool] = None, *, shift: float = ..., layers: str = ..., exclude_breakdowns: bool = ..., use_selection: bool = ..., flip: str = ..., smooth_steps: int = ..., smooth_factor: float = ...) -> set[str]:
    """Interpolate Grease Pencil strokes between frames"""
    ...

def interpolate_sequence(override_context: Optional[Union[dict, 'bpy.types.Context']] = None, execution_context: Optional[str] = None, undo: Optional[bool] = None, *, step: int = ..., layers: str = ..., exclude_breakdowns: bool = ..., use_selection: bool = ..., flip: str = ..., smooth_steps: int = ..., smooth_factor: float = ..., type: str = ..., easing: str = ..., back: float = ..., amplitude: float = ..., period: float = ...) -> set[str]:
    """Generate 'in-betweens' to smoothly interpolate between Grease Pencil frames"""
    ...

def join_selection(override_context: Optional[Union[dict, 'bpy.types.Context']] = None, execution_context: Optional[str] = None, undo: Optional[bool] = None, *, type: str = ...) -> set[str]:
    """New stroke from selected points/strokes"""
    ...

def layer_active(override_context: Optional[Union[dict, 'bpy.types.Context']] = None, execution_context: Optional[str] = None, undo: Optional[bool] = None, *, layer: int = ...) -> set[str]:
    """Set the active Grease Pencil layer"""
    ...

def layer_add(override_context: Optional[Union[dict, 'bpy.types.Context']] = None, execution_context: Optional[str] = None, undo: Optional[bool] = None, *, new_layer_name: str = ...) -> set[str]:
    """Add a new Grease Pencil layer in the active object"""
    ...

def layer_duplicate(override_context: Optional[Union[dict, 'bpy.types.Context']] = None, execution_context: Optional[str] = None, undo: Optional[bool] = None, *, empty_keyframes: bool = ...) -> set[str]:
    """Make a copy of the active Grease Pencil layer"""
    ...

def layer_duplicate_object(override_context: Optional[Union[dict, 'bpy.types.Context']] = None, execution_context: Optional[str] = None, undo: Optional[bool] = None, *, only_active: bool = ..., mode: str = ...) -> set[str]:
    """Make a copy of the active Grease Pencil layer to selected object"""
    ...

def layer_group_add(override_context: Optional[Union[dict, 'bpy.types.Context']] = None, execution_context: Optional[str] = None, undo: Optional[bool] = None, *, new_layer_group_name: str = ...) -> set[str]:
    """Add a new Grease Pencil layer group in the active object"""
    ...

def layer_group_color_tag(override_context: Optional[Union[dict, 'bpy.types.Context']] = None, execution_context: Optional[str] = None, undo: Optional[bool] = None, *, color_tag: str = ...) -> set[str]:
    """Change layer group icon"""
    ...

def layer_group_remove(override_context: Optional[Union[dict, 'bpy.types.Context']] = None, execution_context: Optional[str] = None, undo: Optional[bool] = None, *, keep_children: bool = ...) -> set[str]:
    """Remove Grease Pencil layer group in the active object"""
    ...

def layer_hide(override_context: Optional[Union[dict, 'bpy.types.Context']] = None, execution_context: Optional[str] = None, undo: Optional[bool] = None, *, unselected: bool = ...) -> set[str]:
    """Hide selected/unselected Grease Pencil layers"""
    ...

def layer_isolate(override_context: Optional[Union[dict, 'bpy.types.Context']] = None, execution_context: Optional[str] = None, undo: Optional[bool] = None, *, affect_visibility: bool = ...) -> set[str]:
    """Make only active layer visible/editable"""
    ...

def layer_lock_all(override_context: Optional[Union[dict, 'bpy.types.Context']] = None, execution_context: Optional[str] = None, undo: Optional[bool] = None, *, lock: bool = ...) -> set[str]:
    """Lock all Grease Pencil layers to prevent them from being accidentally modified"""
    ...

def layer_mask_add(override_context: Optional[Union[dict, 'bpy.types.Context']] = None, execution_context: Optional[str] = None, undo: Optional[bool] = None, *, name: str = ...) -> set[str]:
    """Add new layer as masking"""
    ...

def layer_mask_remove(override_context: Optional[Union[dict, 'bpy.types.Context']] = None, execution_context: Optional[str] = None, undo: Optional[bool] = None) -> set[str]:
    """Remove Layer Mask"""
    ...

def layer_mask_reorder(override_context: Optional[Union[dict, 'bpy.types.Context']] = None, execution_context: Optional[str] = None, undo: Optional[bool] = None, *, direction: str = ...) -> set[str]:
    """Reorder the active Grease Pencil mask layer up/down in the list"""
    ...

def layer_merge(override_context: Optional[Union[dict, 'bpy.types.Context']] = None, execution_context: Optional[str] = None, undo: Optional[bool] = None, *, mode: str = ...) -> set[str]:
    """Combine layers based on the mode into one layer"""
    ...

def layer_move(override_context: Optional[Union[dict, 'bpy.types.Context']] = None, execution_context: Optional[str] = None, undo: Optional[bool] = None, *, direction: str = ...) -> set[str]:
    """Move the active Grease Pencil layer or Group"""
    ...

def layer_remove(override_context: Optional[Union[dict, 'bpy.types.Context']] = None, execution_context: Optional[str] = None, undo: Optional[bool] = None) -> set[str]:
    """Remove the active Grease Pencil layer"""
    ...

def layer_reveal(override_context: Optional[Union[dict, 'bpy.types.Context']] = None, execution_context: Optional[str] = None, undo: Optional[bool] = None) -> set[str]:
    """Show all Grease Pencil layers"""
    ...

def material_copy_to_object(override_context: Optional[Union[dict, 'bpy.types.Context']] = None, execution_context: Optional[str] = None, undo: Optional[bool] = None, *, only_active: bool = ...) -> set[str]:
    """Append Materials of the active Grease Pencil to other object"""
    ...

def material_hide(override_context: Optional[Union[dict, 'bpy.types.Context']] = None, execution_context: Optional[str] = None, undo: Optional[bool] = None, *, invert: bool = ...) -> set[str]:
    """Hide active/inactive Grease Pencil material(s)"""
    ...

def material_isolate(override_context: Optional[Union[dict, 'bpy.types.Context']] = None, execution_context: Optional[str] = None, undo: Optional[bool] = None, *, affect_visibility: bool = ...) -> set[str]:
    """Toggle whether the active material is the only one that is editable and/or visible"""
    ...

def material_lock_all(override_context: Optional[Union[dict, 'bpy.types.Context']] = None, execution_context: Optional[str] = None, undo: Optional[bool] = None) -> set[str]:
    """Lock all Grease Pencil materials to prevent them from being accidentally modified"""
    ...

def material_lock_unselected(override_context: Optional[Union[dict, 'bpy.types.Context']] = None, execution_context: Optional[str] = None, undo: Optional[bool] = None) -> set[str]:
    """Lock any material not used in any selected stroke"""
    ...

def material_lock_unused(override_context: Optional[Union[dict, 'bpy.types.Context']] = None, execution_context: Optional[str] = None, undo: Optional[bool] = None) -> set[str]:
    """Lock and hide any material not used"""
    ...

def material_reveal(override_context: Optional[Union[dict, 'bpy.types.Context']] = None, execution_context: Optional[str] = None, undo: Optional[bool] = None) -> set[str]:
    """Unhide all hidden Grease Pencil materials"""
    ...

def material_select(override_context: Optional[Union[dict, 'bpy.types.Context']] = None, execution_context: Optional[str] = None, undo: Optional[bool] = None, *, deselect: bool = ...) -> set[str]:
    """Select/Deselect all Grease Pencil strokes using current material"""
    ...

def material_unlock_all(override_context: Optional[Union[dict, 'bpy.types.Context']] = None, execution_context: Optional[str] = None, undo: Optional[bool] = None) -> set[str]:
    """Unlock all Grease Pencil materials so that they can be edited"""
    ...

def move_to_layer(override_context: Optional[Union[dict, 'bpy.types.Context']] = None, execution_context: Optional[str] = None, undo: Optional[bool] = None, *, target_layer_name: str = ..., add_new_layer: bool = ...) -> set[str]:
    """Move selected strokes to another layer"""
    ...

def outline(override_context: Optional[Union[dict, 'bpy.types.Context']] = None, execution_context: Optional[str] = None, undo: Optional[bool] = None, *, type: str = ..., radius: float = ..., offset_factor: float = ..., corner_subdivisions: int = ...) -> set[str]:
    """Convert selected strokes to perimeter"""
    ...

def paintmode_toggle(override_context: Optional[Union[dict, 'bpy.types.Context']] = None, execution_context: Optional[str] = None, undo: Optional[bool] = None, *, back: bool = ...) -> set[str]:
    """Enter/Exit paint mode for Grease Pencil strokes"""
    ...

def paste(override_context: Optional[Union[dict, 'bpy.types.Context']] = None, execution_context: Optional[str] = None, undo: Optional[bool] = None, *, type: str = ..., paste_back: bool = ..., keep_world_transform: bool = ...) -> set[str]:
    """Paste Grease Pencil points or strokes from the internal clipboard to the active layer"""
    ...

def pen(override_context: Optional[Union[dict, 'bpy.types.Context']] = None, execution_context: Optional[str] = None, undo: Optional[bool] = None, *, extend: bool = ..., deselect: bool = ..., toggle: bool = ..., deselect_all: bool = ..., select_passthrough: bool = ..., extrude_point: bool = ..., extrude_handle: str = ..., delete_point: bool = ..., insert_point: bool = ..., move_segment: bool = ..., select_point: bool = ..., move_point: bool = ..., cycle_handle_type: bool = ..., size: float = ...) -> set[str]:
    """Construct and edit splines"""
    ...

def primitive_arc(override_context: Optional[Union[dict, 'bpy.types.Context']] = None, execution_context: Optional[str] = None, undo: Optional[bool] = None, *, subdivision: int = ..., type: str = ...) -> set[str]:
    """Create predefined Grease Pencil stroke arcs"""
    ...

def primitive_box(override_context: Optional[Union[dict, 'bpy.types.Context']] = None, execution_context: Optional[str] = None, undo: Optional[bool] = None, *, subdivision: int = ..., type: str = ...) -> set[str]:
    """Create predefined Grease Pencil stroke boxes"""
    ...

def primitive_circle(override_context: Optional[Union[dict, 'bpy.types.Context']] = None, execution_context: Optional[str] = None, undo: Optional[bool] = None, *, subdivision: int = ..., type: str = ...) -> set[str]:
    """Create predefined Grease Pencil stroke circles"""
    ...

def primitive_curve(override_context: Optional[Union[dict, 'bpy.types.Context']] = None, execution_context: Optional[str] = None, undo: Optional[bool] = None, *, subdivision: int = ..., type: str = ...) -> set[str]:
    """Create predefined Grease Pencil stroke curve shapes"""
    ...

def primitive_line(override_context: Optional[Union[dict, 'bpy.types.Context']] = None, execution_context: Optional[str] = None, undo: Optional[bool] = None, *, subdivision: int = ..., type: str = ...) -> set[str]:
    """Create predefined Grease Pencil stroke lines"""
    ...

def primitive_polyline(override_context: Optional[Union[dict, 'bpy.types.Context']] = None, execution_context: Optional[str] = None, undo: Optional[bool] = None, *, subdivision: int = ..., type: str = ...) -> set[str]:
    """Create predefined Grease Pencil stroke polylines"""
    ...

def relative_layer_mask_add(override_context: Optional[Union[dict, 'bpy.types.Context']] = None, execution_context: Optional[str] = None, undo: Optional[bool] = None, *, mode: str = ...) -> set[str]:
    """Mask active layer with layer above or below"""
    ...

def remove_fill_guides(override_context: Optional[Union[dict, 'bpy.types.Context']] = None, execution_context: Optional[str] = None, undo: Optional[bool] = None, *, mode: str = ...) -> set[str]:
    """Remove all the strokes that were created from the fill tool as guides"""
    ...

def reorder(override_context: Optional[Union[dict, 'bpy.types.Context']] = None, execution_context: Optional[str] = None, undo: Optional[bool] = None, *, direction: str = ...) -> set[str]:
    """Change the display order of the selected strokes"""
    ...

def reproject(override_context: Optional[Union[dict, 'bpy.types.Context']] = None, execution_context: Optional[str] = None, undo: Optional[bool] = None, *, type: str = ..., keep_original: bool = ..., offset: float = ...) -> set[str]:
    """Reproject the selected strokes from the current viewpoint as if they had been newly drawn (e.g. to fix problems from accidental 3D cursor movement or accidental viewport changes, or for matching deforming geometry)"""
    ...

def reset_uvs(override_context: Optional[Union[dict, 'bpy.types.Context']] = None, execution_context: Optional[str] = None, undo: Optional[bool] = None) -> set[str]:
    """Reset UV transformation to default values"""
    ...

def sculpt_paint(override_context: Optional[Union[dict, 'bpy.types.Context']] = None, execution_context: Optional[str] = None, undo: Optional[bool] = None, *, stroke: bpy_prop_collection['OperatorStrokeElement'] = ..., mode: str = ..., pen_flip: bool = ...) -> set[str]:
    """Sculpt strokes in the active Grease Pencil object"""
    ...

def sculptmode_toggle(override_context: Optional[Union[dict, 'bpy.types.Context']] = None, execution_context: Optional[str] = None, undo: Optional[bool] = None, *, back: bool = ...) -> set[str]:
    """Enter/Exit sculpt mode for Grease Pencil strokes"""
    ...

def select_all(override_context: Optional[Union[dict, 'bpy.types.Context']] = None, execution_context: Optional[str] = None, undo: Optional[bool] = None, *, action: str = ...) -> set[str]:
    """(De)select all visible strokes"""
    ...

def select_alternate(override_context: Optional[Union[dict, 'bpy.types.Context']] = None, execution_context: Optional[str] = None, undo: Optional[bool] = None, *, deselect_ends: bool = ...) -> set[str]:
    """Select alternated points in strokes with already selected points"""
    ...

def select_ends(override_context: Optional[Union[dict, 'bpy.types.Context']] = None, execution_context: Optional[str] = None, undo: Optional[bool] = None, *, amount_start: int = ..., amount_end: int = ...) -> set[str]:
    """Select end points of strokes"""
    ...

def select_less(override_context: Optional[Union[dict, 'bpy.types.Context']] = None, execution_context: Optional[str] = None, undo: Optional[bool] = None) -> set[str]:
    """Shrink the selection by one point"""
    ...

def select_linked(override_context: Optional[Union[dict, 'bpy.types.Context']] = None, execution_context: Optional[str] = None, undo: Optional[bool] = None) -> set[str]:
    """Select all points in curves with any point selection"""
    ...

def select_more(override_context: Optional[Union[dict, 'bpy.types.Context']] = None, execution_context: Optional[str] = None, undo: Optional[bool] = None) -> set[str]:
    """Grow the selection by one point"""
    ...

def select_random(override_context: Optional[Union[dict, 'bpy.types.Context']] = None, execution_context: Optional[str] = None, undo: Optional[bool] = None, *, ratio: float = ..., seed: int = ..., action: str = ...) -> set[str]:
    """Selects random points from the current strokes selection"""
    ...

def select_similar(override_context: Optional[Union[dict, 'bpy.types.Context']] = None, execution_context: Optional[str] = None, undo: Optional[bool] = None, *, mode: str = ..., threshold: float = ...) -> set[str]:
    """Select all strokes with similar characteristics"""
    ...

def separate(override_context: Optional[Union[dict, 'bpy.types.Context']] = None, execution_context: Optional[str] = None, undo: Optional[bool] = None, *, mode: str = ...) -> set[str]:
    """Separate the selected geometry into a new Grease Pencil object"""
    ...

def set_active_material(override_context: Optional[Union[dict, 'bpy.types.Context']] = None, execution_context: Optional[str] = None, undo: Optional[bool] = None) -> set[str]:
    """Set the selected stroke material as the active material"""
    ...

def set_corner_type(override_context: Optional[Union[dict, 'bpy.types.Context']] = None, execution_context: Optional[str] = None, undo: Optional[bool] = None, *, corner_type: str = ..., miter_angle: float = ...) -> set[str]:
    """Set the corner type of the selected points"""
    ...

def set_curve_resolution(override_context: Optional[Union[dict, 'bpy.types.Context']] = None, execution_context: Optional[str] = None, undo: Optional[bool] = None, *, resolution: int = ...) -> set[str]:
    """Set resolution of selected curves"""
    ...

def set_curve_type(override_context: Optional[Union[dict, 'bpy.types.Context']] = None, execution_context: Optional[str] = None, undo: Optional[bool] = None, *, type: str = ..., use_handles: bool = ...) -> set[str]:
    """Set type of selected curves"""
    ...

def set_handle_type(override_context: Optional[Union[dict, 'bpy.types.Context']] = None, execution_context: Optional[str] = None, undo: Optional[bool] = None, *, type: str = ...) -> set[str]:
    """Set the handle type for Bézier curves"""
    ...

def set_material(override_context: Optional[Union[dict, 'bpy.types.Context']] = None, execution_context: Optional[str] = None, undo: Optional[bool] = None, *, slot: str = ...) -> set[str]:
    """Set active material"""
    ...

def set_selection_mode(override_context: Optional[Union[dict, 'bpy.types.Context']] = None, execution_context: Optional[str] = None, undo: Optional[bool] = None, *, mode: str = ...) -> set[str]:
    """Change the selection mode for Grease Pencil strokes"""
    ...

def set_start_point(override_context: Optional[Union[dict, 'bpy.types.Context']] = None, execution_context: Optional[str] = None, undo: Optional[bool] = None) -> set[str]:
    """Select which point is the beginning of the curve"""
    ...

def set_uniform_opacity(override_context: Optional[Union[dict, 'bpy.types.Context']] = None, execution_context: Optional[str] = None, undo: Optional[bool] = None, *, opacity_stroke: float = ..., opacity_fill: float = ...) -> set[str]:
    """Set all stroke points to same opacity"""
    ...

def set_uniform_thickness(override_context: Optional[Union[dict, 'bpy.types.Context']] = None, execution_context: Optional[str] = None, undo: Optional[bool] = None, *, thickness: float = ...) -> set[str]:
    """Set all stroke points to same thickness"""
    ...

def snap_cursor_to_selected(override_context: Optional[Union[dict, 'bpy.types.Context']] = None, execution_context: Optional[str] = None, undo: Optional[bool] = None) -> set[str]:
    """Snap cursor to center of selected points"""
    ...

def snap_to_cursor(override_context: Optional[Union[dict, 'bpy.types.Context']] = None, execution_context: Optional[str] = None, undo: Optional[bool] = None, *, use_offset: bool = ...) -> set[str]:
    """Snap selected points/strokes to the cursor"""
    ...

def snap_to_grid(override_context: Optional[Union[dict, 'bpy.types.Context']] = None, execution_context: Optional[str] = None, undo: Optional[bool] = None) -> set[str]:
    """Snap selected points to the nearest grid points"""
    ...

def stroke_material_set(override_context: Optional[Union[dict, 'bpy.types.Context']] = None, execution_context: Optional[str] = None, undo: Optional[bool] = None, *, material: str = ...) -> set[str]:
    """Assign the active material slot to the selected strokes"""
    ...

def stroke_merge_by_distance(override_context: Optional[Union[dict, 'bpy.types.Context']] = None, execution_context: Optional[str] = None, undo: Optional[bool] = None, *, threshold: float = ..., use_unselected: bool = ...) -> set[str]:
    """Merge points by distance"""
    ...

def stroke_reset_vertex_color(override_context: Optional[Union[dict, 'bpy.types.Context']] = None, execution_context: Optional[str] = None, undo: Optional[bool] = None, *, mode: str = ...) -> set[str]:
    """Reset vertex color for all or selected strokes"""
    ...

def stroke_simplify(override_context: Optional[Union[dict, 'bpy.types.Context']] = None, execution_context: Optional[str] = None, undo: Optional[bool] = None, *, factor: float = ..., length: float = ..., distance: float = ..., steps: int = ..., mode: str = ...) -> set[str]:
    """Simplify selected strokes"""
    ...

def stroke_smooth(override_context: Optional[Union[dict, 'bpy.types.Context']] = None, execution_context: Optional[str] = None, undo: Optional[bool] = None, *, iterations: int = ..., factor: float = ..., smooth_ends: bool = ..., keep_shape: bool = ..., smooth_position: bool = ..., smooth_radius: bool = ..., smooth_opacity: bool = ...) -> set[str]:
    """Smooth selected strokes"""
    ...

def stroke_split(override_context: Optional[Union[dict, 'bpy.types.Context']] = None, execution_context: Optional[str] = None, undo: Optional[bool] = None) -> set[str]:
    """Split selected points to a new stroke"""
    ...

def stroke_subdivide(override_context: Optional[Union[dict, 'bpy.types.Context']] = None, execution_context: Optional[str] = None, undo: Optional[bool] = None, *, number_cuts: int = ..., only_selected: bool = ...) -> set[str]:
    """Subdivide between continuous selected points of the stroke adding a point half way between them"""
    ...

def stroke_subdivide_smooth(override_context: Optional[Union[dict, 'bpy.types.Context']] = None, execution_context: Optional[str] = None, undo: Optional[bool] = None, *, GREASE_PENCIL_OT_stroke_subdivide: 'GREASE_PENCIL_OT_stroke_subdivide' = ..., GREASE_PENCIL_OT_stroke_smooth: 'GREASE_PENCIL_OT_stroke_smooth' = ...) -> set[str]:
    """Subdivide strokes and smooth them"""
    ...

def stroke_switch_direction(override_context: Optional[Union[dict, 'bpy.types.Context']] = None, execution_context: Optional[str] = None, undo: Optional[bool] = None) -> set[str]:
    """Change direction of the points of the selected strokes"""
    ...

def stroke_trim(override_context: Optional[Union[dict, 'bpy.types.Context']] = None, execution_context: Optional[str] = None, undo: Optional[bool] = None, *, path: bpy_prop_collection['OperatorMousePath'] = ..., use_smooth_stroke: bool = ..., smooth_stroke_factor: float = ..., smooth_stroke_radius: int = ...) -> set[str]:
    """Delete stroke points in between intersecting strokes"""
    ...

def texture_gradient(override_context: Optional[Union[dict, 'bpy.types.Context']] = None, execution_context: Optional[str] = None, undo: Optional[bool] = None, *, xstart: int = ..., xend: int = ..., ystart: int = ..., yend: int = ..., flip: bool = ..., cursor: int = ...) -> set[str]:
    """Draw a line to set the fill material gradient for the selected strokes"""
    ...

def trace_image(override_context: Optional[Union[dict, 'bpy.types.Context']] = None, execution_context: Optional[str] = None, undo: Optional[bool] = None, *, target: str = ..., radius: float = ..., threshold: float = ..., turnpolicy: str = ..., mode: str = ..., use_current_frame: bool = ..., frame_number: int = ...) -> set[str]:
    """Extract Grease Pencil strokes from image"""
    ...

def vertex_brush_stroke(override_context: Optional[Union[dict, 'bpy.types.Context']] = None, execution_context: Optional[str] = None, undo: Optional[bool] = None, *, stroke: bpy_prop_collection['OperatorStrokeElement'] = ..., mode: str = ..., pen_flip: bool = ...) -> set[str]:
    """Draw on vertex colors in the active Grease Pencil object"""
    ...

def vertex_color_brightness_contrast(override_context: Optional[Union[dict, 'bpy.types.Context']] = None, execution_context: Optional[str] = None, undo: Optional[bool] = None, *, mode: str = ..., brightness: float = ..., contrast: float = ...) -> set[str]:
    """Adjust vertex color brightness/contrast"""
    ...

def vertex_color_hsv(override_context: Optional[Union[dict, 'bpy.types.Context']] = None, execution_context: Optional[str] = None, undo: Optional[bool] = None, *, mode: str = ..., h: float = ..., s: float = ..., v: float = ...) -> set[str]:
    """Adjust vertex color HSV values"""
    ...

def vertex_color_invert(override_context: Optional[Union[dict, 'bpy.types.Context']] = None, execution_context: Optional[str] = None, undo: Optional[bool] = None, *, mode: str = ...) -> set[str]:
    """Invert RGB values"""
    ...

def vertex_color_levels(override_context: Optional[Union[dict, 'bpy.types.Context']] = None, execution_context: Optional[str] = None, undo: Optional[bool] = None, *, mode: str = ..., offset: float = ..., gain: float = ...) -> set[str]:
    """Adjust levels of vertex colors"""
    ...

def vertex_color_set(override_context: Optional[Union[dict, 'bpy.types.Context']] = None, execution_context: Optional[str] = None, undo: Optional[bool] = None, *, mode: str = ..., factor: float = ...) -> set[str]:
    """Set active color to all selected vertex"""
    ...

def vertex_group_normalize(override_context: Optional[Union[dict, 'bpy.types.Context']] = None, execution_context: Optional[str] = None, undo: Optional[bool] = None) -> set[str]:
    """Normalize weights of the active vertex group"""
    ...

def vertex_group_normalize_all(override_context: Optional[Union[dict, 'bpy.types.Context']] = None, execution_context: Optional[str] = None, undo: Optional[bool] = None, *, lock_active: bool = ...) -> set[str]:
    """Normalize the weights of all vertex groups, so that for each vertex, the sum of all weights is 1.0"""
    ...

def vertex_group_smooth(override_context: Optional[Union[dict, 'bpy.types.Context']] = None, execution_context: Optional[str] = None, undo: Optional[bool] = None, *, factor: float = ..., repeat: int = ...) -> set[str]:
    """Smooth the weights of the active vertex group"""
    ...

def vertexmode_toggle(override_context: Optional[Union[dict, 'bpy.types.Context']] = None, execution_context: Optional[str] = None, undo: Optional[bool] = None, *, back: bool = ...) -> set[str]:
    """Enter/Exit vertex paint mode for Grease Pencil strokes"""
    ...

def weight_brush_stroke(override_context: Optional[Union[dict, 'bpy.types.Context']] = None, execution_context: Optional[str] = None, undo: Optional[bool] = None, *, stroke: bpy_prop_collection['OperatorStrokeElement'] = ..., mode: str = ..., pen_flip: bool = ...) -> set[str]:
    """Draw weight on stroke points in the active Grease Pencil object"""
    ...

def weight_invert(override_context: Optional[Union[dict, 'bpy.types.Context']] = None, execution_context: Optional[str] = None, undo: Optional[bool] = None) -> set[str]:
    """Invert the weight of active vertex group"""
    ...

def weight_sample(override_context: Optional[Union[dict, 'bpy.types.Context']] = None, execution_context: Optional[str] = None, undo: Optional[bool] = None) -> set[str]:
    """Set the weight of the Draw tool to the weight of the vertex under the mouse cursor"""
    ...

def weight_toggle_direction(override_context: Optional[Union[dict, 'bpy.types.Context']] = None, execution_context: Optional[str] = None, undo: Optional[bool] = None) -> set[str]:
    """Toggle Add/Subtract for the weight paint draw tool"""
    ...

def weightmode_toggle(override_context: Optional[Union[dict, 'bpy.types.Context']] = None, execution_context: Optional[str] = None, undo: Optional[bool] = None, *, back: bool = ...) -> set[str]:
    """Enter/Exit weight paint mode for Grease Pencil strokes"""
    ...
