# Blender Probe Generated Stub for Blender 5.0.1
# noinspection PyPep8Naming
# noinspection PyUnresolvedReferences
# noqa: N801
# pylint: disable=invalid-name

import sys
import typing
from typing import Any, Optional, Union, Sequence, Callable, Iterator
from .bpy_prop_collection import bpy_prop_collection

from .bpy_struct import bpy_struct
from .Material import Material
class BlendDataMaterials(bpy_struct):
    def new(self, *args, **kwargs) -> Any: ...
    def create_gpencil_data(self, *args, **kwargs) -> Any: ...
    def remove_gpencil_data(self, *args, **kwargs) -> Any: ...
    def remove(self, *args, **kwargs) -> Any: ...
    def tag(self, *args, **kwargs) -> Any: ...
    def __iter__(self) -> Iterator['Material']: ...
    def __getitem__(self, key: Union[str, int]) -> 'Material': ...
    def __len__(self) -> int: ...