# Blender Probe Generated Stub for Blender 5.0.1
# noinspection PyPep8Naming
# noinspection PyUnresolvedReferences
# noqa: N801
# pylint: disable=invalid-name

import sys
import typing
from typing import Any, Optional, Union, Sequence, Callable, Iterator
from .bpy_prop_collection import bpy_prop_collection

class bpy_struct:
    # --- Injected Methods ---
    def __getattr__(self, name) -> Any: ...
    def __setattr__(self, name: str, value: Any) -> None: ...
    def temp_override(self, window=None, area=None, region=None, **kwargs) -> Any: ...
    def as_pointer(self) -> int: ...
    def driver_add(self, path: str, index: int = -1) -> Any: ...
    def driver_remove(self, path: str, index: int = -1) -> bool: ...
    def get(self, key: str, default: Any = None) -> Any: ...
    def items(self) -> list[tuple[str, Any]]: ...
    def keys(self) -> list[str]: ...
    def values(self) -> list[Any]: ...
    def path_from_id(self, property: str = '') -> str: ...
    id_data: Any