# Blender Probe Generated Stub for Blender 5.0.1
# noinspection PyPep8Naming
# noinspection PyUnresolvedReferences
# noqa: N801
# pylint: disable=invalid-name

import sys
import typing
from typing import Any, Optional, Union, Sequence, Callable, Iterator
from .bpy_prop_collection import bpy_prop_collection

from .bpy_struct import bpy_struct
from .Keyframe import Keyframe
class FCurveKeyframePoints(bpy_struct):
    def insert(self, *args, **kwargs) -> Any: ...
    def add(self, *args, **kwargs) -> Any: ...
    def remove(self, *args, **kwargs) -> Any: ...
    def clear(self, *args, **kwargs) -> Any: ...
    def sort(self, *args, **kwargs) -> Any: ...
    def deduplicate(self, *args, **kwargs) -> Any: ...
    def handles_recalc(self, *args, **kwargs) -> Any: ...
    def __iter__(self) -> Iterator['Keyframe']: ...
    def __getitem__(self, key: Union[str, int]) -> 'Keyframe': ...
    def __len__(self) -> int: ...