# Blender Probe Generated Stub for Blender 5.0.1
# noinspection PyPep8Naming
# noinspection PyUnresolvedReferences
# noqa: N801
# pylint: disable=invalid-name

import sys
import typing
from typing import Any, Optional, Union, Sequence, Callable, Iterator
from .bpy_prop_collection import bpy_prop_collection

from .bpy_struct import bpy_struct
from .Collection import Collection
from .ColorRamp import ColorRamp
from .EffectorWeights import EffectorWeights
from .Object import Object
class FluidDomainSettings(bpy_struct):
    effector_weights: 'EffectorWeights'
    effector_group: 'Collection'
    fluid_group: 'Collection'
    force_collection: 'Collection'
    density_grid: list[float]
    velocity_grid: list[float]
    flame_grid: list[float]
    color_grid: list[float]
    heat_grid: list[float]
    temperature_grid: list[float]
    start_point: list[float]
    cell_size: list[float]
    domain_resolution: list[int]
    additional_res: int
    adapt_margin: int
    adapt_threshold: float
    use_adaptive_domain: bool
    resolution_max: int
    use_collision_border_front: bool
    use_collision_border_back: bool
    use_collision_border_right: bool
    use_collision_border_left: bool
    use_collision_border_top: bool
    use_collision_border_bottom: bool
    gravity: list[float]
    domain_type: str
    delete_in_obstacle: bool
    alpha: float
    beta: float
    dissolve_speed: int
    vorticity: float
    highres_sampling: str
    use_dissolve_smoke: bool
    use_dissolve_smoke_log: bool
    burning_rate: float
    flame_smoke: float
    flame_vorticity: float
    flame_ignition: float
    flame_max_temp: float
    flame_smoke_color: list[float]
    noise_strength: float
    noise_pos_scale: float
    noise_time_anim: float
    noise_scale: int
    use_noise: bool
    simulation_method: str
    flip_ratio: float
    particle_randomness: float
    particle_number: int
    particle_min: int
    particle_max: int
    particle_radius: float
    particle_band_width: float
    use_flip_particles: bool
    use_fractions: bool
    fractions_threshold: float
    fractions_distance: float
    sys_particle_maximum: int
    use_viscosity: bool
    viscosity_value: float
    use_diffusion: bool
    surface_tension: float
    viscosity_base: float
    viscosity_exponent: int
    mesh_concave_upper: float
    mesh_concave_lower: float
    mesh_smoothen_pos: int
    mesh_smoothen_neg: int
    mesh_scale: int
    mesh_generator: str
    use_mesh: bool
    use_speed_vectors: bool
    mesh_particle_radius: float
    sndparticle_potential_min_wavecrest: float
    sndparticle_potential_max_wavecrest: float
    sndparticle_potential_min_trappedair: float
    sndparticle_potential_max_trappedair: float
    sndparticle_potential_min_energy: float
    sndparticle_potential_max_energy: float
    sndparticle_sampling_wavecrest: int
    sndparticle_sampling_trappedair: int
    sndparticle_bubble_buoyancy: float
    sndparticle_bubble_drag: float
    sndparticle_life_min: float
    sndparticle_life_max: float
    sndparticle_boundary: str
    sndparticle_combined_export: str
    sndparticle_potential_radius: int
    sndparticle_update_radius: int
    particle_scale: int
    use_spray_particles: bool
    use_bubble_particles: bool
    use_foam_particles: bool
    use_tracer_particles: bool
    guide_alpha: float
    guide_beta: int
    guide_vel_factor: float
    guide_source: str
    guide_parent: 'Object'
    use_guide: bool
    cache_frame_start: int
    cache_frame_end: int
    cache_frame_offset: int
    cache_frame_pause_data: int
    cache_frame_pause_noise: int
    cache_frame_pause_mesh: int
    cache_frame_pause_particles: int
    cache_frame_pause_guide: int
    cache_mesh_format: str
    cache_data_format: str
    cache_particle_format: str
    cache_noise_format: str
    cache_type: str
    cache_resumable: bool
    cache_directory: str
    is_cache_baking_data: bool
    has_cache_baked_data: bool
    is_cache_baking_noise: bool
    has_cache_baked_noise: bool
    is_cache_baking_mesh: bool
    has_cache_baked_mesh: bool
    is_cache_baking_particles: bool
    has_cache_baked_particles: bool
    is_cache_baking_guide: bool
    has_cache_baked_guide: bool
    is_cache_baking_any: bool
    has_cache_baked_any: bool
    export_manta_script: bool
    openvdb_cache_compress_type: str
    openvdb_data_depth: str
    time_scale: float
    use_adaptive_timesteps: bool
    cfl_condition: float
    timesteps_min: int
    timesteps_max: int
    use_slice: bool
    slice_axis: str
    slice_per_voxel: float
    slice_depth: float
    display_thickness: float
    display_interpolation: str
    show_gridlines: bool
    show_velocity: bool
    vector_display_type: str
    vector_field: str
    vector_scale_with_magnitude: bool
    vector_show_mac_x: bool
    vector_show_mac_y: bool
    vector_show_mac_z: bool
    vector_scale: float
    use_color_ramp: bool
    color_ramp_field: str
    color_ramp_field_scale: float
    color_ramp: 'ColorRamp'
    clipping: float
    gridlines_color_field: str
    gridlines_lower_bound: float
    gridlines_upper_bound: float
    gridlines_range_color: list[float]
    gridlines_cell_filter: str
    velocity_scale: float