# Blender Probe Generated Stub for Blender 5.0.1
# noinspection PyPep8Naming
# noinspection PyUnresolvedReferences
# noqa: N801
# pylint: disable=invalid-name

import sys
import typing
from typing import Any, Optional, Union, Sequence, Callable, Iterator
from .bpy_prop_collection import bpy_prop_collection

from .GeometryNode import GeometryNode
from .Node import Node
from .NodeInputs import NodeInputs
from .NodeLink import NodeLink
from .NodeOutputs import NodeOutputs
from .NodeSocket import NodeSocket
class GeometryNodeObjectInfo(GeometryNode):
    type: str
    location: list[float]
    location_absolute: list[float]
    width: float
    height: float
    dimensions: list[float]
    name: str
    label: str
    inputs: 'NodeInputs'
    outputs: 'NodeOutputs'
    internal_links: bpy_prop_collection['NodeLink']
    parent: 'Node'
    warning_propagation: str
    use_custom_color: bool
    color: list[float]
    color_tag: str
    select: bool
    show_options: bool
    show_preview: bool
    hide: bool
    mute: bool
    show_texture: bool
    bl_idname: str
    bl_label: str
    bl_description: str
    bl_icon: str
    bl_static_type: str
    bl_width_default: float
    bl_width_min: float
    bl_width_max: float
    bl_height_default: float
    bl_height_min: float
    bl_height_max: float
    transform_space: str
    def bl_system_properties_get(self, *args, **kwargs) -> Any: ...
    def socket_value_update(self, *args, **kwargs) -> Any: ...
    def is_registered_node_type(self, *args, **kwargs) -> Any: ...
    def poll(self, *args, **kwargs) -> Any: ...
    def poll_instance(self, *args, **kwargs) -> Any: ...
    def update(self, *args, **kwargs) -> Any: ...
    def insert_link(self, *args, **kwargs) -> Any: ...
    def init(self, *args, **kwargs) -> Any: ...
    def copy(self, *args, **kwargs) -> Any: ...
    def free(self, *args, **kwargs) -> Any: ...
    def draw_buttons(self, *args, **kwargs) -> Any: ...
    def draw_buttons_ext(self, *args, **kwargs) -> Any: ...
    def draw_label(self, *args, **kwargs) -> Any: ...
    def debug_zone_body_lazy_function_graph(self, *args, **kwargs) -> Any: ...
    def debug_zone_lazy_function_graph(self, *args, **kwargs) -> Any: ...
    def poll(self, *args, **kwargs) -> Any: ...
    def poll_instance(self, *args, **kwargs) -> Any: ...
    def update(self, *args, **kwargs) -> Any: ...
    def draw_buttons(self, *args, **kwargs) -> Any: ...
    def draw_buttons_ext(self, *args, **kwargs) -> Any: ...
    def is_registered_node_type(self, *args, **kwargs) -> Any: ...
    def input_template(self, *args, **kwargs) -> Any: ...
    def output_template(self, *args, **kwargs) -> Any: ...