# Blender Probe Generated Stub for Blender 5.0.1
# noinspection PyPep8Naming
# noinspection PyUnresolvedReferences
# noqa: N801
# pylint: disable=invalid-name

import sys
import typing
from typing import Any, Optional, Union, Sequence, Callable, Iterator
from .bpy_prop_collection import bpy_prop_collection

from .RenderEngine import RenderEngine
from .Object import Object
from .RenderSettings import RenderSettings
class HydraRenderEngine(RenderEngine):
    is_animation: bool
    is_preview: bool
    camera_override: 'Object'
    layer_override: list[bool]
    resolution_x: int
    resolution_y: int
    temporary_directory: str
    render: 'RenderSettings'
    use_highlight_tiles: bool
    bl_idname: str
    bl_label: str
    bl_use_preview: bool
    bl_use_postprocess: bool
    bl_use_eevee_viewport: bool
    bl_use_custom_freestyle: bool
    bl_use_image_save: bool
    bl_use_gpu_context: bool
    bl_use_shading_nodes_custom: bool
    bl_use_spherical_stereo: bool
    bl_use_stereo_viewport: bool
    bl_use_materialx: bool
    def update(self, *args, **kwargs) -> Any: ...
    def render(self, *args, **kwargs) -> Any: ...
    def render_frame_finish(self, *args, **kwargs) -> Any: ...
    def draw(self, *args, **kwargs) -> Any: ...
    def bake(self, *args, **kwargs) -> Any: ...
    def view_update(self, *args, **kwargs) -> Any: ...
    def view_draw(self, *args, **kwargs) -> Any: ...
    def update_script_node(self, *args, **kwargs) -> Any: ...
    def update_render_passes(self, *args, **kwargs) -> Any: ...
    def update_custom_camera(self, *args, **kwargs) -> Any: ...
    def tag_redraw(self, *args, **kwargs) -> Any: ...
    def tag_update(self, *args, **kwargs) -> Any: ...
    def begin_result(self, *args, **kwargs) -> Any: ...
    def update_result(self, *args, **kwargs) -> Any: ...
    def end_result(self, *args, **kwargs) -> Any: ...
    def add_pass(self, *args, **kwargs) -> Any: ...
    def get_result(self, *args, **kwargs) -> Any: ...
    def test_break(self, *args, **kwargs) -> Any: ...
    def pass_by_index_get(self, *args, **kwargs) -> Any: ...
    def active_view_get(self, *args, **kwargs) -> Any: ...
    def active_view_set(self, *args, **kwargs) -> Any: ...
    def camera_shift_x(self, *args, **kwargs) -> Any: ...
    def camera_model_matrix(self, *args, **kwargs) -> Any: ...
    def use_spherical_stereo(self, *args, **kwargs) -> Any: ...
    def update_stats(self, *args, **kwargs) -> Any: ...
    def frame_set(self, *args, **kwargs) -> Any: ...
    def update_progress(self, *args, **kwargs) -> Any: ...
    def update_memory_stats(self, *args, **kwargs) -> Any: ...
    def report(self, *args, **kwargs) -> Any: ...
    def error_set(self, *args, **kwargs) -> Any: ...
    def bind_display_space_shader(self, *args, **kwargs) -> Any: ...
    def unbind_display_space_shader(self, *args, **kwargs) -> Any: ...
    def support_display_space_shader(self, *args, **kwargs) -> Any: ...
    def get_preview_pixel_size(self, *args, **kwargs) -> Any: ...
    def free_blender_memory(self, *args, **kwargs) -> Any: ...
    def tile_highlight_set(self, *args, **kwargs) -> Any: ...
    def tile_highlight_clear_all(self, *args, **kwargs) -> Any: ...
    def register_pass(self, *args, **kwargs) -> Any: ...