# Blender Probe Generated Stub for Blender 5.0.1
# noinspection PyPep8Naming
# noinspection PyUnresolvedReferences
# noqa: N801
# pylint: disable=invalid-name

import sys
import typing
from typing import Any, Optional, Union, Sequence, Callable, Iterator
from .bpy_prop_collection import bpy_prop_collection

from .bpy_struct import bpy_struct
from .KeyMapItem import KeyMapItem
class KeyMapItems(bpy_struct):
    def new(self, *args, **kwargs) -> Any: ...
    def new_modal(self, *args, **kwargs) -> Any: ...
    def new_from_item(self, *args, **kwargs) -> Any: ...
    def remove(self, *args, **kwargs) -> Any: ...
    def from_id(self, *args, **kwargs) -> Any: ...
    def find_from_operator(self, *args, **kwargs) -> Any: ...
    def find_match(self, *args, **kwargs) -> Any: ...
    def match_event(self, *args, **kwargs) -> Any: ...
    def __iter__(self) -> Iterator['KeyMapItem']: ...
    def __getitem__(self, key: Union[str, int]) -> 'KeyMapItem': ...
    def __len__(self) -> int: ...