# Blender Probe Generated Stub for Blender 5.0.1
# noinspection PyPep8Naming
# noinspection PyUnresolvedReferences
# noqa: N801
# pylint: disable=invalid-name

import sys
import typing
from typing import Any, Optional, Union, Sequence, Callable, Iterator
from .bpy_prop_collection import bpy_prop_collection

from .bpy_struct import bpy_struct
from .NodeGeometryViewerItem import NodeGeometryViewerItem
class NodeGeometryViewerItems(bpy_struct):
    def new(self, *args, **kwargs) -> Any: ...
    def remove(self, *args, **kwargs) -> Any: ...
    def clear(self, *args, **kwargs) -> Any: ...
    def move(self, *args, **kwargs) -> Any: ...
    def __iter__(self) -> Iterator['NodeGeometryViewerItem']: ...
    def __getitem__(self, key: Union[str, int]) -> 'NodeGeometryViewerItem': ...
    def __len__(self) -> int: ...