# Blender Probe Generated Stub for Blender 5.0.1
# noinspection PyPep8Naming
# noinspection PyUnresolvedReferences
# noqa: N801
# pylint: disable=invalid-name

import sys
import typing
from typing import Any, Optional, Union, Sequence, Callable, Iterator
from .bpy_prop_collection import bpy_prop_collection

from .bpy_struct import bpy_struct
from .NodeTreePath import NodeTreePath
class SpaceNodeEditorPath(bpy_struct):
    to_string: str
    def clear(self, *args, **kwargs) -> Any: ...
    def start(self, *args, **kwargs) -> Any: ...
    def append(self, *args, **kwargs) -> Any: ...
    def pop(self, *args, **kwargs) -> Any: ...
    def __iter__(self) -> Iterator['NodeTreePath']: ...
    def __getitem__(self, key: Union[str, int]) -> 'NodeTreePath': ...
    def __len__(self) -> int: ...