# Blender Probe Generated Stub for Blender 5.0.1
# noinspection PyPep8Naming
# noinspection PyUnresolvedReferences
# noqa: N801
# pylint: disable=invalid-name

import sys
import typing
from typing import Any, Optional, Union, Sequence, Callable, Iterator
from .bpy_prop_collection import bpy_prop_collection

from .bpy_struct import bpy_struct
from .Strip import Strip
class StripsMeta(bpy_struct):
    def new_clip(self, *args, **kwargs) -> Any: ...
    def new_mask(self, *args, **kwargs) -> Any: ...
    def new_scene(self, *args, **kwargs) -> Any: ...
    def new_image(self, *args, **kwargs) -> Any: ...
    def new_movie(self, *args, **kwargs) -> Any: ...
    def new_sound(self, *args, **kwargs) -> Any: ...
    def new_meta(self, *args, **kwargs) -> Any: ...
    def new_effect(self, *args, **kwargs) -> Any: ...
    def remove(self, *args, **kwargs) -> Any: ...
    def __iter__(self) -> Iterator['Strip']: ...
    def __getitem__(self, key: Union[str, int]) -> 'Strip': ...
    def __len__(self) -> int: ...