# Blender Probe Generated Stub for Blender 5.0.1
# noinspection PyPep8Naming
# noinspection PyUnresolvedReferences
# noqa: N801
# pylint: disable=invalid-name

import sys
import typing
from typing import Any, Optional, Union, Sequence, Callable, Iterator
from .bpy_prop_collection import bpy_prop_collection

from .ID import ID
from .Action import Action
from .AssetMetaData import AssetMetaData
from .IDOverrideLibrary import IDOverrideLibrary
from .ImagePreview import ImagePreview
from .KeyConfig import KeyConfig
from .KeyConfigurations import KeyConfigurations
from .Library import Library
from .LibraryWeakReference import LibraryWeakReference
from .Operator import Operator
from .Window import Window
from .XrSessionSettings import XrSessionSettings
from .XrSessionState import XrSessionState
class WindowManager(ID):
    name: str
    name_full: str
    id_type: str
    session_uid: int
    is_evaluated: bool
    original: 'ID'
    users: int
    use_fake_user: bool
    use_extra_user: bool
    is_embedded_data: bool
    is_linked_packed: bool
    is_missing: bool
    is_runtime_data: bool
    is_editable: bool
    tag: bool
    is_library_indirect: bool
    library: 'Library'
    library_weak_reference: 'LibraryWeakReference'
    asset_data: 'AssetMetaData'
    override_library: 'IDOverrideLibrary'
    preview: 'ImagePreview'
    operators: bpy_prop_collection['Operator']
    windows: bpy_prop_collection['Window']
    keyconfigs: 'KeyConfigurations'
    xr_session_settings: 'XrSessionSettings'
    xr_session_state: 'XrSessionState'
    extensions_updates: int
    extensions_blocked: int
    is_interface_locked: bool
    preset_name: str
    asset_path_dummy: str
    addon_search: str
    addon_filter: str
    addon_support: set[str]
    poselib_previous_action: 'Action'
    addon_tags: bpy_prop_collection['BlExtDummyGroup']
    extension_tags: bpy_prop_collection['BlExtDummyGroup']
    extension_search: str
    extension_type: str
    extension_show_panel_installed: bool
    extension_show_panel_available: bool
    def bl_system_properties_get(self, *args, **kwargs) -> Any: ...
    def rename(self, *args, **kwargs) -> Any: ...
    def evaluated_get(self, *args, **kwargs) -> Any: ...
    def copy(self, *args, **kwargs) -> Any: ...
    def asset_mark(self, *args, **kwargs) -> Any: ...
    def asset_clear(self, *args, **kwargs) -> Any: ...
    def asset_generate_preview(self, *args, **kwargs) -> Any: ...
    def override_create(self, *args, **kwargs) -> Any: ...
    def override_hierarchy_create(self, *args, **kwargs) -> Any: ...
    def user_clear(self, *args, **kwargs) -> Any: ...
    def user_remap(self, *args, **kwargs) -> Any: ...
    def make_local(self, *args, **kwargs) -> Any: ...
    def user_of_id(self, *args, **kwargs) -> Any: ...
    def animation_data_create(self, *args, **kwargs) -> Any: ...
    def animation_data_clear(self, *args, **kwargs) -> Any: ...
    def update_tag(self, *args, **kwargs) -> Any: ...
    def preview_ensure(self, *args, **kwargs) -> Any: ...
    def fileselect_add(self, *args, **kwargs) -> Any: ...
    def modal_handler_add(self, *args, **kwargs) -> Any: ...
    def event_timer_add(self, *args, **kwargs) -> Any: ...
    def event_timer_remove(self, *args, **kwargs) -> Any: ...
    def gizmo_group_type_ensure(self, *args, **kwargs) -> Any: ...
    def gizmo_group_type_unlink_delayed(self, *args, **kwargs) -> Any: ...
    def progress_begin(self, *args, **kwargs) -> Any: ...
    def progress_update(self, *args, **kwargs) -> Any: ...
    def progress_end(self, *args, **kwargs) -> Any: ...
    def invoke_props_popup(self, *args, **kwargs) -> Any: ...
    def invoke_props_dialog(self, *args, **kwargs) -> Any: ...
    def invoke_search_popup(self, *args, **kwargs) -> Any: ...
    def invoke_popup(self, *args, **kwargs) -> Any: ...
    def invoke_confirm(self, *args, **kwargs) -> Any: ...
    def popmenu_begin__internal(self, *args, **kwargs) -> Any: ...
    def popmenu_end__internal(self, *args, **kwargs) -> Any: ...
    def popover_begin__internal(self, *args, **kwargs) -> Any: ...
    def popover_end__internal(self, *args, **kwargs) -> Any: ...
    def piemenu_begin__internal(self, *args, **kwargs) -> Any: ...
    def piemenu_end__internal(self, *args, **kwargs) -> Any: ...
    def operator_properties_last(self, *args, **kwargs) -> Any: ...
    def print_undo_steps(self, *args, **kwargs) -> Any: ...
    def tag_script_reload(self, *args, **kwargs) -> Any: ...