# Blender Probe Generated Stub for Blender 5.0.1
# noinspection PyPep8Naming
# noinspection PyUnresolvedReferences
# noqa: N801
# pylint: disable=invalid-name

import sys
import typing
from typing import Any, Optional, Union, Sequence, Callable, Iterator
from .bpy_prop_collection import bpy_prop_collection

from .bpy_struct import bpy_struct
from .WorkSpaceTool import WorkSpaceTool
class wmTools(bpy_struct):
    def from_space_view3d_mode(self, *args, **kwargs) -> Any: ...
    def from_space_image_mode(self, *args, **kwargs) -> Any: ...
    def from_space_node(self, *args, **kwargs) -> Any: ...
    def from_space_sequencer(self, *args, **kwargs) -> Any: ...
    def __iter__(self) -> Iterator['WorkSpaceTool']: ...
    def __getitem__(self, key: Union[str, int]) -> 'WorkSpaceTool': ...
    def __len__(self) -> int: ...