# Blender Probe Generated Stub for Blender 5.0.1
# noinspection PyPep8Naming
# noinspection PyUnresolvedReferences
# noqa: N801
# pylint: disable=invalid-name

import sys
import typing
from typing import Any, Optional, Union, Sequence, Callable, Iterator
from .bpy_prop_collection import bpy_prop_collection

from .bpy_struct import bpy_struct
from .XrActionMap import XrActionMap
from .XrActionMaps import XrActionMaps
class XrSessionState(bpy_struct):
    viewer_pose_location: list[float]
    viewer_pose_rotation: list[float]
    navigation_location: list[float]
    navigation_rotation: list[float]
    navigation_scale: float
    actionmaps: 'XrActionMaps'
    active_actionmap: int
    selected_actionmap: int
    def is_running(self, *args, **kwargs) -> Any: ...
    def reset_to_base_pose(self, *args, **kwargs) -> Any: ...
    def action_set_create(self, *args, **kwargs) -> Any: ...
    def action_create(self, *args, **kwargs) -> Any: ...
    def action_binding_create(self, *args, **kwargs) -> Any: ...
    def active_action_set_set(self, *args, **kwargs) -> Any: ...
    def controller_pose_actions_set(self, *args, **kwargs) -> Any: ...
    def action_state_get(self, *args, **kwargs) -> Any: ...
    def haptic_action_apply(self, *args, **kwargs) -> Any: ...
    def haptic_action_stop(self, *args, **kwargs) -> Any: ...
    def controller_grip_location_get(self, *args, **kwargs) -> Any: ...
    def controller_grip_rotation_get(self, *args, **kwargs) -> Any: ...
    def controller_aim_location_get(self, *args, **kwargs) -> Any: ...
    def controller_aim_rotation_get(self, *args, **kwargs) -> Any: ...